FROM ubuntu:latest

RUN apt-get update -y && apt-get install -y postgresql-client curl

COPY customer/ledger /bin/ledger
COPY symbols/ /symbols
COPY entrypoint.sh /bin/entrypoint.sh

RUN chmod 777 /bin/entrypoint.sh

ENTRYPOINT ["/bin/entrypoint.sh"]
EXPOSE 8080
