image:
  repository: ghcr.io/formancehq/ledger-operator
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

leaderElection: true
watchNamespace: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

nameOverride: ""
fullnameOverride: ""
