{{- if .Values.headlessService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ledger-v3-poc.headlessServiceName" . }}
  labels:
    {{- include "ledger-v3-poc.labels" . | nindent 4 }}
  {{- with .Values.headlessService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  publishNotReadyAddresses: true
  selector:
    {{- include "ledger-v3-poc.selectorLabels" . | nindent 4 }}
{{- end }}

