name: Setup Env
description: Setup Env for Linux x64
inputs:
  token:
    description: 'A Github PAT'
    required: true
runs:
  using: composite
  steps:
    - uses: earthly/actions-setup@v1
      with:
        github-token: ${{ inputs.token }}
        version: "latest"
        use-cache: true
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: "Put back the git branch into git (Earthly uses it for tagging)"
      shell: bash
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true

