VERSION 0.8
PROJECT FormanceHQ/ledger

IMPORT github.com/formancehq/earthly:tags/v0.19.0 AS core

FROM core+base-image

sources:
    WORKDIR /src
    COPY *.go go.* Pulumi.yaml .
    SAVE ARTIFACT /src
