project_name: numary
env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
before:
  hooks:
    - go mod download

builds:
  - binary: numary
    id: numary_linux
    ldflags:
      - -X github.com/numary/ledger/cmd.BuildDate={{ .Date }}
      - -X github.com/numary/ledger/cmd.Version={{ .Version }}
      - -X github.com/numary/ledger/cmd.Commit={{ .ShortCommit }}
      - -extldflags "-static"
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
  - binary: numary
    id: numary_darwin
    ldflags:
      - -X github.com/numary/ledger/cmd.BuildDate={{ .Date }}
      - -X github.com/numary/ledger/cmd.Version={{ .Version }}
      - -X github.com/numary/ledger/cmd.Commit={{ .ShortCommit }}
      - -s
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/osxcross/target/bin/o64-clang
      - CXX=/home/runner/work/osxcross/target/bin/o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: "numary"
    builds:
      - numary_linux
      - numary_darwin
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows


checksum:
  name_template: 'checksums_linux.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^spec:'

release:
  prerelease: auto
  mode: replace

brews:
  - tap:
      owner: numary
      name: homebrew-tap
    name: numary
    folder: Formula
    homepage: https://numary.com
    skip_upload: false
    test: |
      system "#{bin}/numary version"
    install: |
      bin.install "numary"

nfpms:
  - id: packages
    package_name: numary
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - numary_linux
    homepage: https://numary.com
    maintainer: Maxence Maireaux <maxence@numary.com>
    formats:
      - deb
      - rpm

publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/numary/
