before:
  hooks:
    - go build -o numary
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
    binary: numary
archives:
  - replacements:
      darwin: macos
      amd64: x86_64
checksum:
  name_template: 'checksums-darwin.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
