---
volumes:
  postgres:
services:
  postgres:
    extends:
      file: ../../docker-compose.yml
      service: postgres
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one
    ports:
    - "16686:16686/tcp"
  ledger:
    extends:
      file: ../../docker-compose.yml
      service: ledger
    depends_on:
      - postgres
      - jaeger
    image: golang:1.19-alpine
    entrypoint: go run main.go server start
    volumes:
      - ../..:/src
    working_dir: /src
    ports:
    - "3068:3068/tcp"
    environment:
      CGO_ENABLED: 0
      DEBUG: "true"
      OTEL_TRACES: "true"
      OTEL_TRACES_EXPORTER: jaeger
      OTEL_TRACES_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      OTEL_SERVICE_NAME: ledger
