project_name: ledger
monorepo:
  tag_prefix: components/ledger/
  dir: ./

includes:
  - from_file:
      path: ./../../.goreleaser.default.yaml

builds:
  - binary: ledger
    id: ledger
    ldflags:
      - -X github.com/formancehq/ledger/cmd.BuildDate={{ .Date }}
      - -X github.com/formancehq/ledger/cmd.Version={{ .Version }}
      - -X github.com/formancehq/ledger/cmd.Commit={{ .ShortCommit }}
      - -X github.com/formancehq/ledger/cmd.DefaultSegmentWriteKey={{ .Env.SEGMENT_WRITE_KEY }}
      - -extldflags "-static"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64


archives:
  - id: "{{.ProjectName}}"
    builds:
      - gateway
    format: tar.gz
    name_template: "{{.ProjectName}}_{{.Os}}-{{.Arch}}"

nfpms:
  - id: packages
    package_name: ledger
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - ledger
    homepage: https://formance.com
    maintainer: Maxence Maireaux <maxence@formance.com>
    formats:
      - deb
      - rpm

publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/ledger/
