before:
  hooks:
    - go build
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: ./main
archives:
  - replacements:
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
