project_name: ledger
monorepo:
  tag_prefix: components/ledger/
  dir: ./components/ledger/

builds:
  - binary: ledger
    id: ledger_windows
    ldflags:
      - -X github.com/ledger/ledger/cmd.BuildDate={{ .Date }}
      - -X github.com/ledger/ledger/cmd.Version={{ .Version }}
      - -X github.com/ledger/ledger/cmd.Commit={{ .ShortCommit }}
      - -X github.com/ledger/ledger/cmd.DefaultSegmentWriteKey={{ .Env.SEGMENT_WRITE_KEY }}
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -tags=json1
  - binary: ledger
    id: ledger_linux_amd64
    ldflags:
      - -X github.com/ledger/ledger/cmd.BuildDate={{ .Date }}
      - -X github.com/ledger/ledger/cmd.Version={{ .Version }}
      - -X github.com/ledger/ledger/cmd.Commit={{ .ShortCommit }}
      - -X github.com/ledger/ledger/cmd.DefaultSegmentWriteKey={{ .Env.SEGMENT_WRITE_KEY }}
      - -extldflags "-static"
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=json1,netgo
  - binary: ledger
    id: ledger_linux_arm64
    ldflags:
      - -X github.com/ledger/ledger/cmd.BuildDate={{ .Date }}
      - -X github.com/ledger/ledger/cmd.Version={{ .Version }}
      - -X github.com/ledger/ledger/cmd.Commit={{ .ShortCommit }}
      - -X github.com/ledger/ledger/cmd.DefaultSegmentWriteKey={{ .Env.SEGMENT_WRITE_KEY }}
      - -extldflags "-static"
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -tags=json1,netgo

archives:
  - id: "ledger"
    builds:
      - ledger_linux_amd64
      - ledger_linux_arm64
      - ledger_windows
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows

nfpms:
  - id: packages
    package_name: ledger
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - ledger_linux_amd64
      - ledger_linux_arm64
    homepage: https://formance.com
    maintainer: Maxence Maireaux <maxence@formance.com>
    formats:
      - deb
      - rpm

publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/ledger/
