project_name: numary
env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
before:
  hooks:
    - go mod download

builds:
  - binary: numary
    id: numary_windows
    ldflags:
      - -X github.com/numary/ledger/cmd.BuildDate={{ .Date }}
      - -X github.com/numary/ledger/cmd.Version={{ .Version }}
      - -X github.com/numary/ledger/cmd.Commit={{ .ShortCommit }}
      - -X github.com/numary/ledger/cmd.DefaultSegmentWriteKey={{ .Env.SEGMENT_WRITE_KEY }}
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -tags=json1
  - binary: numary
    id: numary_linux
    ldflags:
      - -X github.com/numary/ledger/cmd.BuildDate={{ .Date }}
      - -X github.com/numary/ledger/cmd.Version={{ .Version }}
      - -X github.com/numary/ledger/cmd.Commit={{ .ShortCommit }}
      - -X github.com/numary/ledger/cmd.DefaultSegmentWriteKey={{ .Env.SEGMENT_WRITE_KEY }}
      - -extldflags "-static"
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=json1
  - binary: numary
    id: numary_darwin
    ldflags:
      - -X github.com/numary/ledger/cmd.BuildDate={{ .Date }}
      - -X github.com/numary/ledger/cmd.Version={{ .Version }}
      - -X github.com/numary/ledger/cmd.Commit={{ .ShortCommit }}
      - -X github.com/numary/ledger/cmd.DefaultSegmentWriteKey={{ .Env.SEGMENT_WRITE_KEY }}
      - -s
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/osxcross/target/bin/o64-clang
      - CXX=/home/runner/work/osxcross/target/bin/o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -tags=json1

archives:
  - id: "numary"
    builds:
      - numary_linux
      - numary_darwin
      - numary_windows
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows


checksum:
  name_template: 'checksums_linux.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^spec:'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

release:
  prerelease: auto
  footer: |
    **Full Changelog**: https://docs.formance.com/oss/ledger/changelog/{{ .Tag }}
    ## Want to try this version ?
    [![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/numary/ledger/tree/{{ .Tag }}&version={{ .Tag }})
    ## What to do next?
    - Read the [documentation](https://docs.numary.com/oss/ledger/get-started/installation)
    - Join our [Discord server](https://discord.gg/xyHvcbzk4w)

brews:
  - tap:
      owner: numary
      name: homebrew-tap
    name: numary
    folder: Formula
    homepage: https://numary.com
    skip_upload: auto
    test: |
      system "#{bin}/numary version"
    install: |
      bin.install "numary"

nfpms:
  - id: packages
    package_name: numary
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - numary_linux
    homepage: https://numary.com
    maintainer: Maxence Maireaux <maxence@numary.com>
    formats:
      - deb
      - rpm

publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/numary/
