project_name: numary

builds:
  - binary: numary
    id: numary_windows
    ldflags:
      - -X github.com/numary/ledger/cmd.BuildDate={{ .Date }}
      - -X github.com/numary/ledger/cmd.Version={{ .Version }}
      - -X github.com/numary/ledger/cmd.Commit={{ .ShortCommit }}
      - -X github.com/numary/ledger/cmd.DefaultSegmentWriteKey={{ .Env.SEGMENT_WRITE_KEY }}
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -tags=json1
  - binary: numary
    id: numary_linux_amd64
    ldflags:
      - -X github.com/numary/ledger/cmd.BuildDate={{ .Date }}
      - -X github.com/numary/ledger/cmd.Version={{ .Version }}
      - -X github.com/numary/ledger/cmd.Commit={{ .ShortCommit }}
      - -X github.com/numary/ledger/cmd.DefaultSegmentWriteKey={{ .Env.SEGMENT_WRITE_KEY }}
      - -extldflags "-static"
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=json1,netgo
  - binary: numary
    id: numary_linux_arm64
    ldflags:
      - -X github.com/numary/ledger/cmd.BuildDate={{ .Date }}
      - -X github.com/numary/ledger/cmd.Version={{ .Version }}
      - -X github.com/numary/ledger/cmd.Commit={{ .ShortCommit }}
      - -X github.com/numary/ledger/cmd.DefaultSegmentWriteKey={{ .Env.SEGMENT_WRITE_KEY }}
      - -extldflags "-static"
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -tags=json1,netgo

archives:
  - id: "numary"
    builds:
      - numary_linux_amd64
      - numary_linux_arm64
      - numary_windows
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows


checksum:
  name_template: '{{.ProjectName}}_checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^spec:'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

release:
  prerelease: auto
  footer: |
    ## What to do next?
    - Read the [documentation](https://docs.formance.com/)
    - Join our [Slack server](https://formance.com/slack)

nfpms:
  - id: packages
    package_name: numary
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - numary_linux_amd64
      - numary_linux_arm64
    homepage: https://formance.com
    maintainer: Maxence Maireaux <maxence@formance.com>
    formats:
      - deb
      - rpm

publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/numary/


dockers:
  - image_templates: ["ghcr.io/formancehq/{{ .ProjectName }}:{{ .Version }}-amd64"]
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/formancehq/stack
      - --label=org.opencontainers.image.source=https://github.com/formancehq/stack
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - image_templates: [ "ghcr.io/formancehq/{{ .ProjectName }}:{{ .Version }}-arm64" ]
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/formancehq/stack
      - --label=org.opencontainers.image.source=https://github.com/formancehq/stack
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
  - name_template: ghcr.io/formancehq/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/formancehq/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/formancehq/{{ .ProjectName }}:{{ .Version }}-arm64
  - name_template: ghcr.io/formancehq/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/formancehq/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/formancehq/{{ .ProjectName }}:{{ .Version }}-arm64
