services: 
  - type: web
    name: ledger-web
    plan: starter
    env: go
    startCommand: bin/ledger server start --server.http.bind_address 0.0.0.0:${PORT} --storage.driver postgres --storage.postgres.conn_string ${DATABASE_URL} --lock-strategy redis --lock-strategy-redis-url ${REDIS_URL}
    envVars: 
      - key: DATABASE_URL
        fromDatabase:
          name: ledger-db
          propert: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: ledger-redis
          property: connectionString
      - key: NUMARY_AUTH_BASIC_ENABLED
        value: true
      - key: NUMARY_AUTH_BASIC_CREDENTIALS
        sync: false
   - type:
