image:
  repository: fo.registry.ovh-gra.kers.sh/formancehq/ledger-v3-poc

imagePullSecrets:
  - name: zot

config:
  debug: false

  monitoring:
    # Service name for monitoring
    serviceName: "ledger-v3-poc"
    # Traces configuration
    traces:
      enabled: true
      exporter: "otlp"
      endpoint: "opentelemetry-collector.monitoring.svc.cluster.local"
      port: "4317"
      insecure: "true"
      mode: "grpc"
      batch: "true"

ingress:
  enabled: true
  #className: ""  # Ingress class name (e.g., "nginx", "traefik")
  #annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: ledger-exp.gfyrag.v2.formance.dev
      paths:
        - path: /
          pathType: Prefix
  #tls: []
  # Uncomment to enable per-pod ingress (for accessing individual pods from outside)
  perPod:
    enabled: true
  #   annotations:
  #     traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
  #     traefik.ingress.kubernetes.io/router.tls: "true"

extraData:
  enabled: true
  mountPath: /data/extra
  storageClass: "" # Use default storage class if empty
  accessMode: ReadWriteOnce
  size: 10Gi
  annotations: {}

persistence:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete