// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/ledger/pkg/client/internal/utils"
	"math/big"
)

// AccountWithVolumesAndBalances - An account together with its volumes and net balances per asset
type AccountWithVolumesAndBalances struct {
	// The account address, a colon-separated segmented path such as users:001
	Address string `json:"address"`
	// Free-form classification of the account
	Type *string `json:"type,omitempty"`
	// Arbitrary key/value pairs attached to the account
	Metadata map[string]any `json:"metadata,omitempty"`
	// Volumes per asset for a single account
	Volumes map[string]Volume `json:"volumes,omitempty"`
	// Net balance per asset, equal to input minus output
	Balances map[string]*big.Int `json:"balances,omitempty"`
}

func (a AccountWithVolumesAndBalances) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountWithVolumesAndBalances) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountWithVolumesAndBalances) GetAddress() string {
	if a == nil {
		return ""
	}
	return a.Address
}

func (a *AccountWithVolumesAndBalances) GetType() *string {
	if a == nil {
		return nil
	}
	return a.Type
}

func (a *AccountWithVolumesAndBalances) GetMetadata() map[string]any {
	if a == nil {
		return nil
	}
	return a.Metadata
}

func (a *AccountWithVolumesAndBalances) GetVolumes() map[string]Volume {
	if a == nil {
		return nil
	}
	return a.Volumes
}

func (a *AccountWithVolumesAndBalances) GetBalances() map[string]*big.Int {
	if a == nil {
		return nil
	}
	return a.Balances
}
