// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateLedgerInBucketResponse struct {
	Data *LedgerInfo `json:"data,omitempty"`
}

func (o *CreateLedgerInBucketResponse) GetData() *LedgerInfo {
	if o == nil {
		return nil
	}
	return o.Data
}
