// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// CreateBucketRequestDriver - Driver name (e.g., "sqlite")
type CreateBucketRequestDriver string

const (
	CreateBucketRequestDriverSqlite CreateBucketRequestDriver = "sqlite"
)

func (e CreateBucketRequestDriver) ToPointer() *CreateBucketRequestDriver {
	return &e
}
func (e *CreateBucketRequestDriver) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "sqlite":
		*e = CreateBucketRequestDriver(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateBucketRequestDriver: %v", v)
	}
}

type CreateBucketRequest struct {
	// Driver name (e.g., "sqlite")
	Driver CreateBucketRequestDriver `json:"driver"`
	// SQLite driver configuration (empty object - DSN is automatically generated)
	Config *SQLiteConfig `json:"config,omitempty"`
	// Number of logs before triggering a snapshot (optional, uses global config if not set)
	SnapshotThreshold *int64 `json:"snapshotThreshold,omitempty"`
}

func (o *CreateBucketRequest) GetDriver() CreateBucketRequestDriver {
	if o == nil {
		return CreateBucketRequestDriver("")
	}
	return o.Driver
}

func (o *CreateBucketRequest) GetConfig() *SQLiteConfig {
	if o == nil {
		return nil
	}
	return o.Config
}

func (o *CreateBucketRequest) GetSnapshotThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.SnapshotThreshold
}
