// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ErrorResponse struct {
	// Machine-readable error code identifying the failure
	ErrorCode ErrorsEnum `json:"errorCode"`
	// Human-readable description of the error
	ErrorMessage string `json:"errorMessage"`
	// Optional link carrying additional context about the error, such as a Numscript playground URL reproducing it
	Details *string `json:"details,omitempty"`
}

func (e *ErrorResponse) GetErrorCode() ErrorsEnum {
	if e == nil {
		return ErrorsEnum("")
	}
	return e.ErrorCode
}

func (e *ErrorResponse) GetErrorMessage() string {
	if e == nil {
		return ""
	}
	return e.ErrorMessage
}

func (e *ErrorResponse) GetDetails() *string {
	if e == nil {
		return nil
	}
	return e.Details
}
