// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MappingResponse struct {
	Data *Mapping `json:"data,omitempty"`
}

func (m *MappingResponse) GetData() *Mapping {
	if m == nil {
		return nil
	}
	return m.Data
}
