// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Mapping - Contracts constraining the balances a ledger's accounts may hold
type Mapping struct {
	// Constraints enforced on the ledger's accounts
	Contracts []Contract `json:"contracts"`
}

func (m *Mapping) GetContracts() []Contract {
	if m == nil {
		return []Contract{}
	}
	return m.Contracts
}
