// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/formancehq/ledger-v3-poc/pkg/client/internal/utils"
	"math/big"
)

type PostingResponse struct {
	Source      string `json:"source"`
	Destination string `json:"destination"`
	// Amount as a big integer
	Amount *big.Int `json:"amount"`
	Asset  string   `json:"asset"`
}

func (p PostingResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostingResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *PostingResponse) GetSource() string {
	if o == nil {
		return ""
	}
	return o.Source
}

func (o *PostingResponse) GetDestination() string {
	if o == nil {
		return ""
	}
	return o.Destination
}

func (o *PostingResponse) GetAmount() *big.Int {
	if o == nil {
		return big.NewInt(0)
	}
	return o.Amount
}

func (o *PostingResponse) GetAsset() string {
	if o == nil {
		return ""
	}
	return o.Asset
}
