// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StatsResponse struct {
	Data Stats `json:"data"`
}

func (s *StatsResponse) GetData() Stats {
	if s == nil {
		return Stats{}
	}
	return s.Data
}
