// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2ListExportersResponseCursorCursor struct {
	PageSize int64        `json:"pageSize"`
	HasMore  bool         `json:"hasMore"`
	Previous *string      `json:"previous,omitempty"`
	Next     *string      `json:"next,omitempty"`
	Data     []V2Exporter `json:"data"`
}

func (o *V2ListExportersResponseCursorCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *V2ListExportersResponseCursorCursor) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *V2ListExportersResponseCursorCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *V2ListExportersResponseCursorCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *V2ListExportersResponseCursorCursor) GetData() []V2Exporter {
	if o == nil {
		return []V2Exporter{}
	}
	return o.Data
}

type V2ListExportersResponseCursor struct {
	Cursor V2ListExportersResponseCursorCursor `json:"cursor"`
	Data   []V2Exporter                        `json:"data,omitempty"`
}

func (o *V2ListExportersResponseCursor) GetCursor() V2ListExportersResponseCursorCursor {
	if o == nil {
		return V2ListExportersResponseCursorCursor{}
	}
	return o.Cursor
}

func (o *V2ListExportersResponseCursor) GetData() []V2Exporter {
	if o == nil {
		return nil
	}
	return o.Data
}

// V2ListExportersResponse - Exporters list
type V2ListExportersResponse struct {
	Cursor *V2ListExportersResponseCursor `json:"cursor,omitempty"`
}

func (o *V2ListExportersResponse) GetCursor() *V2ListExportersResponseCursor {
	if o == nil {
		return nil
	}
	return o.Cursor
}
