// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2PipelinesCursorResponseCursor struct {
	PageSize int64        `json:"pageSize"`
	HasMore  bool         `json:"hasMore"`
	Previous *string      `json:"previous,omitempty"`
	Next     *string      `json:"next,omitempty"`
	Data     []V2Pipeline `json:"data"`
}

func (v *V2PipelinesCursorResponseCursor) GetPageSize() int64 {
	if v == nil {
		return 0
	}
	return v.PageSize
}

func (v *V2PipelinesCursorResponseCursor) GetHasMore() bool {
	if v == nil {
		return false
	}
	return v.HasMore
}

func (v *V2PipelinesCursorResponseCursor) GetPrevious() *string {
	if v == nil {
		return nil
	}
	return v.Previous
}

func (v *V2PipelinesCursorResponseCursor) GetNext() *string {
	if v == nil {
		return nil
	}
	return v.Next
}

func (v *V2PipelinesCursorResponseCursor) GetData() []V2Pipeline {
	if v == nil {
		return []V2Pipeline{}
	}
	return v.Data
}

// #region class-body-v2pipelinescursorresponsecursor
// #endregion class-body-v2pipelinescursorresponsecursor

// V2PipelinesCursorResponse - Pipelines list
type V2PipelinesCursorResponse struct {
	Cursor V2PipelinesCursorResponseCursor `json:"cursor"`
}

func (v *V2PipelinesCursorResponse) GetCursor() V2PipelinesCursorResponseCursor {
	if v == nil {
		return V2PipelinesCursorResponseCursor{}
	}
	return v.Cursor
}

// #region class-body-v2pipelinescursorresponse
// #endregion class-body-v2pipelinescursorresponse
