// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2RevertTransactionResponse struct {
	// A transaction recorded in the ledger, carrying its postings, metadata and both bi-temporal timestamps
	Data V2Transaction `json:"data"`
}

func (v *V2RevertTransactionResponse) GetData() V2Transaction {
	if v == nil {
		return V2Transaction{}
	}
	return v.Data
}

// #region class-body-v2reverttransactionresponse
// #endregion class-body-v2reverttransactionresponse
