// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V2SchemasCursor - Paginated cursor over the ledger's schemas
type V2SchemasCursor struct {
	// The schemas on this page
	Data []V2Schema `json:"data"`
	// Whether further pages are available
	HasMore bool `json:"hasMore"`
	// Cursor for the previous page, absent on the first page
	Previous *string `json:"previous,omitempty"`
	// Cursor for the next page, absent on the last page
	Next *string `json:"next,omitempty"`
	// Number of items requested per page
	PageSize int64 `json:"pageSize"`
}

func (v *V2SchemasCursor) GetData() []V2Schema {
	if v == nil {
		return []V2Schema{}
	}
	return v.Data
}

func (v *V2SchemasCursor) GetHasMore() bool {
	if v == nil {
		return false
	}
	return v.HasMore
}

func (v *V2SchemasCursor) GetPrevious() *string {
	if v == nil {
		return nil
	}
	return v.Previous
}

func (v *V2SchemasCursor) GetNext() *string {
	if v == nil {
		return nil
	}
	return v.Next
}

func (v *V2SchemasCursor) GetPageSize() int64 {
	if v == nil {
		return 0
	}
	return v.PageSize
}

// #region class-body-v2schemascursor
// #endregion class-body-v2schemascursor
