// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V2SchemaResponse struct {
	// Complete schema structure with metadata
	Data V2Schema `json:"data"`
}

func (o *V2SchemaResponse) GetData() V2Schema {
	if o == nil {
		return V2Schema{}
	}
	return o.Data
}
