// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type V2VolumesWithBalanceCursorResponseResource string

const (
	V2VolumesWithBalanceCursorResponseResourceVolumes V2VolumesWithBalanceCursorResponseResource = "volumes"
)

func (e V2VolumesWithBalanceCursorResponseResource) ToPointer() *V2VolumesWithBalanceCursorResponseResource {
	return &e
}
func (e *V2VolumesWithBalanceCursorResponseResource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "volumes":
		*e = V2VolumesWithBalanceCursorResponseResource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for V2VolumesWithBalanceCursorResponseResource: %v", v)
	}
}

type V2VolumesWithBalanceCursorResponseCursor struct {
	PageSize int64                  `json:"pageSize"`
	HasMore  bool                   `json:"hasMore"`
	Previous *string                `json:"previous,omitempty"`
	Next     *string                `json:"next,omitempty"`
	Data     []V2VolumesWithBalance `json:"data"`
}

func (o *V2VolumesWithBalanceCursorResponseCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *V2VolumesWithBalanceCursorResponseCursor) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *V2VolumesWithBalanceCursorResponseCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *V2VolumesWithBalanceCursorResponseCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *V2VolumesWithBalanceCursorResponseCursor) GetData() []V2VolumesWithBalance {
	if o == nil {
		return []V2VolumesWithBalance{}
	}
	return o.Data
}

type V2VolumesWithBalanceCursorResponse struct {
	Resource *V2VolumesWithBalanceCursorResponseResource `json:"resource,omitempty"`
	Cursor   V2VolumesWithBalanceCursorResponseCursor    `json:"cursor"`
}

func (o *V2VolumesWithBalanceCursorResponse) GetResource() *V2VolumesWithBalanceCursorResponseResource {
	if o == nil {
		return nil
	}
	return o.Resource
}

func (o *V2VolumesWithBalanceCursorResponse) GetCursor() V2VolumesWithBalanceCursorResponseCursor {
	if o == nil {
		return V2VolumesWithBalanceCursorResponseCursor{}
	}
	return o.Cursor
}
