
mod config
mod workload

tag := "antithesis"

run duration description='ledger-v3 manual run' *ARGS:
    just push-images {{ARGS}}
    curl --fail \
        --user "formance:$ANTITHESIS_PASSWORD" \
        -X POST https://formance.antithesis.com/api/v1/launch/basic_test -d '{ \
            "params": { \
                "custom.duration": "{{duration}}", \
                "custom.containers_to_exclude_from_network_faults":"etcd-0 etcd-1 etcd-2 workload", \
                "antithesis.report.recipients": "'"$ANTITHESIS_REPORT_RECIPIENT"'", \
                "antithesis.config_image": "'"antithesis-config-ledger-v3:{{tag}}"'", \
                "antithesis.description": "{{description}}", \
                "antithesis.images": "'"workload-ledger-v3:{{tag}};ledger-v3-poc:{{tag}};etcd:v3.5.9"'" \
            } \
        }'

build-images:
    # etcd (tag from public registry for Antithesis)
    docker pull --platform linux/amd64 quay.io/coreos/etcd:v3.5.9
    docker tag quay.io/coreos/etcd:v3.5.9 "$ANTITHESIS_REPOSITORY/etcd:v3.5.9"

    # ledger (instrumented for Antithesis)
    docker build \
        --platform linux/amd64 \
        -f ../../Dockerfile.antithesis \
        --progress=plain \
        -t "$ANTITHESIS_REPOSITORY/ledger-v3-poc:{{tag}}" \
        ../../

push-images *ARGS:
    just build-images
    just --justfile config/Justfile -d config push {{ARGS}}
    just --justfile workload/Justfile -d workload push
    docker push $ANTITHESIS_REPOSITORY/ledger-v3-poc:{{tag}}
    docker push $ANTITHESIS_REPOSITORY/etcd:v3.5.9

deploy-local: build-images
    #!/usr/bin/env bash

    set -euo pipefail
    tmpdir=$(mktemp -d)
    trap 'rm -rf $tmpdir' EXIT

    just config/build-config "$tmpdir/docker-compose.yaml"
    just workload/build

    docker compose -f "$tmpdir/docker-compose.yaml" up
