# Default values for k6 TestRun
# Usage: just k6-run <script>.js values.yaml
spec:
  parallelism: 1
  arguments: "-o opentelemetry"
metadata:
  namespace: ledger-exp
runner:
  env:
    LEDGER_URL: "http://ledger-exp.ledger-exp.svc.cluster.local:9000"
    LEDGER_NAME: "ledger0"
    K6_STAGES: "1m:10"
    # OTLP configuration
    K6_OTEL_GRPC_EXPORTER_ENDPOINT: "otel-opentelemetry-collector.ledger-exp.svc.cluster.local:4317"
    K6_OTEL_GRPC_EXPORTER_INSECURE: "true"
    K6_OTEL_METRICS_FLUSH_INTERVAL: "5s"
    K6_OTEL_SERVICE_NAME: "k6-loadtest"
    K6_OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  nodeSelector: {}
  tolerations: []
