# Default values for k6 TestRun
# Usage: just k6-run <script>.js values.yaml
spec:
  parallelism: 1
metadata:
  namespace: ledger-exp
runner:
  env:
    ledgerUrl: "http://ledger-exp.ledger-exp.svc.cluster.local:9000"
    ledgerName: "ledger0"
    stages: "1m:10"
  otlp:
    endpoint: "otel-opentelemetry-collector.ledger-exp.svc.cluster.local:4317"
  nodeSelector: {}
  tolerations: []
