# Default values for k6 TestRun
# Usage: just k6-run <script>.js values.yaml
spec:
  parallelism: 3
  separate: true
metadata:
  namespace: ledger-exp
runner:
  env:
    ledgerUrl: "http://ledger-exp.ledger-exp.svc.cluster.local:9000"
    ledgerName: "ledger0"
    stages: "3m:1600,3m:1600,3m:0"
  otlp:
    endpoint: "otel-opentelemetry-collector.ledger-exp.svc.cluster.local:4317"
  nodeSelector:
    formance.com/dedicated: benchmark
  tolerations:
    - effect: NoSchedule
      key: formance.com/dedicated
      operator: Equal
      value: benchmark

