# ACME values for k6 TestRun
# Usage: just k6-run <script>.js values.acme.yaml
grpcurl:
  arch: "arm64"

spec:
  parallelism: 1
  separate: true
  arguments: "-o opentelemetry"
metadata:
  namespace: ledger-v3

runner:
  env:
    GRPC_ADDR: "benchmark0.ledger-v3.svc.cluster.local:8888"
    LEDGER_NAME: "ledger0"
    K6_STAGES: "1m:100,5m:100,1m:0"
    BULK_SIZE: "50"
    BULK_ATOMIC: "true"
    # OTLP configuration
    K6_OTEL_GRPC_EXPORTER_ENDPOINT: "opentelemetry-collector.monitoring.svc.cluster.local:4317"
    K6_OTEL_GRPC_EXPORTER_INSECURE: "true"
    K6_OTEL_METRICS_FLUSH_INTERVAL: "5s"
    K6_OTEL_SERVICE_NAME: "k6-loadtest"
#  nodeSelector:
#    formance.com/dedicated: benchmark
#  tolerations:
#    - effect: NoSchedule
#      key: formance.com/dedicated
#      operator: Equal
#      value: benchmark
#
