---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: {{ include "k6-run.fullname" . }}
  {{- if .Values.metadata.namespace }}
  namespace: {{ .Values.metadata.namespace }}
  {{- end }}
spec:
  parallelism: {{ .Values.spec.parallelism }}
  {{ if .Values.runner.otlp.endpoint }}
  arguments: -o opentelemetry
  {{ end }}
  {{- if .Values.spec.separate }}
  separate: {{ .Values.spec.separate }}
  {{- end }}
  {{- if .Values.spec.cleanup }}
  cleanup: '{{ .Values.spec.cleanup }}'
  {{- end }}
  script:
    configMap:
      name: {{ include "k6-run.configmapName" . }}
      file: {{ .Values.script }}.tar
  runner:
    env:
    - name: LEDGER_URL
      value: {{ .Values.runner.env.ledgerUrl }}
    {{- if .Values.runner.env.ledgerName }}
    - name: LEDGER_NAME
      value: {{ .Values.runner.env.ledgerName }}
    {{- end }}
    {{- if .Values.runner.env.stages }}
    - name: K6_STAGES
      value: "{{ .Values.runner.env.stages }}"
    {{- end }}
    {{ if .Values.runner.otlp.endpoint }}
    - name: K6_OTEL_GRPC_EXPORTER_ENDPOINT
      value: {{ .Values.runner.otlp.endpoint }}
    - name: K6_OTEL_GRPC_EXPORTER_INSECURE
      value: "true"
    - name: K6_OTEL_METRICS_FLUSH_INTERVAL
      value: "5s"
    - name: K6_OTEL_SERVICE_NAME
      value: k6-loadtest
    - name: K6_OTEL_EXPORTER_OTLP_PROTOCOL
      value: http/protobuf
    {{ end }}
