// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: cluster_bootstrap.proto

package clusterbootstrappb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersRequest) Reset() {
	*x = GetPeersRequest{}
	mi := &file_cluster_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersRequest) ProtoMessage() {}

func (x *GetPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersRequest.ProtoReflect.Descriptor instead.
func (*GetPeersRequest) Descriptor() ([]byte, []int) {
	return file_cluster_bootstrap_proto_rawDescGZIP(), []int{0}
}

type GetPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersResponse) Reset() {
	*x = GetPeersResponse{}
	mi := &file_cluster_bootstrap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersResponse) ProtoMessage() {}

func (x *GetPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_bootstrap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersResponse.ProtoReflect.Descriptor instead.
func (*GetPeersResponse) Descriptor() ([]byte, []int) {
	return file_cluster_bootstrap_proto_rawDescGZIP(), []int{1}
}

func (x *GetPeersResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

// PeerInfo carries the minimum information a joining node needs to
// populate its initial WAL snapshot and dial the leader.
type PeerInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RaftAddress    string                 `protobuf:"bytes,2,opt,name=raft_address,json=raftAddress,proto3" json:"raft_address,omitempty"`
	ServiceAddress string                 `protobuf:"bytes,3,opt,name=service_address,json=serviceAddress,proto3" json:"service_address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_cluster_bootstrap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_bootstrap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_cluster_bootstrap_proto_rawDescGZIP(), []int{2}
}

func (x *PeerInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PeerInfo) GetRaftAddress() string {
	if x != nil {
		return x.RaftAddress
	}
	return ""
}

func (x *PeerInfo) GetServiceAddress() string {
	if x != nil {
		return x.ServiceAddress
	}
	return ""
}

type JoinAsLearnerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                        // Numeric ID for the new learner node
	RaftAddress    string                 `protobuf:"bytes,2,opt,name=raft_address,json=raftAddress,proto3" json:"raft_address,omitempty"`          // Raft transport address of the learner
	ServiceAddress string                 `protobuf:"bytes,3,opt,name=service_address,json=serviceAddress,proto3" json:"service_address,omitempty"` // Service API address of the learner
	InstanceId     []byte                 `protobuf:"bytes,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`             // 16-byte UUID identifying this peer's WAL/PVC incarnation (EN-1045); required
	// fsm_determinism_enabled is the joining node's local fsm-determinism-enabled
	// flag. The leader refuses the join when it disagrees with its own flag: the
	// cross-node FSM digest and the deterministic attribute encoding are only
	// coherent when every peer runs the same setting, and a divergent peer would
	// otherwise be admitted and then report perpetual (false) digest divergence.
	// Local persisted-config validation only catches a flag flip across restarts
	// of the SAME node; this catches a mismatched peer at join time.
	FsmDeterminismEnabled bool `protobuf:"varint,5,opt,name=fsm_determinism_enabled,json=fsmDeterminismEnabled,proto3" json:"fsm_determinism_enabled,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *JoinAsLearnerRequest) Reset() {
	*x = JoinAsLearnerRequest{}
	mi := &file_cluster_bootstrap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinAsLearnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinAsLearnerRequest) ProtoMessage() {}

func (x *JoinAsLearnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_bootstrap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinAsLearnerRequest.ProtoReflect.Descriptor instead.
func (*JoinAsLearnerRequest) Descriptor() ([]byte, []int) {
	return file_cluster_bootstrap_proto_rawDescGZIP(), []int{3}
}

func (x *JoinAsLearnerRequest) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *JoinAsLearnerRequest) GetRaftAddress() string {
	if x != nil {
		return x.RaftAddress
	}
	return ""
}

func (x *JoinAsLearnerRequest) GetServiceAddress() string {
	if x != nil {
		return x.ServiceAddress
	}
	return ""
}

func (x *JoinAsLearnerRequest) GetInstanceId() []byte {
	if x != nil {
		return x.InstanceId
	}
	return nil
}

func (x *JoinAsLearnerRequest) GetFsmDeterminismEnabled() bool {
	if x != nil {
		return x.FsmDeterminismEnabled
	}
	return false
}

type JoinAsLearnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinAsLearnerResponse) Reset() {
	*x = JoinAsLearnerResponse{}
	mi := &file_cluster_bootstrap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinAsLearnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinAsLearnerResponse) ProtoMessage() {}

func (x *JoinAsLearnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_bootstrap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinAsLearnerResponse.ProtoReflect.Descriptor instead.
func (*JoinAsLearnerResponse) Descriptor() ([]byte, []int) {
	return file_cluster_bootstrap_proto_rawDescGZIP(), []int{4}
}

var File_cluster_bootstrap_proto protoreflect.FileDescriptor

const file_cluster_bootstrap_proto_rawDesc = "" +
	"\n" +
	"\x17cluster_bootstrap.proto\x12\x11cluster_bootstrap\"\x11\n" +
	"\x0fGetPeersRequest\"E\n" +
	"\x10GetPeersResponse\x121\n" +
	"\x05peers\x18\x01 \x03(\v2\x1b.cluster_bootstrap.PeerInfoR\x05peers\"f\n" +
	"\bPeerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\fraft_address\x18\x02 \x01(\tR\vraftAddress\x12'\n" +
	"\x0fservice_address\x18\x03 \x01(\tR\x0eserviceAddress\"\xd4\x01\n" +
	"\x14JoinAsLearnerRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12!\n" +
	"\fraft_address\x18\x02 \x01(\tR\vraftAddress\x12'\n" +
	"\x0fservice_address\x18\x03 \x01(\tR\x0eserviceAddress\x12\x1f\n" +
	"\vinstance_id\x18\x04 \x01(\fR\n" +
	"instanceId\x126\n" +
	"\x17fsm_determinism_enabled\x18\x05 \x01(\bR\x15fsmDeterminismEnabled\"\x17\n" +
	"\x15JoinAsLearnerResponse2\xd2\x01\n" +
	"\x17ClusterBootstrapService\x12S\n" +
	"\bGetPeers\x12\".cluster_bootstrap.GetPeersRequest\x1a#.cluster_bootstrap.GetPeersResponse\x12b\n" +
	"\rJoinAsLearner\x12'.cluster_bootstrap.JoinAsLearnerRequest\x1a(.cluster_bootstrap.JoinAsLearnerResponseBCZAgithub.com/formancehq/ledger/v3/internal/proto/clusterbootstrappbb\x06proto3"

var (
	file_cluster_bootstrap_proto_rawDescOnce sync.Once
	file_cluster_bootstrap_proto_rawDescData []byte
)

func file_cluster_bootstrap_proto_rawDescGZIP() []byte {
	file_cluster_bootstrap_proto_rawDescOnce.Do(func() {
		file_cluster_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_bootstrap_proto_rawDesc), len(file_cluster_bootstrap_proto_rawDesc)))
	})
	return file_cluster_bootstrap_proto_rawDescData
}

var file_cluster_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cluster_bootstrap_proto_goTypes = []any{
	(*GetPeersRequest)(nil),       // 0: cluster_bootstrap.GetPeersRequest
	(*GetPeersResponse)(nil),      // 1: cluster_bootstrap.GetPeersResponse
	(*PeerInfo)(nil),              // 2: cluster_bootstrap.PeerInfo
	(*JoinAsLearnerRequest)(nil),  // 3: cluster_bootstrap.JoinAsLearnerRequest
	(*JoinAsLearnerResponse)(nil), // 4: cluster_bootstrap.JoinAsLearnerResponse
}
var file_cluster_bootstrap_proto_depIdxs = []int32{
	2, // 0: cluster_bootstrap.GetPeersResponse.peers:type_name -> cluster_bootstrap.PeerInfo
	0, // 1: cluster_bootstrap.ClusterBootstrapService.GetPeers:input_type -> cluster_bootstrap.GetPeersRequest
	3, // 2: cluster_bootstrap.ClusterBootstrapService.JoinAsLearner:input_type -> cluster_bootstrap.JoinAsLearnerRequest
	1, // 3: cluster_bootstrap.ClusterBootstrapService.GetPeers:output_type -> cluster_bootstrap.GetPeersResponse
	4, // 4: cluster_bootstrap.ClusterBootstrapService.JoinAsLearner:output_type -> cluster_bootstrap.JoinAsLearnerResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cluster_bootstrap_proto_init() }
func file_cluster_bootstrap_proto_init() {
	if File_cluster_bootstrap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_bootstrap_proto_rawDesc), len(file_cluster_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cluster_bootstrap_proto_goTypes,
		DependencyIndexes: file_cluster_bootstrap_proto_depIdxs,
		MessageInfos:      file_cluster_bootstrap_proto_msgTypes,
	}.Build()
	File_cluster_bootstrap_proto = out.File
	file_cluster_bootstrap_proto_goTypes = nil
	file_cluster_bootstrap_proto_depIdxs = nil
}
