// Code generated by protoc-gen-dethash. DO NOT EDIT.
// source: cluster_bootstrap.proto

package clusterbootstrappb

func (m *GetPeersRequest) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *GetPeersResponse) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *PeerInfo) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *JoinAsLearnerRequest) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *JoinAsLearnerResponse) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}
