// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/formancehq/ledger/internal/controller/system (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=internal/controller/system/mocks_store_test.go -package=system github.com/formancehq/ledger/internal/controller/system Store
//

// Package system is a generated GoMock package.
package system

import (
	context "context"
	reflect "reflect"

	bunpaginate "github.com/formancehq/go-libs/v3/bun/bunpaginate"
	metadata "github.com/formancehq/go-libs/v3/metadata"
	ledger "github.com/formancehq/ledger/internal"
	ledger0 "github.com/formancehq/ledger/internal/controller/ledger"
	common "github.com/formancehq/ledger/internal/storage/common"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateLedger mocks base method.
func (m *MockStore) CreateLedger(arg0 context.Context, arg1 *ledger.Ledger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLedger", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLedger indicates an expected call of CreateLedger.
func (mr *MockStoreMockRecorder) CreateLedger(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLedger", reflect.TypeOf((*MockStore)(nil).CreateLedger), arg0, arg1)
}

// DeleteLedgerMetadata mocks base method.
func (m *MockStore) DeleteLedgerMetadata(ctx context.Context, param, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLedgerMetadata", ctx, param, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLedgerMetadata indicates an expected call of DeleteLedgerMetadata.
func (mr *MockStoreMockRecorder) DeleteLedgerMetadata(ctx, param, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLedgerMetadata", reflect.TypeOf((*MockStore)(nil).DeleteLedgerMetadata), ctx, param, key)
}

// GetLedger mocks base method.
func (m *MockStore) GetLedger(ctx context.Context, name string) (*ledger.Ledger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLedger", ctx, name)
	ret0, _ := ret[0].(*ledger.Ledger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedger indicates an expected call of GetLedger.
func (mr *MockStoreMockRecorder) GetLedger(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedger", reflect.TypeOf((*MockStore)(nil).GetLedger), ctx, name)
}

// ListBucketsWithStatus mocks base method.
func (m *MockStore) ListBucketsWithStatus(ctx context.Context, query common.ColumnPaginatedQuery[any]) (*bunpaginate.Cursor[BucketWithStatus], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBucketsWithStatus", ctx, query)
	ret0, _ := ret[0].(*bunpaginate.Cursor[BucketWithStatus])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBucketsWithStatus indicates an expected call of ListBucketsWithStatus.
func (mr *MockStoreMockRecorder) ListBucketsWithStatus(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBucketsWithStatus", reflect.TypeOf((*MockStore)(nil).ListBucketsWithStatus), ctx, query)
}

// ListLedgers mocks base method.
func (m *MockStore) ListLedgers(ctx context.Context, query common.ColumnPaginatedQuery[any]) (*bunpaginate.Cursor[ledger.Ledger], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLedgers", ctx, query)
	ret0, _ := ret[0].(*bunpaginate.Cursor[ledger.Ledger])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLedgers indicates an expected call of ListLedgers.
func (mr *MockStoreMockRecorder) ListLedgers(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLedgers", reflect.TypeOf((*MockStore)(nil).ListLedgers), ctx, query)
}

// MarkBucketAsDeleted mocks base method.
func (m *MockStore) MarkBucketAsDeleted(ctx context.Context, bucketName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkBucketAsDeleted", ctx, bucketName)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkBucketAsDeleted indicates an expected call of MarkBucketAsDeleted.
func (mr *MockStoreMockRecorder) MarkBucketAsDeleted(ctx, bucketName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkBucketAsDeleted", reflect.TypeOf((*MockStore)(nil).MarkBucketAsDeleted), ctx, bucketName)
}

// OpenLedger mocks base method.
func (m *MockStore) OpenLedger(arg0 context.Context, arg1 string) (ledger0.Store, *ledger.Ledger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenLedger", arg0, arg1)
	ret0, _ := ret[0].(ledger0.Store)
	ret1, _ := ret[1].(*ledger.Ledger)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// OpenLedger indicates an expected call of OpenLedger.
func (mr *MockStoreMockRecorder) OpenLedger(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenLedger", reflect.TypeOf((*MockStore)(nil).OpenLedger), arg0, arg1)
}

// RestoreBucket mocks base method.
func (m *MockStore) RestoreBucket(ctx context.Context, bucketName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreBucket", ctx, bucketName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreBucket indicates an expected call of RestoreBucket.
func (mr *MockStoreMockRecorder) RestoreBucket(ctx, bucketName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreBucket", reflect.TypeOf((*MockStore)(nil).RestoreBucket), ctx, bucketName)
}

// UpdateLedgerMetadata mocks base method.
func (m_2 *MockStore) UpdateLedgerMetadata(ctx context.Context, name string, m metadata.Metadata) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "UpdateLedgerMetadata", ctx, name, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLedgerMetadata indicates an expected call of UpdateLedgerMetadata.
func (mr *MockStoreMockRecorder) UpdateLedgerMetadata(ctx, name, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLedgerMetadata", reflect.TypeOf((*MockStore)(nil).UpdateLedgerMetadata), ctx, name, m)
}
