---
volumes:
  postgres:
services:
  postgres:
    extends:
      file: ../../docker-compose.yml
      service: postgres
  ledger:
    extends:
      file: ../../docker-compose.yml
      service: ledger
    depends_on:
      - postgres
    image: golang:1.19-alpine
    entrypoint: go run main.go serve
    volumes:
      - ../..:/src
    ports:
    - 3068:3068
    working_dir: /src
    environment:
      CGO_ENABLED: 0
      DEBUG: "true"
      AUTH_BASIC_ENABLED: "true"
      AUTH_BASIC_CREDENTIALS: "user:password"
