// Code generated by protoc-gen-dethash. DO NOT EDIT.
// source: common.proto

package commonpb

import (
	protohelpers "github.com/planetscale/vtprotobuf/protohelpers"
	maps "maps"
	slices "slices"
)

func (m *Timestamp) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *Metadata) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *NullValue) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *MetadataValue) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *MetadataSet) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *ParameterValue) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *Uint256) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *Posting) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *Transaction) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *Script) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	sz := m.SizeVT()
	buf := make([]byte, sz)
	n, _ := m.MarshalToSizedBufferDeterministicVT(buf)
	return append(dAtA, buf[sz-n:]...)
}

func (m *Script) MarshalToSizedBufferDeterministicVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.ContentHash) > 0 {
		i -= len(m.ContentHash)
		copy(dAtA[i:], m.ContentHash)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.ContentHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Vars) > 0 {
		for _, k := range slices.Sorted(maps.Keys(m.Vars)) {
			v := m.Vars[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = protohelpers.EncodeVarint(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Plain) > 0 {
		i -= len(m.Plain)
		copy(dAtA[i:], m.Plain)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Plain)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Volumes) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *VolumesWithBalance) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *VolumesByAssets) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	sz := m.SizeVT()
	buf := make([]byte, sz)
	n, _ := m.MarshalToSizedBufferDeterministicVT(buf)
	return append(dAtA, buf[sz-n:]...)
}

func (m *VolumesByAssets) MarshalToSizedBufferDeterministicVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.Volumes) > 0 {
		for _, k := range slices.Sorted(maps.Keys(m.Volumes)) {
			v := m.Volumes[k]
			baseI := i
			size, _ := v.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = protohelpers.EncodeVarint(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *PostCommitVolumes) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	sz := m.SizeVT()
	buf := make([]byte, sz)
	n, _ := m.MarshalToSizedBufferDeterministicVT(buf)
	return append(dAtA, buf[sz-n:]...)
}

func (m *PostCommitVolumes) MarshalToSizedBufferDeterministicVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.VolumesByAccount) > 0 {
		for _, k := range slices.Sorted(maps.Keys(m.VolumesByAccount)) {
			v := m.VolumesByAccount[k]
			baseI := i
			size, _ := v.MarshalToSizedBufferDeterministicVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = protohelpers.EncodeVarint(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Account) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	sz := m.SizeVT()
	buf := make([]byte, sz)
	n, _ := m.MarshalToSizedBufferDeterministicVT(buf)
	return append(dAtA, buf[sz-n:]...)
}

func (m *Account) MarshalToSizedBufferDeterministicVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.Volumes) > 0 {
		for _, k := range slices.Sorted(maps.Keys(m.Volumes)) {
			v := m.Volumes[k]
			baseI := i
			size, _ := v.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = protohelpers.EncodeVarint(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x32
		}
	}
	if m.UpdatedAt != nil {
		size, _ := m.UpdatedAt.MarshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x2a
	}
	if m.InsertionDate != nil {
		size, _ := m.InsertionDate.MarshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x22
	}
	if m.FirstUsage != nil {
		size, _ := m.FirstUsage.MarshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if m.Metadata != nil {
		size, _ := m.Metadata.MarshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TargetAccount) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *TargetTransaction) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *Target) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *MetadataFieldSchema) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *MetadataSchema) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	sz := m.SizeVT()
	buf := make([]byte, sz)
	n, _ := m.MarshalToSizedBufferDeterministicVT(buf)
	return append(dAtA, buf[sz-n:]...)
}

func (m *MetadataSchema) MarshalToSizedBufferDeterministicVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.TransactionFields) > 0 {
		for _, k := range slices.Sorted(maps.Keys(m.TransactionFields)) {
			v := m.TransactionFields[k]
			baseI := i
			size, _ := v.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = protohelpers.EncodeVarint(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.AccountFields) > 0 {
		for _, k := range slices.Sorted(maps.Keys(m.AccountFields)) {
			v := m.AccountFields[k]
			baseI := i
			size, _ := v.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = protohelpers.EncodeVarint(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *SetMetadataFieldTypeCommand) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *TransactionIndex) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *AccountIndex) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *BuiltinIndexConfig) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *LogBuiltinIndexConfig) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *Idempotency) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *IdempotencyEntry) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *Log) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	sz := m.SizeVT()
	buf := make([]byte, sz)
	n, _ := m.MarshalToSizedBufferDeterministicVT(buf)
	return append(dAtA, buf[sz-n:]...)
}

func (m *Log) MarshalToSizedBufferDeterministicVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.HashVersion != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.HashVersion))
		i--
		dAtA[i] = 0x40
	}
	if m.ResponseSignature != nil {
		size, _ := m.ResponseSignature.MarshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Receipt) > 0 {
		i -= len(m.Receipt)
		copy(dAtA[i:], m.Receipt)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Receipt)))
		i--
		dAtA[i] = 0x32
	}
	if m.Signature != nil {
		size, _ := m.Signature.MarshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x22
	}
	if m.Idempotency != nil {
		size, _ := m.Idempotency.MarshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if m.Payload != nil {
		size, _ := m.Payload.MarshalToSizedBufferDeterministicVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if m.Sequence != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *LogPayload) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	sz := m.SizeVT()
	buf := make([]byte, sz)
	n, _ := m.MarshalToSizedBufferDeterministicVT(buf)
	return append(dAtA, buf[sz-n:]...)
}

func (m *LogPayload) MarshalToSizedBufferDeterministicVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	switch v := m.Type.(type) {
	case *LogPayload_CreateLedger:
		if v.CreateLedger != nil {
			size, _ := v.CreateLedger.MarshalToSizedBufferDeterministicVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0xa
		}
	case *LogPayload_DeleteLedger:
		if v.DeleteLedger != nil {
			size, _ := v.DeleteLedger.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x12
		}
	case *LogPayload_Apply:
		if v.Apply != nil {
			size, _ := v.Apply.MarshalToSizedBufferDeterministicVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x1a
		}
	case *LogPayload_RegisterSigningKey:
		if v.RegisterSigningKey != nil {
			size, _ := v.RegisterSigningKey.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x22
		}
	case *LogPayload_RevokeSigningKey:
		if v.RevokeSigningKey != nil {
			size, _ := v.RevokeSigningKey.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x2a
		}
	case *LogPayload_SetSigningConfig:
		if v.SetSigningConfig != nil {
			size, _ := v.SetSigningConfig.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x32
		}
	case *LogPayload_AddedEventsSink:
		if v.AddedEventsSink != nil {
			size, _ := v.AddedEventsSink.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x3a
		}
	case *LogPayload_RemovedEventsSink:
		if v.RemovedEventsSink != nil {
			size, _ := v.RemovedEventsSink.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x42
		}
	case *LogPayload_ClosePeriod:
		if v.ClosePeriod != nil {
			size, _ := v.ClosePeriod.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x4a
		}
	case *LogPayload_SealPeriod:
		if v.SealPeriod != nil {
			size, _ := v.SealPeriod.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x52
		}
	case *LogPayload_ArchivePeriod:
		if v.ArchivePeriod != nil {
			size, _ := v.ArchivePeriod.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x5a
		}
	case *LogPayload_ConfirmArchivePeriod:
		if v.ConfirmArchivePeriod != nil {
			size, _ := v.ConfirmArchivePeriod.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x62
		}
	case *LogPayload_SetMaintenanceMode:
		if v.SetMaintenanceMode != nil {
			size, _ := v.SetMaintenanceMode.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x6a
		}
	case *LogPayload_SetPeriodSchedule:
		if v.SetPeriodSchedule != nil {
			size, _ := v.SetPeriodSchedule.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x72
		}
	case *LogPayload_DeletePeriodSchedule:
		if v.DeletePeriodSchedule != nil {
			size, _ := v.DeletePeriodSchedule.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x7a
		}
	case *LogPayload_PromoteLedger:
		if v.PromoteLedger != nil {
			size, _ := v.PromoteLedger.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x8a
		}
	case *LogPayload_CreatedPreparedQuery:
		if v.CreatedPreparedQuery != nil {
			size, _ := v.CreatedPreparedQuery.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x92
		}
	case *LogPayload_UpdatedPreparedQuery:
		if v.UpdatedPreparedQuery != nil {
			size, _ := v.UpdatedPreparedQuery.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x9a
		}
	case *LogPayload_DeletedPreparedQuery:
		if v.DeletedPreparedQuery != nil {
			size, _ := v.DeletedPreparedQuery.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xa2
		}
	case *LogPayload_SavedNumscript:
		if v.SavedNumscript != nil {
			size, _ := v.SavedNumscript.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xaa
		}
	case *LogPayload_DeletedNumscript:
		if v.DeletedNumscript != nil {
			size, _ := v.DeletedNumscript.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xb2
		}
	case *LogPayload_CreatedQueryCheckpoint:
		if v.CreatedQueryCheckpoint != nil {
			size, _ := v.CreatedQueryCheckpoint.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xba
		}
	case *LogPayload_DeletedQueryCheckpoint:
		if v.DeletedQueryCheckpoint != nil {
			size, _ := v.DeletedQueryCheckpoint.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xc2
		}
	case *LogPayload_SetQueryCheckpointSchedule:
		if v.SetQueryCheckpointSchedule != nil {
			size, _ := v.SetQueryCheckpointSchedule.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xca
		}
	case *LogPayload_DeleteQueryCheckpointSchedule:
		if v.DeleteQueryCheckpointSchedule != nil {
			size, _ := v.DeleteQueryCheckpointSchedule.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xd2
		}
	}
	return len(dAtA) - i, nil
}

func (m *PromoteLedgerLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *RegisterSigningKeyLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *RevokeSigningKeyLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *SigningKey) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *SetSigningConfigLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *AddedEventsSinkLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *RemovedEventsSinkLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *SetMaintenanceModeLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *ClusterConfig) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *PersistedClusterState) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *SetPeriodScheduleLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *DeletePeriodScheduleLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *CreatedPreparedQueryLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *UpdatedPreparedQueryLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *DeletedPreparedQueryLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *NumscriptInfo) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *SavedNumscriptLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *DeletedNumscriptLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *SetQueryCheckpointScheduleLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *DeleteQueryCheckpointScheduleLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *CreatedQueryCheckpointLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *DeletedQueryCheckpointLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *SinkConfig) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *SinkStatus) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *SinkError) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *NatsSinkConfig) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *ClickHouseSinkConfig) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *KafkaSinkConfig) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *HttpSinkConfig) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *DatabricksSinkConfig) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *CreateLedgerLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	sz := m.SizeVT()
	buf := make([]byte, sz)
	n, _ := m.MarshalToSizedBufferDeterministicVT(buf)
	return append(dAtA, buf[sz-n:]...)
}

func (m *CreateLedgerLog) MarshalToSizedBufferDeterministicVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.DefaultEnforcementMode != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.DefaultEnforcementMode))
		i--
		dAtA[i] = 0x38
	}
	if len(m.AccountTypes) > 0 {
		for _, k := range slices.Sorted(maps.Keys(m.AccountTypes)) {
			v := m.AccountTypes[k]
			baseI := i
			size, _ := v.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = protohelpers.EncodeVarint(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x32
		}
	}
	if m.MirrorSource != nil {
		size, _ := m.MirrorSource.MarshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x2a
	}
	if m.Mode != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.Mode))
		i--
		dAtA[i] = 0x20
	}
	if m.MetadataSchema != nil {
		size, _ := m.MetadataSchema.MarshalToSizedBufferDeterministicVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if m.CreatedAt != nil {
		size, _ := m.CreatedAt.MarshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DeleteLedgerLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *ApplyLedgerLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	sz := m.SizeVT()
	buf := make([]byte, sz)
	n, _ := m.MarshalToSizedBufferDeterministicVT(buf)
	return append(dAtA, buf[sz-n:]...)
}

func (m *ApplyLedgerLog) MarshalToSizedBufferDeterministicVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.Log != nil {
		size, _ := m.Log.MarshalToSizedBufferDeterministicVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if len(m.LedgerName) > 0 {
		i -= len(m.LedgerName)
		copy(dAtA[i:], m.LedgerName)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.LedgerName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LedgerLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	sz := m.SizeVT()
	buf := make([]byte, sz)
	n, _ := m.MarshalToSizedBufferDeterministicVT(buf)
	return append(dAtA, buf[sz-n:]...)
}

func (m *LedgerLog) MarshalToSizedBufferDeterministicVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.Id != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x18
	}
	if m.Date != nil {
		size, _ := m.Date.MarshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if m.Data != nil {
		size, _ := m.Data.MarshalToSizedBufferDeterministicVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LedgerLogPayload) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	sz := m.SizeVT()
	buf := make([]byte, sz)
	n, _ := m.MarshalToSizedBufferDeterministicVT(buf)
	return append(dAtA, buf[sz-n:]...)
}

func (m *LedgerLogPayload) MarshalToSizedBufferDeterministicVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	switch v := m.Payload.(type) {
	case *LedgerLogPayload_CreatedTransaction:
		if v.CreatedTransaction != nil {
			size, _ := v.CreatedTransaction.MarshalToSizedBufferDeterministicVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0xa
		}
	case *LedgerLogPayload_RevertedTransaction:
		if v.RevertedTransaction != nil {
			size, _ := v.RevertedTransaction.MarshalToSizedBufferDeterministicVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x12
		}
	case *LedgerLogPayload_SavedMetadata:
		if v.SavedMetadata != nil {
			size, _ := v.SavedMetadata.MarshalToSizedBufferDeterministicVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x1a
		}
	case *LedgerLogPayload_DeletedMetadata:
		if v.DeletedMetadata != nil {
			size, _ := v.DeletedMetadata.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x22
		}
	case *LedgerLogPayload_SetMetadataFieldType:
		if v.SetMetadataFieldType != nil {
			size, _ := v.SetMetadataFieldType.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x2a
		}
	case *LedgerLogPayload_RemovedMetadataFieldType:
		if v.RemovedMetadataFieldType != nil {
			size, _ := v.RemovedMetadataFieldType.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x32
		}
	case *LedgerLogPayload_ConvertMetadataBatch:
		if v.ConvertMetadataBatch != nil {
			size, _ := v.ConvertMetadataBatch.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x3a
		}
	case *LedgerLogPayload_MetadataConversionComplete:
		if v.MetadataConversionComplete != nil {
			size, _ := v.MetadataConversionComplete.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x42
		}
	case *LedgerLogPayload_FillGap:
		if v.FillGap != nil {
			size, _ := v.FillGap.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x4a
		}
	case *LedgerLogPayload_CreateIndex:
		if v.CreateIndex != nil {
			size, _ := v.CreateIndex.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x52
		}
	case *LedgerLogPayload_DropIndex:
		if v.DropIndex != nil {
			size, _ := v.DropIndex.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x5a
		}
	case *LedgerLogPayload_IndexReady:
		if v.IndexReady != nil {
			size, _ := v.IndexReady.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x62
		}
	case *LedgerLogPayload_AddedAccountType:
		if v.AddedAccountType != nil {
			size, _ := v.AddedAccountType.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x6a
		}
	case *LedgerLogPayload_RemovedAccountType:
		if v.RemovedAccountType != nil {
			size, _ := v.RemovedAccountType.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x72
		}
	case *LedgerLogPayload_UpdatedDefaultEnforcementMode:
		if v.UpdatedDefaultEnforcementMode != nil {
			size, _ := v.UpdatedDefaultEnforcementMode.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x7a
		}
	case *LedgerLogPayload_StartedAccountMigration:
		if v.StartedAccountMigration != nil {
			size, _ := v.StartedAccountMigration.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x82
		}
	case *LedgerLogPayload_AccountMigrationBatch:
		if v.AccountMigrationBatch != nil {
			size, _ := v.AccountMigrationBatch.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x8a
		}
	case *LedgerLogPayload_CompletedAccountMigration:
		if v.CompletedAccountMigration != nil {
			size, _ := v.CompletedAccountMigration.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x92
		}
	}
	return len(dAtA) - i, nil
}

func (m *CreateIndexLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *DropIndexLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *IndexReadyLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *FillGapLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *ConvertMetadataBatchLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *ConvertMetadataBatchLogEntry) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *MetadataConversionCompleteLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *CreatedTransaction) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	sz := m.SizeVT()
	buf := make([]byte, sz)
	n, _ := m.MarshalToSizedBufferDeterministicVT(buf)
	return append(dAtA, buf[sz-n:]...)
}

func (m *CreatedTransaction) MarshalToSizedBufferDeterministicVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.PreviousAccountMetadata) > 0 {
		for _, k := range slices.Sorted(maps.Keys(m.PreviousAccountMetadata)) {
			v := m.PreviousAccountMetadata[k]
			baseI := i
			size, _ := v.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = protohelpers.EncodeVarint(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.PostCommitVolumes != nil {
		size, _ := m.PostCommitVolumes.MarshalToSizedBufferDeterministicVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x22
	}
	if m.PeriodId != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.PeriodId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.AccountMetadata) > 0 {
		for _, k := range slices.Sorted(maps.Keys(m.AccountMetadata)) {
			v := m.AccountMetadata[k]
			baseI := i
			size, _ := v.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = protohelpers.EncodeVarint(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Transaction != nil {
		size, _ := m.Transaction.MarshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RevertedTransaction) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	sz := m.SizeVT()
	buf := make([]byte, sz)
	n, _ := m.MarshalToSizedBufferDeterministicVT(buf)
	return append(dAtA, buf[sz-n:]...)
}

func (m *RevertedTransaction) MarshalToSizedBufferDeterministicVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.PostCommitVolumes != nil {
		size, _ := m.PostCommitVolumes.MarshalToSizedBufferDeterministicVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if m.RevertTransaction != nil {
		size, _ := m.RevertTransaction.MarshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if m.RevertedTransactionId != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.RevertedTransactionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SavedMetadata) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	sz := m.SizeVT()
	buf := make([]byte, sz)
	n, _ := m.MarshalToSizedBufferDeterministicVT(buf)
	return append(dAtA, buf[sz-n:]...)
}

func (m *SavedMetadata) MarshalToSizedBufferDeterministicVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.PreviousValues) > 0 {
		for _, k := range slices.Sorted(maps.Keys(m.PreviousValues)) {
			v := m.PreviousValues[k]
			baseI := i
			size, _ := v.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = protohelpers.EncodeVarint(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Metadata != nil {
		size, _ := m.Metadata.MarshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if m.Target != nil {
		size, _ := m.Target.MarshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DeletedMetadata) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *SetMetadataFieldTypeLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *RemovedMetadataFieldTypeLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *Period) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *ClosePeriodLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *SealPeriodLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *ArchivePeriodLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *ConfirmArchivePeriodLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *MirrorSourceConfig) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *HttpMirrorSourceConfig) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *OAuth2ClientCredentials) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *PostgresMirrorSourceConfig) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *MirrorSyncError) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *MirrorSyncProgress) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *LedgerInfo) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	sz := m.SizeVT()
	buf := make([]byte, sz)
	n, _ := m.MarshalToSizedBufferDeterministicVT(buf)
	return append(dAtA, buf[sz-n:]...)
}

func (m *LedgerInfo) MarshalToSizedBufferDeterministicVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.DefaultEnforcementMode != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.DefaultEnforcementMode))
		i--
		dAtA[i] = 0x58
	}
	if len(m.AccountTypes) > 0 {
		for _, k := range slices.Sorted(maps.Keys(m.AccountTypes)) {
			v := m.AccountTypes[k]
			baseI := i
			size, _ := v.MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = protohelpers.EncodeVarint(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x52
		}
	}
	if m.LogBuiltinIndexes != nil {
		size, _ := m.LogBuiltinIndexes.MarshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x4a
	}
	if m.BuiltinIndexes != nil {
		size, _ := m.BuiltinIndexes.MarshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x42
	}
	if m.MirrorSyncProgress != nil {
		size, _ := m.MirrorSyncProgress.MarshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x3a
	}
	if m.MirrorSource != nil {
		size, _ := m.MirrorSource.MarshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x32
	}
	if m.Mode != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.Mode))
		i--
		dAtA[i] = 0x28
	}
	if m.MetadataSchema != nil {
		size, _ := m.MetadataSchema.MarshalToSizedBufferDeterministicVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x22
	}
	if m.DeletedAt != nil {
		size, _ := m.DeletedAt.MarshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if m.CreatedAt != nil {
		size, _ := m.CreatedAt.MarshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SaveMetadataCommand) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *DeleteMetadataCommand) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *TransactionState) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *IdempotencyKeyValue) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *TransactionReferenceValue) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *NumscriptVersionValue) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *AccountType) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *AddedAccountTypeLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *RemovedAccountTypeLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *UpdatedDefaultEnforcementModeLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *AccountTypeMigration) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *StartedAccountMigrationLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *AccountMigrationBatchLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *AccountMigrationEntryLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *CompletedAccountMigrationLog) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *QueryFilter) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *ReferenceCondition) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *LedgerCondition) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *LogIdCondition) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *BuiltinUintCondition) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *LogBuiltinUintCondition) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *AndFilter) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *OrFilter) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *NotFilter) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *FieldRef) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *FieldCondition) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *StringCondition) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *IntCondition) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *UintCondition) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *BoolCondition) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *ExistsCondition) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *AddressMatch) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *PreparedQuery) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *AggregatedVolume) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *AggregateResult) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *GroupedAggregateResult) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}

func (m *PreparedQueryCursor) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	sz := m.SizeVT()
	buf := make([]byte, sz)
	n, _ := m.MarshalToSizedBufferDeterministicVT(buf)
	return append(dAtA, buf[sz-n:]...)
}

func (m *PreparedQueryCursor) MarshalToSizedBufferDeterministicVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if len(m.TransactionData) > 0 {
		for iNdEx := len(m.TransactionData) - 1; iNdEx >= 0; iNdEx-- {
			size, _ := m.TransactionData[iNdEx].MarshalToSizedBufferVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.AccountData) > 0 {
		for iNdEx := len(m.AccountData) - 1; iNdEx >= 0; iNdEx-- {
			size, _ := m.AccountData[iNdEx].MarshalToSizedBufferDeterministicVT(dAtA[:i])
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Next) > 0 {
		i -= len(m.Next)
		copy(dAtA[i:], m.Next)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Next)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Previous) > 0 {
		i -= len(m.Previous)
		copy(dAtA[i:], m.Previous)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Previous)))
		i--
		dAtA[i] = 0x1a
	}
	if m.HasMore {
		i--
		if m.HasMore {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.PageSize != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.PageSize))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *LedgerStats) MarshalDeterministicVT(dAtA []byte) []byte {
	if m == nil {
		return dAtA
	}
	b, err := m.MarshalVT()
	if err != nil {
		panic("MarshalDeterministicVT: " + err.Error())
	}
	return append(dAtA, b...)
}
