openapi: 3.1.0
info:
  title: Formance Stack API
  description: |
    Open, modular foundation for unique payments flows

    # Introduction
    This API is documented in **OpenAPI format**.

    # Authentication
    Formance Stack offers one forms of authentication:
      - OAuth2
    OAuth2 - an open protocol to allow secure authorization in a simple
    and standard method from web, mobile and desktop applications.
    <SecurityDefinitions />
  contact:
    name: Formance
    url: https://www.formance.com
    email: support@formance.com
  x-logo:
    url: https://avatars.githubusercontent.com/u/84325077?s=200&v=4
    altText: Formance
  version: "SDK_VERSION"

servers:
  - url: http://localhost
    description: local server
  - url: https://{organization}.sandbox.formance.cloud
    description: sandbox server
    variables:
      organization:
        description: The organization on which the ledger is located
        default: ""

security:
  - Authorization: []

components:
  securitySchemes:
    Authorization:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}

x-tagGroups:
  - name: Auth
    tags:
      - Clients
      - Scopes
      - Users
  - name: Ledger
    tags:
      - Server
      - Accounts
      - Mapping
      - Script
      - Stats
      - Transactions
      - Balances
  - name: Payments
    tags:
      - Payments
  - name: Search
    tags:
      - Search
  - name: Webhooks
    tags:
      - Webhooks
  