{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "benchmark-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "benchmark-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups:
      - k6.io
    resources:
      - testruns
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
      - update
      - patch
      - delete
{{- end }}
