{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "benchmark-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "benchmark-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benchmark.formance.com
  resources:
  - benchmarks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benchmark.formance.com
  resources:
  - benchmarks/finalizers
  verbs:
  - update
- apiGroups:
  - benchmark.formance.com
  resources:
  - benchmarks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k6.io
  resources:
  - testruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# -- Leader election
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# -- Event recording
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
{{- with .Values.rbac.additionalRules }}
{{ toYaml . | indent 0 }}
{{- end }}
{{- end }}
