apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "benchmark-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "benchmark-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "benchmark-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "benchmark-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "benchmark-operator.serviceAccountName" . }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WATCH_NAMESPACE
              value: "{{ .Values.watchNamespace }}"
{{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
{{- end }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
{{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
{{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
{{- toYaml .Values.affinity | nindent 8 }}
