// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/ledger/pkg/client/internal/utils"
	"github.com/formancehq/ledger/pkg/client/models/components"
	"math/big"
)

type V2AddMetadataOnTransactionRequest struct {
	// Name of the ledger.
	Ledger string `pathParam:"style=simple,explode=false,name=ledger"`
	// Transaction ID.
	ID *big.Int `pathParam:"style=simple,explode=false,name=id"`
	// Set the dryRun mode. Dry run mode doesn't add the logs to the database or publish a message to the message broker.
	DryRun *bool `queryParam:"style=form,explode=true,name=dryRun"`
	// Use an idempotency key
	IdempotencyKey *string `header:"style=simple,explode=false,name=Idempotency-Key"`
	// Schema version to use for validation
	SchemaVersion *string `queryParam:"style=form,explode=true,name=schemaVersion"`
	// metadata
	RequestBody map[string]string `request:"mediaType=application/json"`
}

func (v V2AddMetadataOnTransactionRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V2AddMetadataOnTransactionRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *V2AddMetadataOnTransactionRequest) GetLedger() string {
	if v == nil {
		return ""
	}
	return v.Ledger
}

func (v *V2AddMetadataOnTransactionRequest) GetID() *big.Int {
	if v == nil {
		return big.NewInt(0)
	}
	return v.ID
}

func (v *V2AddMetadataOnTransactionRequest) GetDryRun() *bool {
	if v == nil {
		return nil
	}
	return v.DryRun
}

func (v *V2AddMetadataOnTransactionRequest) GetIdempotencyKey() *string {
	if v == nil {
		return nil
	}
	return v.IdempotencyKey
}

func (v *V2AddMetadataOnTransactionRequest) GetSchemaVersion() *string {
	if v == nil {
		return nil
	}
	return v.SchemaVersion
}

func (v *V2AddMetadataOnTransactionRequest) GetRequestBody() map[string]string {
	if v == nil {
		return map[string]string{}
	}
	return v.RequestBody
}

// #region class-body-v2addmetadataontransactionrequest
// #endregion class-body-v2addmetadataontransactionrequest

type V2AddMetadataOnTransactionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Headers  map[string][]string
}

func (v *V2AddMetadataOnTransactionResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V2AddMetadataOnTransactionResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}

// #region class-body-v2addmetadataontransactionresponse
// #endregion class-body-v2addmetadataontransactionresponse
