VERSION 0.8

IMPORT github.com/formancehq/earthly:tags/v0.17.1 AS core

FROM core+base-image

run:
    WAIT
        BUILD +requirements-build
    END

    FROM curlimages/curl
    ARG ANTITHESIS_USERNAME=formance
    ARG --required ANTITHESIS_SLACK_REPORT_RECIPIENT
    RUN --no-cache --secret ANTITHESIS_PASSWORD curl \
        --fail \
        --user "$ANTITHESIS_USERNAME:$ANTITHESIS_PASSWORD" \
        -X POST https://formance.antithesis.com/api/v1/launch_experiment/formance -d "{
          \"params\": {
            \"custom.duration\": \"0.1\",
            \"antithesis.report.recipients\": \"${ANTITHESIS_SLACK_REPORT_RECIPIENT}\",
            \"antithesis.config_image\": \"antithesis-config:latest\",
            \"antithesis.images\": \"ledger:latest;workload:latest\"
          }
        }"

requirements-build:
  ARG --required ANTITHESIS_REPOSITORY

  BUILD --pass-args ./config+build
  BUILD --pass-args ./image+build
  BUILD --pass-args ./workload+build