build-manifest:
	rm -f -- tmp/resources.yaml
	mkdir -p tmp
	cat manifests/namespace.yaml >> tmp/resources.yaml
	echo "---" >> tmp/resources.yaml
	cat manifests/postgres.yaml >> tmp/resources.yaml
	echo "---" >> tmp/resources.yaml
	helm template regions oci://ghcr.io/formancehq/helm/regions --version 2.15.2 --namespace formance-systems >> tmp/resources.yaml
	echo "---" >> tmp/resources.yaml
	cat manifests/stack.yaml >> tmp/resources.yaml
	echo "---" >> tmp/resources.yaml
	yq '.spec.version = strenv(LEDGER_PREVIOUS_TAG)' manifests/ledger.yaml >> tmp/resources.yaml
	echo "---" >> tmp/resources.yaml
	cat manifests/workload.yaml >> tmp/resources.yaml

push: build-manifest
	docker build -f Dockerfile.config -t $ANTITHESIS_REPOSITORY/antithesis-config:daily_run .
	docker push $ANTITHESIS_REPOSITORY/antithesis-config:daily_run
