build-manifest output:
	rm -f -- '{{output}}'
	helm dependency update
	helm dependency build
	helm template . --include-crds > '{{output}}'

push:
	#!/usr/bin/env bash

	set -euxo pipefail
	tmpdir=$(mktemp -d)
	trap 'rm -rf $tmpdir' EXIT

	just build-manifest "$tmpdir/resources.yaml"

	docker build -f Dockerfile.config -t $ANTITHESIS_REPOSITORY/antithesis-config:ledger_v3 $tmpdir
	docker push $ANTITHESIS_REPOSITORY/antithesis-config:ledger_v3
