tag := "antithesis"

build-config output:
	sed 's/__TAG__/{{tag}}/g' docker-compose.yaml > '{{output}}'

push *ARGS:
	#!/usr/bin/env bash

	set -euxo pipefail
	tmpdir=$(mktemp -d)
	trap 'rm -rf $tmpdir' EXIT

	just build-config "$tmpdir/docker-compose.yaml"

	docker build --platform linux/amd64 -f Dockerfile.config -t $ANTITHESIS_REPOSITORY/antithesis-config-ledger-v3:{{tag}} $tmpdir
	docker push $ANTITHESIS_REPOSITORY/antithesis-config-ledger-v3:{{tag}}
