build-manifest output:
	rm -f -- '{{output}}'
	helm dependency update
	helm dependency build
	helm template . --include-crds --set "ledger-operator.image.tag=$RUN_TAG" --set "run_tag=$RUN_TAG" > '{{output}}'

push:
	#!/usr/bin/env bash

	set -euxo pipefail
	tmpdir=$(mktemp -d)
	trap 'rm -rf $tmpdir' EXIT

	just build-manifest "$tmpdir/resources.yaml"

	docker build --platform linux/amd64 -f Dockerfile.config -t $ANTITHESIS_REPOSITORY/antithesis-config-ledger-v3:$RUN_TAG $tmpdir
	docker push $ANTITHESIS_REPOSITORY/antithesis-config-ledger-v3:$RUN_TAG
