// Code generated by MockGen. DO NOT EDIT.
//
// Generated by this command:
//
//	mockgen -typed -write_source_comment=false -write_package_comment=false -destination controller_generated_test.go -package grpc github.com/formancehq/ledger/v3/internal/application/ctrl Controller
//

package grpc

import (
	context "context"
	reflect "reflect"

	cursor "github.com/formancehq/ledger/v3/internal/pkg/cursor"
	auditpb "github.com/formancehq/ledger/v3/internal/proto/auditpb"
	commonpb "github.com/formancehq/ledger/v3/internal/proto/commonpb"
	servicepb "github.com/formancehq/ledger/v3/internal/proto/servicepb"
	query "github.com/formancehq/ledger/v3/internal/query"
	gomock "go.uber.org/mock/gomock"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
	isgomock struct{}
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// AggregateVolumes mocks base method.
func (m *MockController) AggregateVolumes(ctx context.Context, ledgerName string, filter *commonpb.QueryFilter, opts query.AggregateOptions) (*commonpb.AggregateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateVolumes", ctx, ledgerName, filter, opts)
	ret0, _ := ret[0].(*commonpb.AggregateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AggregateVolumes indicates an expected call of AggregateVolumes.
func (mr *MockControllerMockRecorder) AggregateVolumes(ctx, ledgerName, filter, opts any) *MockControllerAggregateVolumesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateVolumes", reflect.TypeOf((*MockController)(nil).AggregateVolumes), ctx, ledgerName, filter, opts)
	return &MockControllerAggregateVolumesCall{Call: call}
}

// MockControllerAggregateVolumesCall wrap *gomock.Call
type MockControllerAggregateVolumesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerAggregateVolumesCall) Return(arg0 *commonpb.AggregateResult, arg1 error) *MockControllerAggregateVolumesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerAggregateVolumesCall) Do(f func(context.Context, string, *commonpb.QueryFilter, query.AggregateOptions) (*commonpb.AggregateResult, error)) *MockControllerAggregateVolumesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerAggregateVolumesCall) DoAndReturn(f func(context.Context, string, *commonpb.QueryFilter, query.AggregateOptions) (*commonpb.AggregateResult, error)) *MockControllerAggregateVolumesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AnalyzeAccounts mocks base method.
func (m *MockController) AnalyzeAccounts(ctx context.Context, ledgerName string, variableThreshold uint32, onProgress func(uint64, uint64)) (*servicepb.AnalyzeAccountsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnalyzeAccounts", ctx, ledgerName, variableThreshold, onProgress)
	ret0, _ := ret[0].(*servicepb.AnalyzeAccountsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyzeAccounts indicates an expected call of AnalyzeAccounts.
func (mr *MockControllerMockRecorder) AnalyzeAccounts(ctx, ledgerName, variableThreshold, onProgress any) *MockControllerAnalyzeAccountsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyzeAccounts", reflect.TypeOf((*MockController)(nil).AnalyzeAccounts), ctx, ledgerName, variableThreshold, onProgress)
	return &MockControllerAnalyzeAccountsCall{Call: call}
}

// MockControllerAnalyzeAccountsCall wrap *gomock.Call
type MockControllerAnalyzeAccountsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerAnalyzeAccountsCall) Return(arg0 *servicepb.AnalyzeAccountsResponse, arg1 error) *MockControllerAnalyzeAccountsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerAnalyzeAccountsCall) Do(f func(context.Context, string, uint32, func(uint64, uint64)) (*servicepb.AnalyzeAccountsResponse, error)) *MockControllerAnalyzeAccountsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerAnalyzeAccountsCall) DoAndReturn(f func(context.Context, string, uint32, func(uint64, uint64)) (*servicepb.AnalyzeAccountsResponse, error)) *MockControllerAnalyzeAccountsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AnalyzeTransactions mocks base method.
func (m *MockController) AnalyzeTransactions(ctx context.Context, ledgerName string, variableThreshold uint32, onProgress func(uint64, uint64)) (*servicepb.AnalyzeTransactionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnalyzeTransactions", ctx, ledgerName, variableThreshold, onProgress)
	ret0, _ := ret[0].(*servicepb.AnalyzeTransactionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AnalyzeTransactions indicates an expected call of AnalyzeTransactions.
func (mr *MockControllerMockRecorder) AnalyzeTransactions(ctx, ledgerName, variableThreshold, onProgress any) *MockControllerAnalyzeTransactionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnalyzeTransactions", reflect.TypeOf((*MockController)(nil).AnalyzeTransactions), ctx, ledgerName, variableThreshold, onProgress)
	return &MockControllerAnalyzeTransactionsCall{Call: call}
}

// MockControllerAnalyzeTransactionsCall wrap *gomock.Call
type MockControllerAnalyzeTransactionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerAnalyzeTransactionsCall) Return(arg0 *servicepb.AnalyzeTransactionsResponse, arg1 error) *MockControllerAnalyzeTransactionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerAnalyzeTransactionsCall) Do(f func(context.Context, string, uint32, func(uint64, uint64)) (*servicepb.AnalyzeTransactionsResponse, error)) *MockControllerAnalyzeTransactionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerAnalyzeTransactionsCall) DoAndReturn(f func(context.Context, string, uint32, func(uint64, uint64)) (*servicepb.AnalyzeTransactionsResponse, error)) *MockControllerAnalyzeTransactionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Apply mocks base method.
func (m *MockController) Apply(ctx context.Context, req *servicepb.ApplyRequest) ([]*commonpb.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", ctx, req)
	ret0, _ := ret[0].([]*commonpb.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Apply indicates an expected call of Apply.
func (mr *MockControllerMockRecorder) Apply(ctx, req any) *MockControllerApplyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockController)(nil).Apply), ctx, req)
	return &MockControllerApplyCall{Call: call}
}

// MockControllerApplyCall wrap *gomock.Call
type MockControllerApplyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerApplyCall) Return(arg0 []*commonpb.Log, arg1 error) *MockControllerApplyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerApplyCall) Do(f func(context.Context, *servicepb.ApplyRequest) ([]*commonpb.Log, error)) *MockControllerApplyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerApplyCall) DoAndReturn(f func(context.Context, *servicepb.ApplyRequest) ([]*commonpb.Log, error)) *MockControllerApplyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Barrier mocks base method.
func (m *MockController) Barrier(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Barrier", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Barrier indicates an expected call of Barrier.
func (mr *MockControllerMockRecorder) Barrier(ctx any) *MockControllerBarrierCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Barrier", reflect.TypeOf((*MockController)(nil).Barrier), ctx)
	return &MockControllerBarrierCall{Call: call}
}

// MockControllerBarrierCall wrap *gomock.Call
type MockControllerBarrierCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerBarrierCall) Return(arg0 uint64, arg1 error) *MockControllerBarrierCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerBarrierCall) Do(f func(context.Context) (uint64, error)) *MockControllerBarrierCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerBarrierCall) DoAndReturn(f func(context.Context) (uint64, error)) *MockControllerBarrierCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ExecutePreparedQuery mocks base method.
func (m *MockController) ExecutePreparedQuery(ctx context.Context, req *servicepb.ExecutePreparedQueryRequest) (*servicepb.ExecutePreparedQueryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutePreparedQuery", ctx, req)
	ret0, _ := ret[0].(*servicepb.ExecutePreparedQueryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecutePreparedQuery indicates an expected call of ExecutePreparedQuery.
func (mr *MockControllerMockRecorder) ExecutePreparedQuery(ctx, req any) *MockControllerExecutePreparedQueryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutePreparedQuery", reflect.TypeOf((*MockController)(nil).ExecutePreparedQuery), ctx, req)
	return &MockControllerExecutePreparedQueryCall{Call: call}
}

// MockControllerExecutePreparedQueryCall wrap *gomock.Call
type MockControllerExecutePreparedQueryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerExecutePreparedQueryCall) Return(arg0 *servicepb.ExecutePreparedQueryResponse, arg1 error) *MockControllerExecutePreparedQueryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerExecutePreparedQueryCall) Do(f func(context.Context, *servicepb.ExecutePreparedQueryRequest) (*servicepb.ExecutePreparedQueryResponse, error)) *MockControllerExecutePreparedQueryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerExecutePreparedQueryCall) DoAndReturn(f func(context.Context, *servicepb.ExecutePreparedQueryRequest) (*servicepb.ExecutePreparedQueryResponse, error)) *MockControllerExecutePreparedQueryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAccount mocks base method.
func (m *MockController) GetAccount(ctx context.Context, ledgerName, address string) (*commonpb.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, ledgerName, address)
	ret0, _ := ret[0].(*commonpb.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockControllerMockRecorder) GetAccount(ctx, ledgerName, address any) *MockControllerGetAccountCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockController)(nil).GetAccount), ctx, ledgerName, address)
	return &MockControllerGetAccountCall{Call: call}
}

// MockControllerGetAccountCall wrap *gomock.Call
type MockControllerGetAccountCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerGetAccountCall) Return(arg0 *commonpb.Account, arg1 error) *MockControllerGetAccountCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerGetAccountCall) Do(f func(context.Context, string, string) (*commonpb.Account, error)) *MockControllerGetAccountCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerGetAccountCall) DoAndReturn(f func(context.Context, string, string) (*commonpb.Account, error)) *MockControllerGetAccountCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAuditEntry mocks base method.
func (m *MockController) GetAuditEntry(ctx context.Context, sequence uint64) (*auditpb.AuditEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuditEntry", ctx, sequence)
	ret0, _ := ret[0].(*auditpb.AuditEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuditEntry indicates an expected call of GetAuditEntry.
func (mr *MockControllerMockRecorder) GetAuditEntry(ctx, sequence any) *MockControllerGetAuditEntryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuditEntry", reflect.TypeOf((*MockController)(nil).GetAuditEntry), ctx, sequence)
	return &MockControllerGetAuditEntryCall{Call: call}
}

// MockControllerGetAuditEntryCall wrap *gomock.Call
type MockControllerGetAuditEntryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerGetAuditEntryCall) Return(arg0 *auditpb.AuditEntry, arg1 error) *MockControllerGetAuditEntryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerGetAuditEntryCall) Do(f func(context.Context, uint64) (*auditpb.AuditEntry, error)) *MockControllerGetAuditEntryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerGetAuditEntryCall) DoAndReturn(f func(context.Context, uint64) (*auditpb.AuditEntry, error)) *MockControllerGetAuditEntryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetChapterSchedule mocks base method.
func (m *MockController) GetChapterSchedule(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChapterSchedule", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChapterSchedule indicates an expected call of GetChapterSchedule.
func (mr *MockControllerMockRecorder) GetChapterSchedule(ctx any) *MockControllerGetChapterScheduleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChapterSchedule", reflect.TypeOf((*MockController)(nil).GetChapterSchedule), ctx)
	return &MockControllerGetChapterScheduleCall{Call: call}
}

// MockControllerGetChapterScheduleCall wrap *gomock.Call
type MockControllerGetChapterScheduleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerGetChapterScheduleCall) Return(arg0 string, arg1 error) *MockControllerGetChapterScheduleCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerGetChapterScheduleCall) Do(f func(context.Context) (string, error)) *MockControllerGetChapterScheduleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerGetChapterScheduleCall) DoAndReturn(f func(context.Context) (string, error)) *MockControllerGetChapterScheduleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetEventsSinks mocks base method.
func (m *MockController) GetEventsSinks(ctx context.Context) ([]*commonpb.SinkConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsSinks", ctx)
	ret0, _ := ret[0].([]*commonpb.SinkConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsSinks indicates an expected call of GetEventsSinks.
func (mr *MockControllerMockRecorder) GetEventsSinks(ctx any) *MockControllerGetEventsSinksCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsSinks", reflect.TypeOf((*MockController)(nil).GetEventsSinks), ctx)
	return &MockControllerGetEventsSinksCall{Call: call}
}

// MockControllerGetEventsSinksCall wrap *gomock.Call
type MockControllerGetEventsSinksCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerGetEventsSinksCall) Return(arg0 []*commonpb.SinkConfig, arg1 error) *MockControllerGetEventsSinksCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerGetEventsSinksCall) Do(f func(context.Context) ([]*commonpb.SinkConfig, error)) *MockControllerGetEventsSinksCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerGetEventsSinksCall) DoAndReturn(f func(context.Context) ([]*commonpb.SinkConfig, error)) *MockControllerGetEventsSinksCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetLedgerByName mocks base method.
func (m *MockController) GetLedgerByName(ctx context.Context, name string) (*commonpb.LedgerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLedgerByName", ctx, name)
	ret0, _ := ret[0].(*commonpb.LedgerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedgerByName indicates an expected call of GetLedgerByName.
func (mr *MockControllerMockRecorder) GetLedgerByName(ctx, name any) *MockControllerGetLedgerByNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedgerByName", reflect.TypeOf((*MockController)(nil).GetLedgerByName), ctx, name)
	return &MockControllerGetLedgerByNameCall{Call: call}
}

// MockControllerGetLedgerByNameCall wrap *gomock.Call
type MockControllerGetLedgerByNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerGetLedgerByNameCall) Return(arg0 *commonpb.LedgerInfo, arg1 error) *MockControllerGetLedgerByNameCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerGetLedgerByNameCall) Do(f func(context.Context, string) (*commonpb.LedgerInfo, error)) *MockControllerGetLedgerByNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerGetLedgerByNameCall) DoAndReturn(f func(context.Context, string) (*commonpb.LedgerInfo, error)) *MockControllerGetLedgerByNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetLedgerStats mocks base method.
func (m *MockController) GetLedgerStats(ctx context.Context, ledgerName string) (*commonpb.LedgerStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLedgerStats", ctx, ledgerName)
	ret0, _ := ret[0].(*commonpb.LedgerStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedgerStats indicates an expected call of GetLedgerStats.
func (mr *MockControllerMockRecorder) GetLedgerStats(ctx, ledgerName any) *MockControllerGetLedgerStatsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedgerStats", reflect.TypeOf((*MockController)(nil).GetLedgerStats), ctx, ledgerName)
	return &MockControllerGetLedgerStatsCall{Call: call}
}

// MockControllerGetLedgerStatsCall wrap *gomock.Call
type MockControllerGetLedgerStatsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerGetLedgerStatsCall) Return(arg0 *commonpb.LedgerStats, arg1 error) *MockControllerGetLedgerStatsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerGetLedgerStatsCall) Do(f func(context.Context, string) (*commonpb.LedgerStats, error)) *MockControllerGetLedgerStatsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerGetLedgerStatsCall) DoAndReturn(f func(context.Context, string) (*commonpb.LedgerStats, error)) *MockControllerGetLedgerStatsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetLog mocks base method.
func (m *MockController) GetLog(ctx context.Context, sequence uint64) (*commonpb.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLog", ctx, sequence)
	ret0, _ := ret[0].(*commonpb.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLog indicates an expected call of GetLog.
func (mr *MockControllerMockRecorder) GetLog(ctx, sequence any) *MockControllerGetLogCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLog", reflect.TypeOf((*MockController)(nil).GetLog), ctx, sequence)
	return &MockControllerGetLogCall{Call: call}
}

// MockControllerGetLogCall wrap *gomock.Call
type MockControllerGetLogCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerGetLogCall) Return(arg0 *commonpb.Log, arg1 error) *MockControllerGetLogCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerGetLogCall) Do(f func(context.Context, uint64) (*commonpb.Log, error)) *MockControllerGetLogCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerGetLogCall) DoAndReturn(f func(context.Context, uint64) (*commonpb.Log, error)) *MockControllerGetLogCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetMetadataSchemaStatus mocks base method.
func (m *MockController) GetMetadataSchemaStatus(ctx context.Context, ledgerName string) (*servicepb.GetMetadataSchemaStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadataSchemaStatus", ctx, ledgerName)
	ret0, _ := ret[0].(*servicepb.GetMetadataSchemaStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadataSchemaStatus indicates an expected call of GetMetadataSchemaStatus.
func (mr *MockControllerMockRecorder) GetMetadataSchemaStatus(ctx, ledgerName any) *MockControllerGetMetadataSchemaStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadataSchemaStatus", reflect.TypeOf((*MockController)(nil).GetMetadataSchemaStatus), ctx, ledgerName)
	return &MockControllerGetMetadataSchemaStatusCall{Call: call}
}

// MockControllerGetMetadataSchemaStatusCall wrap *gomock.Call
type MockControllerGetMetadataSchemaStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerGetMetadataSchemaStatusCall) Return(arg0 *servicepb.GetMetadataSchemaStatusResponse, arg1 error) *MockControllerGetMetadataSchemaStatusCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerGetMetadataSchemaStatusCall) Do(f func(context.Context, string) (*servicepb.GetMetadataSchemaStatusResponse, error)) *MockControllerGetMetadataSchemaStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerGetMetadataSchemaStatusCall) DoAndReturn(f func(context.Context, string) (*servicepb.GetMetadataSchemaStatusResponse, error)) *MockControllerGetMetadataSchemaStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetNumscript mocks base method.
func (m *MockController) GetNumscript(ctx context.Context, ledger, name, version string) (*commonpb.NumscriptInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNumscript", ctx, ledger, name, version)
	ret0, _ := ret[0].(*commonpb.NumscriptInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNumscript indicates an expected call of GetNumscript.
func (mr *MockControllerMockRecorder) GetNumscript(ctx, ledger, name, version any) *MockControllerGetNumscriptCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNumscript", reflect.TypeOf((*MockController)(nil).GetNumscript), ctx, ledger, name, version)
	return &MockControllerGetNumscriptCall{Call: call}
}

// MockControllerGetNumscriptCall wrap *gomock.Call
type MockControllerGetNumscriptCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerGetNumscriptCall) Return(arg0 *commonpb.NumscriptInfo, arg1 error) *MockControllerGetNumscriptCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerGetNumscriptCall) Do(f func(context.Context, string, string, string) (*commonpb.NumscriptInfo, error)) *MockControllerGetNumscriptCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerGetNumscriptCall) DoAndReturn(f func(context.Context, string, string, string) (*commonpb.NumscriptInfo, error)) *MockControllerGetNumscriptCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetTemplateUsage mocks base method.
func (m *MockController) GetTemplateUsage(ctx context.Context, ledger, name string) (*commonpb.TemplateUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateUsage", ctx, ledger, name)
	ret0, _ := ret[0].(*commonpb.TemplateUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplateUsage indicates an expected call of GetTemplateUsage.
func (mr *MockControllerMockRecorder) GetTemplateUsage(ctx, ledger, name any) *MockControllerGetTemplateUsageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateUsage", reflect.TypeOf((*MockController)(nil).GetTemplateUsage), ctx, ledger, name)
	return &MockControllerGetTemplateUsageCall{Call: call}
}

// MockControllerGetTemplateUsageCall wrap *gomock.Call
type MockControllerGetTemplateUsageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerGetTemplateUsageCall) Return(arg0 *commonpb.TemplateUsage, arg1 error) *MockControllerGetTemplateUsageCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerGetTemplateUsageCall) Do(f func(context.Context, string, string) (*commonpb.TemplateUsage, error)) *MockControllerGetTemplateUsageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerGetTemplateUsageCall) DoAndReturn(f func(context.Context, string, string) (*commonpb.TemplateUsage, error)) *MockControllerGetTemplateUsageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetTransaction mocks base method.
func (m *MockController) GetTransaction(ctx context.Context, ledgerName string, transactionID uint64) (*commonpb.Transaction, *string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, ledgerName, transactionID)
	ret0, _ := ret[0].(*commonpb.Transaction)
	ret1, _ := ret[1].(*string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockControllerMockRecorder) GetTransaction(ctx, ledgerName, transactionID any) *MockControllerGetTransactionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockController)(nil).GetTransaction), ctx, ledgerName, transactionID)
	return &MockControllerGetTransactionCall{Call: call}
}

// MockControllerGetTransactionCall wrap *gomock.Call
type MockControllerGetTransactionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerGetTransactionCall) Return(arg0 *commonpb.Transaction, arg1 *string, arg2 error) *MockControllerGetTransactionCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerGetTransactionCall) Do(f func(context.Context, string, uint64) (*commonpb.Transaction, *string, error)) *MockControllerGetTransactionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerGetTransactionCall) DoAndReturn(f func(context.Context, string, uint64) (*commonpb.Transaction, *string, error)) *MockControllerGetTransactionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// InspectIndex mocks base method.
func (m *MockController) InspectIndex(ctx context.Context, req *servicepb.InspectIndexRequest) (*servicepb.InspectIndexResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InspectIndex", ctx, req)
	ret0, _ := ret[0].(*servicepb.InspectIndexResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InspectIndex indicates an expected call of InspectIndex.
func (mr *MockControllerMockRecorder) InspectIndex(ctx, req any) *MockControllerInspectIndexCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InspectIndex", reflect.TypeOf((*MockController)(nil).InspectIndex), ctx, req)
	return &MockControllerInspectIndexCall{Call: call}
}

// MockControllerInspectIndexCall wrap *gomock.Call
type MockControllerInspectIndexCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerInspectIndexCall) Return(arg0 *servicepb.InspectIndexResponse, arg1 error) *MockControllerInspectIndexCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerInspectIndexCall) Do(f func(context.Context, *servicepb.InspectIndexRequest) (*servicepb.InspectIndexResponse, error)) *MockControllerInspectIndexCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerInspectIndexCall) DoAndReturn(f func(context.Context, *servicepb.InspectIndexRequest) (*servicepb.InspectIndexResponse, error)) *MockControllerInspectIndexCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListAccounts mocks base method.
func (m *MockController) ListAccounts(ctx context.Context, ledgerName string, pageSize uint32, afterAddress string, filter *commonpb.QueryFilter, reverse bool) (cursor.Cursor[*commonpb.Account], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccounts", ctx, ledgerName, pageSize, afterAddress, filter, reverse)
	ret0, _ := ret[0].(cursor.Cursor[*commonpb.Account])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccounts indicates an expected call of ListAccounts.
func (mr *MockControllerMockRecorder) ListAccounts(ctx, ledgerName, pageSize, afterAddress, filter, reverse any) *MockControllerListAccountsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccounts", reflect.TypeOf((*MockController)(nil).ListAccounts), ctx, ledgerName, pageSize, afterAddress, filter, reverse)
	return &MockControllerListAccountsCall{Call: call}
}

// MockControllerListAccountsCall wrap *gomock.Call
type MockControllerListAccountsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerListAccountsCall) Return(arg0 cursor.Cursor[*commonpb.Account], arg1 error) *MockControllerListAccountsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerListAccountsCall) Do(f func(context.Context, string, uint32, string, *commonpb.QueryFilter, bool) (cursor.Cursor[*commonpb.Account], error)) *MockControllerListAccountsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerListAccountsCall) DoAndReturn(f func(context.Context, string, uint32, string, *commonpb.QueryFilter, bool) (cursor.Cursor[*commonpb.Account], error)) *MockControllerListAccountsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListAuditEntries mocks base method.
func (m *MockController) ListAuditEntries(ctx context.Context, pageSize uint32, afterSequence uint64, filter *commonpb.QueryFilter, reverse bool) (cursor.Cursor[*auditpb.AuditEntry], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuditEntries", ctx, pageSize, afterSequence, filter, reverse)
	ret0, _ := ret[0].(cursor.Cursor[*auditpb.AuditEntry])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAuditEntries indicates an expected call of ListAuditEntries.
func (mr *MockControllerMockRecorder) ListAuditEntries(ctx, pageSize, afterSequence, filter, reverse any) *MockControllerListAuditEntriesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuditEntries", reflect.TypeOf((*MockController)(nil).ListAuditEntries), ctx, pageSize, afterSequence, filter, reverse)
	return &MockControllerListAuditEntriesCall{Call: call}
}

// MockControllerListAuditEntriesCall wrap *gomock.Call
type MockControllerListAuditEntriesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerListAuditEntriesCall) Return(arg0 cursor.Cursor[*auditpb.AuditEntry], arg1 error) *MockControllerListAuditEntriesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerListAuditEntriesCall) Do(f func(context.Context, uint32, uint64, *commonpb.QueryFilter, bool) (cursor.Cursor[*auditpb.AuditEntry], error)) *MockControllerListAuditEntriesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerListAuditEntriesCall) DoAndReturn(f func(context.Context, uint32, uint64, *commonpb.QueryFilter, bool) (cursor.Cursor[*auditpb.AuditEntry], error)) *MockControllerListAuditEntriesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListChapters mocks base method.
func (m *MockController) ListChapters(ctx context.Context) (cursor.Cursor[*commonpb.Chapter], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChapters", ctx)
	ret0, _ := ret[0].(cursor.Cursor[*commonpb.Chapter])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChapters indicates an expected call of ListChapters.
func (mr *MockControllerMockRecorder) ListChapters(ctx any) *MockControllerListChaptersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChapters", reflect.TypeOf((*MockController)(nil).ListChapters), ctx)
	return &MockControllerListChaptersCall{Call: call}
}

// MockControllerListChaptersCall wrap *gomock.Call
type MockControllerListChaptersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerListChaptersCall) Return(arg0 cursor.Cursor[*commonpb.Chapter], arg1 error) *MockControllerListChaptersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerListChaptersCall) Do(f func(context.Context) (cursor.Cursor[*commonpb.Chapter], error)) *MockControllerListChaptersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerListChaptersCall) DoAndReturn(f func(context.Context) (cursor.Cursor[*commonpb.Chapter], error)) *MockControllerListChaptersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListLedgers mocks base method.
func (m *MockController) ListLedgers(ctx context.Context) (cursor.Cursor[*commonpb.LedgerInfo], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLedgers", ctx)
	ret0, _ := ret[0].(cursor.Cursor[*commonpb.LedgerInfo])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLedgers indicates an expected call of ListLedgers.
func (mr *MockControllerMockRecorder) ListLedgers(ctx any) *MockControllerListLedgersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLedgers", reflect.TypeOf((*MockController)(nil).ListLedgers), ctx)
	return &MockControllerListLedgersCall{Call: call}
}

// MockControllerListLedgersCall wrap *gomock.Call
type MockControllerListLedgersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerListLedgersCall) Return(arg0 cursor.Cursor[*commonpb.LedgerInfo], arg1 error) *MockControllerListLedgersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerListLedgersCall) Do(f func(context.Context) (cursor.Cursor[*commonpb.LedgerInfo], error)) *MockControllerListLedgersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerListLedgersCall) DoAndReturn(f func(context.Context) (cursor.Cursor[*commonpb.LedgerInfo], error)) *MockControllerListLedgersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListLogs mocks base method.
func (m *MockController) ListLogs(ctx context.Context, ledgerName string, afterSequence uint64, pageSize uint32, filter *commonpb.QueryFilter) (cursor.Cursor[*commonpb.Log], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLogs", ctx, ledgerName, afterSequence, pageSize, filter)
	ret0, _ := ret[0].(cursor.Cursor[*commonpb.Log])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLogs indicates an expected call of ListLogs.
func (mr *MockControllerMockRecorder) ListLogs(ctx, ledgerName, afterSequence, pageSize, filter any) *MockControllerListLogsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLogs", reflect.TypeOf((*MockController)(nil).ListLogs), ctx, ledgerName, afterSequence, pageSize, filter)
	return &MockControllerListLogsCall{Call: call}
}

// MockControllerListLogsCall wrap *gomock.Call
type MockControllerListLogsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerListLogsCall) Return(arg0 cursor.Cursor[*commonpb.Log], arg1 error) *MockControllerListLogsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerListLogsCall) Do(f func(context.Context, string, uint64, uint32, *commonpb.QueryFilter) (cursor.Cursor[*commonpb.Log], error)) *MockControllerListLogsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerListLogsCall) DoAndReturn(f func(context.Context, string, uint64, uint32, *commonpb.QueryFilter) (cursor.Cursor[*commonpb.Log], error)) *MockControllerListLogsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListNumscripts mocks base method.
func (m *MockController) ListNumscripts(ctx context.Context, ledger string) ([]*commonpb.NumscriptInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNumscripts", ctx, ledger)
	ret0, _ := ret[0].([]*commonpb.NumscriptInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNumscripts indicates an expected call of ListNumscripts.
func (mr *MockControllerMockRecorder) ListNumscripts(ctx, ledger any) *MockControllerListNumscriptsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNumscripts", reflect.TypeOf((*MockController)(nil).ListNumscripts), ctx, ledger)
	return &MockControllerListNumscriptsCall{Call: call}
}

// MockControllerListNumscriptsCall wrap *gomock.Call
type MockControllerListNumscriptsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerListNumscriptsCall) Return(arg0 []*commonpb.NumscriptInfo, arg1 error) *MockControllerListNumscriptsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerListNumscriptsCall) Do(f func(context.Context, string) ([]*commonpb.NumscriptInfo, error)) *MockControllerListNumscriptsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerListNumscriptsCall) DoAndReturn(f func(context.Context, string) ([]*commonpb.NumscriptInfo, error)) *MockControllerListNumscriptsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListPreparedQueries mocks base method.
func (m *MockController) ListPreparedQueries(ctx context.Context, ledger string) ([]*commonpb.PreparedQuery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPreparedQueries", ctx, ledger)
	ret0, _ := ret[0].([]*commonpb.PreparedQuery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPreparedQueries indicates an expected call of ListPreparedQueries.
func (mr *MockControllerMockRecorder) ListPreparedQueries(ctx, ledger any) *MockControllerListPreparedQueriesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPreparedQueries", reflect.TypeOf((*MockController)(nil).ListPreparedQueries), ctx, ledger)
	return &MockControllerListPreparedQueriesCall{Call: call}
}

// MockControllerListPreparedQueriesCall wrap *gomock.Call
type MockControllerListPreparedQueriesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerListPreparedQueriesCall) Return(arg0 []*commonpb.PreparedQuery, arg1 error) *MockControllerListPreparedQueriesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerListPreparedQueriesCall) Do(f func(context.Context, string) ([]*commonpb.PreparedQuery, error)) *MockControllerListPreparedQueriesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerListPreparedQueriesCall) DoAndReturn(f func(context.Context, string) ([]*commonpb.PreparedQuery, error)) *MockControllerListPreparedQueriesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListSigningKeys mocks base method.
func (m *MockController) ListSigningKeys(ctx context.Context) (cursor.Cursor[*commonpb.SigningKey], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSigningKeys", ctx)
	ret0, _ := ret[0].(cursor.Cursor[*commonpb.SigningKey])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSigningKeys indicates an expected call of ListSigningKeys.
func (mr *MockControllerMockRecorder) ListSigningKeys(ctx any) *MockControllerListSigningKeysCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSigningKeys", reflect.TypeOf((*MockController)(nil).ListSigningKeys), ctx)
	return &MockControllerListSigningKeysCall{Call: call}
}

// MockControllerListSigningKeysCall wrap *gomock.Call
type MockControllerListSigningKeysCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerListSigningKeysCall) Return(arg0 cursor.Cursor[*commonpb.SigningKey], arg1 error) *MockControllerListSigningKeysCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerListSigningKeysCall) Do(f func(context.Context) (cursor.Cursor[*commonpb.SigningKey], error)) *MockControllerListSigningKeysCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerListSigningKeysCall) DoAndReturn(f func(context.Context) (cursor.Cursor[*commonpb.SigningKey], error)) *MockControllerListSigningKeysCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListTransactions mocks base method.
func (m *MockController) ListTransactions(ctx context.Context, ledgerName string, pageSize uint32, afterTxID uint64, filter *commonpb.QueryFilter, reverse bool) (cursor.Cursor[*commonpb.Transaction], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", ctx, ledgerName, pageSize, afterTxID, filter, reverse)
	ret0, _ := ret[0].(cursor.Cursor[*commonpb.Transaction])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockControllerMockRecorder) ListTransactions(ctx, ledgerName, pageSize, afterTxID, filter, reverse any) *MockControllerListTransactionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockController)(nil).ListTransactions), ctx, ledgerName, pageSize, afterTxID, filter, reverse)
	return &MockControllerListTransactionsCall{Call: call}
}

// MockControllerListTransactionsCall wrap *gomock.Call
type MockControllerListTransactionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockControllerListTransactionsCall) Return(arg0 cursor.Cursor[*commonpb.Transaction], arg1 error) *MockControllerListTransactionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockControllerListTransactionsCall) Do(f func(context.Context, string, uint32, uint64, *commonpb.QueryFilter, bool) (cursor.Cursor[*commonpb.Transaction], error)) *MockControllerListTransactionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockControllerListTransactionsCall) DoAndReturn(f func(context.Context, string, uint32, uint64, *commonpb.QueryFilter, bool) (cursor.Cursor[*commonpb.Transaction], error)) *MockControllerListTransactionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
