// Code generated by MockGen. DO NOT EDIT.
//
// Generated by this command:
//
//	mockgen -typed -write_source_comment=false -write_package_comment=false -destination server_streaming_server_generated_test.go -package grpc google.golang.org/grpc ServerStreamingServer
//

package grpc

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	metadata "google.golang.org/grpc/metadata"
)

// MockServerStreamingServer is a mock of ServerStreamingServer interface.
type MockServerStreamingServer[Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockServerStreamingServerMockRecorder[Res]
	isgomock struct{}
}

// MockServerStreamingServerMockRecorder is the mock recorder for MockServerStreamingServer.
type MockServerStreamingServerMockRecorder[Res any] struct {
	mock *MockServerStreamingServer[Res]
}

// NewMockServerStreamingServer creates a new mock instance.
func NewMockServerStreamingServer[Res any](ctrl *gomock.Controller) *MockServerStreamingServer[Res] {
	mock := &MockServerStreamingServer[Res]{ctrl: ctrl}
	mock.recorder = &MockServerStreamingServerMockRecorder[Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerStreamingServer[Res]) EXPECT() *MockServerStreamingServerMockRecorder[Res] {
	return m.recorder
}

// Context mocks base method.
func (m *MockServerStreamingServer[Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockServerStreamingServerMockRecorder[Res]) Context() *MockServerStreamingServerContextCall[Res] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockServerStreamingServer[Res])(nil).Context))
	return &MockServerStreamingServerContextCall[Res]{Call: call}
}

// MockServerStreamingServerContextCall wrap *gomock.Call
type MockServerStreamingServerContextCall[Res any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServerStreamingServerContextCall[Res]) Return(arg0 context.Context) *MockServerStreamingServerContextCall[Res] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServerStreamingServerContextCall[Res]) Do(f func() context.Context) *MockServerStreamingServerContextCall[Res] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServerStreamingServerContextCall[Res]) DoAndReturn(f func() context.Context) *MockServerStreamingServerContextCall[Res] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RecvMsg mocks base method.
func (m_2 *MockServerStreamingServer[Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockServerStreamingServerMockRecorder[Res]) RecvMsg(m any) *MockServerStreamingServerRecvMsgCall[Res] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockServerStreamingServer[Res])(nil).RecvMsg), m)
	return &MockServerStreamingServerRecvMsgCall[Res]{Call: call}
}

// MockServerStreamingServerRecvMsgCall wrap *gomock.Call
type MockServerStreamingServerRecvMsgCall[Res any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServerStreamingServerRecvMsgCall[Res]) Return(arg0 error) *MockServerStreamingServerRecvMsgCall[Res] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServerStreamingServerRecvMsgCall[Res]) Do(f func(any) error) *MockServerStreamingServerRecvMsgCall[Res] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServerStreamingServerRecvMsgCall[Res]) DoAndReturn(f func(any) error) *MockServerStreamingServerRecvMsgCall[Res] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Send mocks base method.
func (m *MockServerStreamingServer[Res]) Send(arg0 *Res) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockServerStreamingServerMockRecorder[Res]) Send(arg0 any) *MockServerStreamingServerSendCall[Res] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockServerStreamingServer[Res])(nil).Send), arg0)
	return &MockServerStreamingServerSendCall[Res]{Call: call}
}

// MockServerStreamingServerSendCall wrap *gomock.Call
type MockServerStreamingServerSendCall[Res any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServerStreamingServerSendCall[Res]) Return(arg0 error) *MockServerStreamingServerSendCall[Res] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServerStreamingServerSendCall[Res]) Do(f func(*Res) error) *MockServerStreamingServerSendCall[Res] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServerStreamingServerSendCall[Res]) DoAndReturn(f func(*Res) error) *MockServerStreamingServerSendCall[Res] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SendHeader mocks base method.
func (m *MockServerStreamingServer[Res]) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockServerStreamingServerMockRecorder[Res]) SendHeader(arg0 any) *MockServerStreamingServerSendHeaderCall[Res] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockServerStreamingServer[Res])(nil).SendHeader), arg0)
	return &MockServerStreamingServerSendHeaderCall[Res]{Call: call}
}

// MockServerStreamingServerSendHeaderCall wrap *gomock.Call
type MockServerStreamingServerSendHeaderCall[Res any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServerStreamingServerSendHeaderCall[Res]) Return(arg0 error) *MockServerStreamingServerSendHeaderCall[Res] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServerStreamingServerSendHeaderCall[Res]) Do(f func(metadata.MD) error) *MockServerStreamingServerSendHeaderCall[Res] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServerStreamingServerSendHeaderCall[Res]) DoAndReturn(f func(metadata.MD) error) *MockServerStreamingServerSendHeaderCall[Res] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SendMsg mocks base method.
func (m_2 *MockServerStreamingServer[Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockServerStreamingServerMockRecorder[Res]) SendMsg(m any) *MockServerStreamingServerSendMsgCall[Res] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockServerStreamingServer[Res])(nil).SendMsg), m)
	return &MockServerStreamingServerSendMsgCall[Res]{Call: call}
}

// MockServerStreamingServerSendMsgCall wrap *gomock.Call
type MockServerStreamingServerSendMsgCall[Res any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServerStreamingServerSendMsgCall[Res]) Return(arg0 error) *MockServerStreamingServerSendMsgCall[Res] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServerStreamingServerSendMsgCall[Res]) Do(f func(any) error) *MockServerStreamingServerSendMsgCall[Res] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServerStreamingServerSendMsgCall[Res]) DoAndReturn(f func(any) error) *MockServerStreamingServerSendMsgCall[Res] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetHeader mocks base method.
func (m *MockServerStreamingServer[Res]) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockServerStreamingServerMockRecorder[Res]) SetHeader(arg0 any) *MockServerStreamingServerSetHeaderCall[Res] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockServerStreamingServer[Res])(nil).SetHeader), arg0)
	return &MockServerStreamingServerSetHeaderCall[Res]{Call: call}
}

// MockServerStreamingServerSetHeaderCall wrap *gomock.Call
type MockServerStreamingServerSetHeaderCall[Res any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServerStreamingServerSetHeaderCall[Res]) Return(arg0 error) *MockServerStreamingServerSetHeaderCall[Res] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServerStreamingServerSetHeaderCall[Res]) Do(f func(metadata.MD) error) *MockServerStreamingServerSetHeaderCall[Res] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServerStreamingServerSetHeaderCall[Res]) DoAndReturn(f func(metadata.MD) error) *MockServerStreamingServerSetHeaderCall[Res] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetTrailer mocks base method.
func (m *MockServerStreamingServer[Res]) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockServerStreamingServerMockRecorder[Res]) SetTrailer(arg0 any) *MockServerStreamingServerSetTrailerCall[Res] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockServerStreamingServer[Res])(nil).SetTrailer), arg0)
	return &MockServerStreamingServerSetTrailerCall[Res]{Call: call}
}

// MockServerStreamingServerSetTrailerCall wrap *gomock.Call
type MockServerStreamingServerSetTrailerCall[Res any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServerStreamingServerSetTrailerCall[Res]) Return() *MockServerStreamingServerSetTrailerCall[Res] {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServerStreamingServerSetTrailerCall[Res]) Do(f func(metadata.MD)) *MockServerStreamingServerSetTrailerCall[Res] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServerStreamingServerSetTrailerCall[Res]) DoAndReturn(f func(metadata.MD)) *MockServerStreamingServerSetTrailerCall[Res] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
