/**
 * Formance Stack API
 * Open, modular foundation for unique payments flows  # Introduction This API is documented in **OpenAPI format**.  # Authentication Formance Stack offers one forms of authentication:   - OAuth2 OAuth2 - an open protocol to allow secure authorization in a simple and standard method from web, mobile and desktop applications. <SecurityDefinitions /> 
 *
 * OpenAPI spec version: develop
 * Contact: support@formance.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Connector } from '../models/Connector';
import { HttpFile } from '../http/http';

export class PaymentsAccount {
    'id': string;
    'createdAt': Date;
    'provider': Connector;
    'reference': string;
    'type': PaymentsAccountTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "Connector",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PaymentsAccountTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaymentsAccount.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PaymentsAccountTypeEnum = "TARGET" | "SOURCE" ;

