tempo:
  # config Tempo monolithique, stockage local (dev)
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces

persistence:
  enabled: true
  size: 10Gi

service:
  type: ClusterIP

# On expose l’ingestion OTLP directement sur Tempo (pratique et standard)
traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: false
