VERSION 0.7

FROM --platform=linux/amd64 golang:1.22.2

CACHE --sharing=shared --id go-mod-cache /go/pkg/mod
CACHE --sharing=shared --id go-cache /root/.cache/go-build

sources:
    WORKDIR /src/test/antithesis/workload
    COPY go.* .
    COPY --dir bin internal .

    SAVE ARTIFACT /src

compile:
    CACHE --id go-mod-cache /go/pkg/mod
    CACHE --id go-cache /root/.cache/go-build

    RUN go install github.com/antithesishq/antithesis-sdk-go/tools/antithesis-go-instrumentor@latest

    COPY +sources/src /src

    WORKDIR /src/test/antithesis/workload
    COPY --dir ../../../pkg/client+client/client ../../../pkg/client
    RUN mkdir -p /workload_instrumented
    RUN mkdir -p /out/cmds

    RUN antithesis-go-instrumentor -assert_only .
    RUN go build -o /out/init ./bin/init

    FOR file IN $(ls bin/cmds)
        RUN go build -o /out/cmds/$file ./bin/cmds/$file
    END

    SAVE ARTIFACT /out

build:
    FROM --platform=linux/amd64 ubuntu:latest
    COPY (+compile/out/init) /init
    ENTRYPOINT ["/init"]

    COPY (+compile/out/cmds/*) /opt/antithesis/test/v1/main/

    ARG --required ANTITHESIS_REPOSITORY

    SAVE IMAGE --push --no-manifest-list ${ANTITHESIS_REPOSITORY}/workload:latest