linters-settings:
  dupl:
    threshold: 30
  funlen:
    lines: 150
    statements: 30
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  cyclop:
    max-complexity: 30
  gocyclo:
    min-complexity: 30
  goimports:
    local-prefixes: github.com/formancehq/payments
  govet:
    check-shadowing: true
  lll:
    line-length: 120
  nakedret:
    max-func-lines: 0
  tagliatelle:
    case:
      rules:
        json: goCamel
        yaml: goCamel
        bson: goCamel
  gomnd:
    ignored-numbers:
      - '2'
      - '5'
      - '10'
      - '100'
      - '64'
      - '256'
      - '512'
  varnamelen:
     ignore-names:
      - id
      - i
      - db
      - m
      - r
      - c
      - fn
      - w
      - h
      - to
      - fs

linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - maligned #deprecated
    - golint # deprecated
    - ifshort # deprecated
    - structcheck # deprecated
    - varcheck # deprecated
    - interfacer # deprecated
    - scopelint #deprecated
    - nosnakecase # deprecated
    - rowserrcheck # disabled due to generics
    - sqlclosecheck # disabled due to generics
    - structcheck # disabled due to generics
    - wastedassign # disabled due to generics
    - gci # conflicts with gofumpt
    - goimports # conflicts with gofumpt
    - testpackage # Disabled by design
    - wrapcheck # Disabled by design
    - exhaustivestruct # Disabled by design
    - exhaustruct # Disabled by design
    - exhaustive # Disabled by design
    - dupl # Disabled by design
    - godox # Disabled by design
    - lll # Disabled by design
    - funlen # Disabled by design
    - misspell # Disabled by design
    - ireturn # Disabled by design
    - wsl # Disabled by design
    - gocritic # TODO: FIX. Seems to have issues with generics
    - gocognit # TODO: FIX
    - goerr113 # TODO: FIX
    - noctx # TODO: FIX
    - contextcheck # TODO: FIX
    - containedctx # TODO: FIX

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goerr113
        - varnamelen

    - path: internal/app/migrations/
      linters:
        - gochecknoinits
        - varnamelen

    - linters:
      - nolintlint
      text: "should be written without leading space"

run:
  timeout: 5m
