---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: benchmark-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benchmark.formance.com
  resources:
  - benchmarks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benchmark.formance.com
  resources:
  - benchmarks/finalizers
  verbs:
  - update
- apiGroups:
  - benchmark.formance.com
  resources:
  - benchmarks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k6.io
  resources:
  - testruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
