---
volumes:
  postgres:
services:

  postgres:
    extends:
      file: ../../docker-compose.yml
      service: postgres

  redis:
    image: redis

  ledger:
    extends:
      file: ../../docker-compose.yml
      service: ledger
    deploy:
      replicas: 3
    depends_on:
    - postgres
    - redis
    image: golang:1.18-alpine
    entrypoint: go run main.go server start
    volumes:
    - ../..:/src
    ports: []
    working_dir: /src
    environment:
      CGO_ENABLED: 0
      NUMARY_DEBUG: "true"
      NUMARY_LOCK_STRATEGY: redis
      NUMARY_LOCK_STRATEGY_REDIS_URL: redis://redis:6379
      NUMARY_LOCK_STRATEGY_REDIS_DURATION: 60s # Default value
      NUMARY_LOCK_STRATEGY_REDIS_RETRY: 1s # Default value
      NUMARY_LOCK_STRATEGY_REDIS_TLS_ENABLED: false
      NUMARY_LOCK_STRATEGY_REDIS_TLS_INSECURE: false

  proxy:
    extends:
      file: ../../docker-compose.yml
      service: proxy

