// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type CreateSnapshotResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Snapshot created successfully
	SnapshotResponse *shared.SnapshotResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateSnapshotResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateSnapshotResponse) GetSnapshotResponse() *shared.SnapshotResponse {
	if o == nil {
		return nil
	}
	return o.SnapshotResponse
}

func (o *CreateSnapshotResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateSnapshotResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
