name: Setup Env
description: Setup Nix environment with Go caching
inputs:
  token:
    description: 'A Github PAT'
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: Configure git for private Formance modules
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        git config --global url."https://x-access-token:${GH_TOKEN}@github.com/formancehq/".insteadOf "https://github.com/formancehq/"
        echo "GOPRIVATE=github.com/formancehq/*" >> "$GITHUB_ENV"
    - name: Install Nix
      uses: cachix/install-nix-action@v31
    - name: go env
      id: go-env
      shell: bash
      run: |
        nix develop --command bash -c "go env | sed -E \"s/^([^=]+)='(.*)'\$/\1=\2/\"" >> "$GITHUB_OUTPUT"
    - uses: namespacelabs/nscloud-cache-action@v1
      with:
        path: |
          ${{ steps.go-env.outputs.GOCACHE }}
          ${{ steps.go-env.outputs.GOMODCACHE }}
          ~/.cache/golangci-lint
