name: Setup Env
description: Setup Nix environment with Go caching
inputs:
  token:
    description: 'A Github PAT'
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v31
    - name: go env
      id: go-env
      shell: bash
      run: |
        nix develop --command bash -c "go env | sed -E \"s/^([^=]+)='(.*)'\$/\1=\2/\"" >> "$GITHUB_OUTPUT"
    - uses: actions/cache@v4
      with:
        path: |
          ${{ steps.go-env.outputs.GOCACHE }}
          ${{ steps.go-env.outputs.GOMODCACHE }}
          ~/.cache/golangci-lint
        key: ${{ runner.os }}-${{ github.job }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.job }}-go-
