apiVersion: ledger.formance.com/v1alpha1
kind: LedgerAgent
metadata:
  name: payment-service
  namespace: default
spec:
  scopes:
    - write
    - read
  selector:
    matchLabels:
      env: production
