apiVersion: ledger.formance.com/v1alpha1
kind: Cluster
metadata:
  name: my-cluster
spec:
  replicas: 3
  image:
    repository: ghcr.io/formancehq/ledger
    tag: latest
  clusterID: default
  podAntiAffinity:
    enabled: true
    type: hard
    topologyKey: kubernetes.io/hostname
  pebble:
    memTableSize: 256Mi
    cacheSize: 1Gi
  persistence:
    wal:
      size: 5Gi
    data:
      size: 10Gi
  resources:
    requests:
      cpu: "2000m"
      memory: 4Gi
    limits:
      cpu: "4000m"
      memory: 4Gi
  goMemLimitRatio: 90
