linters-settings:
  tagliatelle:
    case:
      rules:
        json: goCamel

issues:
  exclude-rules:
  - path: '(.+)_test\.go'
    linters:
    - bodyclose

linters:
  enable-all: true
  disable:
    - wrapcheck
    - varnamelen
    - nlreturn
    - ireturn
    - gochecknoglobals
    - forcetypeassert
    - exhaustivestruct
    - exhaustruct
    - wsl
    - gosec
    - gochecknoinits
    - funlen
    - testpackage
    - lll
    - dupl
    - nosnakecase
    - nestif
    - goerr113
    # Deprecated linters
    - ifshort
    - varcheck
    - maligned
    - scopelint
    - deadcode
    - structcheck
    - golint
    - interfacer
    # Disabled because of generics
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
run:
  timeout: 5m
