// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.5
// source: proto/ledger.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LedgerSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ledger        string                 `protobuf:"bytes,1,opt,name=ledger,proto3" json:"ledger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerSnapshotRequest) Reset() {
	*x = LedgerSnapshotRequest{}
	mi := &file_proto_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerSnapshotRequest) ProtoMessage() {}

func (x *LedgerSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerSnapshotRequest.ProtoReflect.Descriptor instead.
func (*LedgerSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *LedgerSnapshotRequest) GetLedger() string {
	if x != nil {
		return x.Ledger
	}
	return ""
}

type LedgerSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerSnapshotResponse) Reset() {
	*x = LedgerSnapshotResponse{}
	mi := &file_proto_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerSnapshotResponse) ProtoMessage() {}

func (x *LedgerSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerSnapshotResponse.ProtoReflect.Descriptor instead.
func (*LedgerSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *LedgerSnapshotResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Script struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plain         string                 `protobuf:"bytes,1,opt,name=plain,proto3" json:"plain,omitempty"`
	Vars          map[string]string      `protobuf:"bytes,2,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Script) Reset() {
	*x = Script{}
	mi := &file_proto_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Script) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Script) ProtoMessage() {}

func (x *Script) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Script.ProtoReflect.Descriptor instead.
func (*Script) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *Script) GetPlain() string {
	if x != nil {
		return x.Plain
	}
	return ""
}

func (x *Script) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

type CreateTransactionRequest struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	Ledger          string                      `protobuf:"bytes,1,opt,name=ledger,proto3" json:"ledger,omitempty"`
	AccountMetadata map[string]*structpb.Struct `protobuf:"bytes,2,rep,name=account_metadata,json=accountMetadata,proto3" json:"account_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp       *timestamppb.Timestamp      `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata        *structpb.Struct            `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Reference       string                      `protobuf:"bytes,5,opt,name=reference,proto3" json:"reference,omitempty"`
	Postings        []*Posting                  `protobuf:"bytes,6,rep,name=postings,proto3" json:"postings,omitempty"`
	DryRun          bool                        `protobuf:"varint,7,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	IdempotencyKey  string                      `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Script          *Script                     `protobuf:"bytes,9,opt,name=script,proto3" json:"script,omitempty"`
	Runtime         string                      `protobuf:"bytes,10,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_proto_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTransactionRequest) GetLedger() string {
	if x != nil {
		return x.Ledger
	}
	return ""
}

func (x *CreateTransactionRequest) GetAccountMetadata() map[string]*structpb.Struct {
	if x != nil {
		return x.AccountMetadata
	}
	return nil
}

func (x *CreateTransactionRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CreateTransactionRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateTransactionRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *CreateTransactionRequest) GetPostings() []*Posting {
	if x != nil {
		return x.Postings
	}
	return nil
}

func (x *CreateTransactionRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *CreateTransactionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateTransactionRequest) GetScript() *Script {
	if x != nil {
		return x.Script
	}
	return nil
}

func (x *CreateTransactionRequest) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

type CreateTransactionResponse struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	Transaction     *Transaction                `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	AccountMetadata map[string]*structpb.Struct `protobuf:"bytes,2,rep,name=account_metadata,json=accountMetadata,proto3" json:"account_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_proto_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *CreateTransactionResponse) GetAccountMetadata() map[string]*structpb.Struct {
	if x != nil {
		return x.AccountMetadata
	}
	return nil
}

type SaveAccountMetadataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ledger         string                 `protobuf:"bytes,1,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Metadata       *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	DryRun         bool                   `protobuf:"varint,4,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SaveAccountMetadataRequest) Reset() {
	*x = SaveAccountMetadataRequest{}
	mi := &file_proto_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAccountMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAccountMetadataRequest) ProtoMessage() {}

func (x *SaveAccountMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAccountMetadataRequest.ProtoReflect.Descriptor instead.
func (*SaveAccountMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *SaveAccountMetadataRequest) GetLedger() string {
	if x != nil {
		return x.Ledger
	}
	return ""
}

func (x *SaveAccountMetadataRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SaveAccountMetadataRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SaveAccountMetadataRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *SaveAccountMetadataRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type SaveAccountMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           *Log                   `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveAccountMetadataResponse) Reset() {
	*x = SaveAccountMetadataResponse{}
	mi := &file_proto_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveAccountMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAccountMetadataResponse) ProtoMessage() {}

func (x *SaveAccountMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAccountMetadataResponse.ProtoReflect.Descriptor instead.
func (*SaveAccountMetadataResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *SaveAccountMetadataResponse) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

type StreamLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ledger        string                 `protobuf:"bytes,1,opt,name=ledger,proto3" json:"ledger,omitempty"`
	FromSequence  uint64                 `protobuf:"varint,2,opt,name=from_sequence,json=fromSequence,proto3" json:"from_sequence,omitempty"` // Optional: start streaming from this sequence number (inclusive). If 0, streams from the beginning
	ToSequence    uint64                 `protobuf:"varint,3,opt,name=to_sequence,json=toSequence,proto3" json:"to_sequence,omitempty"`       // Optional: stop streaming at this sequence number (inclusive). If 0, streams until the end
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_proto_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *StreamLogsRequest) GetLedger() string {
	if x != nil {
		return x.Ledger
	}
	return ""
}

func (x *StreamLogsRequest) GetFromSequence() uint64 {
	if x != nil {
		return x.FromSequence
	}
	return 0
}

func (x *StreamLogsRequest) GetToSequence() uint64 {
	if x != nil {
		return x.ToSequence
	}
	return 0
}

type StreamLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           *Log                   `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsResponse) Reset() {
	*x = StreamLogsResponse{}
	mi := &file_proto_ledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsResponse) ProtoMessage() {}

func (x *StreamLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsResponse.ProtoReflect.Descriptor instead.
func (*StreamLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{8}
}

func (x *StreamLogsResponse) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

type Log struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"` // LogType enum value
	Data            *LogPayload            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Date            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	IdempotencyHash string                 `protobuf:"bytes,5,opt,name=idempotency_hash,json=idempotencyHash,proto3" json:"idempotency_hash,omitempty"`
	Id              uint64                 `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`             // Optional log ID
	Sequence        uint64                 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"` // Global sequence number
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_proto_ledger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{9}
}

func (x *Log) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Log) GetData() *LogPayload {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Log) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Log) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Log) GetIdempotencyHash() string {
	if x != nil {
		return x.IdempotencyHash
	}
	return ""
}

func (x *Log) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Log) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type LogPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*LogPayload_CreatedTransaction
	//	*LogPayload_RevertedTransaction
	//	*LogPayload_SavedMetadata
	//	*LogPayload_DeletedMetadata
	Payload       isLogPayload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogPayload) Reset() {
	*x = LogPayload{}
	mi := &file_proto_ledger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogPayload) ProtoMessage() {}

func (x *LogPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogPayload.ProtoReflect.Descriptor instead.
func (*LogPayload) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{10}
}

func (x *LogPayload) GetPayload() isLogPayload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LogPayload) GetCreatedTransaction() *CreatedTransaction {
	if x != nil {
		if x, ok := x.Payload.(*LogPayload_CreatedTransaction); ok {
			return x.CreatedTransaction
		}
	}
	return nil
}

func (x *LogPayload) GetRevertedTransaction() *RevertedTransaction {
	if x != nil {
		if x, ok := x.Payload.(*LogPayload_RevertedTransaction); ok {
			return x.RevertedTransaction
		}
	}
	return nil
}

func (x *LogPayload) GetSavedMetadata() *SavedMetadata {
	if x != nil {
		if x, ok := x.Payload.(*LogPayload_SavedMetadata); ok {
			return x.SavedMetadata
		}
	}
	return nil
}

func (x *LogPayload) GetDeletedMetadata() *DeletedMetadata {
	if x != nil {
		if x, ok := x.Payload.(*LogPayload_DeletedMetadata); ok {
			return x.DeletedMetadata
		}
	}
	return nil
}

type isLogPayload_Payload interface {
	isLogPayload_Payload()
}

type LogPayload_CreatedTransaction struct {
	CreatedTransaction *CreatedTransaction `protobuf:"bytes,1,opt,name=created_transaction,json=createdTransaction,proto3,oneof"`
}

type LogPayload_RevertedTransaction struct {
	RevertedTransaction *RevertedTransaction `protobuf:"bytes,2,opt,name=reverted_transaction,json=revertedTransaction,proto3,oneof"`
}

type LogPayload_SavedMetadata struct {
	SavedMetadata *SavedMetadata `protobuf:"bytes,3,opt,name=saved_metadata,json=savedMetadata,proto3,oneof"`
}

type LogPayload_DeletedMetadata struct {
	DeletedMetadata *DeletedMetadata `protobuf:"bytes,4,opt,name=deleted_metadata,json=deletedMetadata,proto3,oneof"`
}

func (*LogPayload_CreatedTransaction) isLogPayload_Payload() {}

func (*LogPayload_RevertedTransaction) isLogPayload_Payload() {}

func (*LogPayload_SavedMetadata) isLogPayload_Payload() {}

func (*LogPayload_DeletedMetadata) isLogPayload_Payload() {}

type CreatedTransaction struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	Transaction     *Transaction                `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	AccountMetadata map[string]*structpb.Struct `protobuf:"bytes,2,rep,name=account_metadata,json=accountMetadata,proto3" json:"account_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatedTransaction) Reset() {
	*x = CreatedTransaction{}
	mi := &file_proto_ledger_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedTransaction) ProtoMessage() {}

func (x *CreatedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedTransaction.ProtoReflect.Descriptor instead.
func (*CreatedTransaction) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{11}
}

func (x *CreatedTransaction) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *CreatedTransaction) GetAccountMetadata() map[string]*structpb.Struct {
	if x != nil {
		return x.AccountMetadata
	}
	return nil
}

type RevertedTransaction struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RevertedTransaction *Transaction           `protobuf:"bytes,1,opt,name=reverted_transaction,json=revertedTransaction,proto3" json:"reverted_transaction,omitempty"`
	RevertTransaction   *Transaction           `protobuf:"bytes,2,opt,name=revert_transaction,json=revertTransaction,proto3" json:"revert_transaction,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RevertedTransaction) Reset() {
	*x = RevertedTransaction{}
	mi := &file_proto_ledger_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevertedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertedTransaction) ProtoMessage() {}

func (x *RevertedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertedTransaction.ProtoReflect.Descriptor instead.
func (*RevertedTransaction) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{12}
}

func (x *RevertedTransaction) GetRevertedTransaction() *Transaction {
	if x != nil {
		return x.RevertedTransaction
	}
	return nil
}

func (x *RevertedTransaction) GetRevertTransaction() *Transaction {
	if x != nil {
		return x.RevertTransaction
	}
	return nil
}

type SavedMetadata struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TargetType string                 `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // "ACCOUNT" or "TRANSACTION"
	// Types that are valid to be assigned to TargetId:
	//
	//	*SavedMetadata_AccountId
	//	*SavedMetadata_TransactionId
	TargetId      isSavedMetadata_TargetId `protobuf_oneof:"target_id"`
	Metadata      *structpb.Struct         `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavedMetadata) Reset() {
	*x = SavedMetadata{}
	mi := &file_proto_ledger_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavedMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavedMetadata) ProtoMessage() {}

func (x *SavedMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavedMetadata.ProtoReflect.Descriptor instead.
func (*SavedMetadata) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{13}
}

func (x *SavedMetadata) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *SavedMetadata) GetTargetId() isSavedMetadata_TargetId {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *SavedMetadata) GetAccountId() string {
	if x != nil {
		if x, ok := x.TargetId.(*SavedMetadata_AccountId); ok {
			return x.AccountId
		}
	}
	return ""
}

func (x *SavedMetadata) GetTransactionId() uint64 {
	if x != nil {
		if x, ok := x.TargetId.(*SavedMetadata_TransactionId); ok {
			return x.TransactionId
		}
	}
	return 0
}

func (x *SavedMetadata) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isSavedMetadata_TargetId interface {
	isSavedMetadata_TargetId()
}

type SavedMetadata_AccountId struct {
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3,oneof"` // Account address (for ACCOUNT type)
}

type SavedMetadata_TransactionId struct {
	TransactionId uint64 `protobuf:"varint,3,opt,name=transaction_id,json=transactionId,proto3,oneof"` // Transaction ID (for TRANSACTION type)
}

func (*SavedMetadata_AccountId) isSavedMetadata_TargetId() {}

func (*SavedMetadata_TransactionId) isSavedMetadata_TargetId() {}

type DeletedMetadata struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TargetType string                 `protobuf:"bytes,1,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // "ACCOUNT" or "TRANSACTION"
	// Types that are valid to be assigned to TargetId:
	//
	//	*DeletedMetadata_AccountId
	//	*DeletedMetadata_TransactionId
	TargetId      isDeletedMetadata_TargetId `protobuf_oneof:"target_id"`
	Key           string                     `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"` // Metadata key to delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletedMetadata) Reset() {
	*x = DeletedMetadata{}
	mi := &file_proto_ledger_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletedMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletedMetadata) ProtoMessage() {}

func (x *DeletedMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletedMetadata.ProtoReflect.Descriptor instead.
func (*DeletedMetadata) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{14}
}

func (x *DeletedMetadata) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *DeletedMetadata) GetTargetId() isDeletedMetadata_TargetId {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *DeletedMetadata) GetAccountId() string {
	if x != nil {
		if x, ok := x.TargetId.(*DeletedMetadata_AccountId); ok {
			return x.AccountId
		}
	}
	return ""
}

func (x *DeletedMetadata) GetTransactionId() uint64 {
	if x != nil {
		if x, ok := x.TargetId.(*DeletedMetadata_TransactionId); ok {
			return x.TransactionId
		}
	}
	return 0
}

func (x *DeletedMetadata) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type isDeletedMetadata_TargetId interface {
	isDeletedMetadata_TargetId()
}

type DeletedMetadata_AccountId struct {
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3,oneof"` // Account address (for ACCOUNT type)
}

type DeletedMetadata_TransactionId struct {
	TransactionId uint64 `protobuf:"varint,3,opt,name=transaction_id,json=transactionId,proto3,oneof"` // Transaction ID (for TRANSACTION type)
}

func (*DeletedMetadata_AccountId) isDeletedMetadata_TargetId() {}

func (*DeletedMetadata_TransactionId) isDeletedMetadata_TargetId() {}

var File_proto_ledger_proto protoreflect.FileDescriptor

const file_proto_ledger_proto_rawDesc = "" +
	"\n" +
	"\x12proto/ledger.proto\x12\x06ledger\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12proto/common.proto\"/\n" +
	"\x15LedgerSnapshotRequest\x12\x16\n" +
	"\x06ledger\x18\x01 \x01(\tR\x06ledger\"2\n" +
	"\x16LedgerSnapshotResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x85\x01\n" +
	"\x06Script\x12\x14\n" +
	"\x05plain\x18\x01 \x01(\tR\x05plain\x12,\n" +
	"\x04vars\x18\x02 \x03(\v2\x18.ledger.Script.VarsEntryR\x04vars\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x04\n" +
	"\x18CreateTransactionRequest\x12\x16\n" +
	"\x06ledger\x18\x01 \x01(\tR\x06ledger\x12`\n" +
	"\x10account_metadata\x18\x02 \x03(\v25.ledger.CreateTransactionRequest.AccountMetadataEntryR\x0faccountMetadata\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x1c\n" +
	"\treference\x18\x05 \x01(\tR\treference\x12+\n" +
	"\bpostings\x18\x06 \x03(\v2\x0f.common.PostingR\bpostings\x12\x17\n" +
	"\adry_run\x18\a \x01(\bR\x06dryRun\x12'\n" +
	"\x0fidempotency_key\x18\b \x01(\tR\x0eidempotencyKey\x12&\n" +
	"\x06script\x18\t \x01(\v2\x0e.ledger.ScriptR\x06script\x12\x18\n" +
	"\aruntime\x18\n" +
	" \x01(\tR\aruntime\x1a[\n" +
	"\x14AccountMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value:\x028\x01\"\x92\x02\n" +
	"\x19CreateTransactionResponse\x125\n" +
	"\vtransaction\x18\x01 \x01(\v2\x13.common.TransactionR\vtransaction\x12a\n" +
	"\x10account_metadata\x18\x02 \x03(\v26.ledger.CreateTransactionResponse.AccountMetadataEntryR\x0faccountMetadata\x1a[\n" +
	"\x14AccountMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value:\x028\x01\"\xc5\x01\n" +
	"\x1aSaveAccountMetadataRequest\x12\x16\n" +
	"\x06ledger\x18\x01 \x01(\tR\x06ledger\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x17\n" +
	"\adry_run\x18\x04 \x01(\bR\x06dryRun\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"<\n" +
	"\x1bSaveAccountMetadataResponse\x12\x1d\n" +
	"\x03log\x18\x01 \x01(\v2\v.ledger.LogR\x03log\"q\n" +
	"\x11StreamLogsRequest\x12\x16\n" +
	"\x06ledger\x18\x01 \x01(\tR\x06ledger\x12#\n" +
	"\rfrom_sequence\x18\x02 \x01(\x04R\ffromSequence\x12\x1f\n" +
	"\vto_sequence\x18\x03 \x01(\x04R\n" +
	"toSequence\"3\n" +
	"\x12StreamLogsResponse\x12\x1d\n" +
	"\x03log\x18\x01 \x01(\v2\v.ledger.LogR\x03log\"\xf1\x01\n" +
	"\x03Log\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12&\n" +
	"\x04data\x18\x02 \x01(\v2\x12.ledger.LogPayloadR\x04data\x12.\n" +
	"\x04date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12)\n" +
	"\x10idempotency_hash\x18\x05 \x01(\tR\x0fidempotencyHash\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\x04R\x02id\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x04R\bsequence\"\xbe\x02\n" +
	"\n" +
	"LogPayload\x12M\n" +
	"\x13created_transaction\x18\x01 \x01(\v2\x1a.ledger.CreatedTransactionH\x00R\x12createdTransaction\x12P\n" +
	"\x14reverted_transaction\x18\x02 \x01(\v2\x1b.ledger.RevertedTransactionH\x00R\x13revertedTransaction\x12>\n" +
	"\x0esaved_metadata\x18\x03 \x01(\v2\x15.ledger.SavedMetadataH\x00R\rsavedMetadata\x12D\n" +
	"\x10deleted_metadata\x18\x04 \x01(\v2\x17.ledger.DeletedMetadataH\x00R\x0fdeletedMetadataB\t\n" +
	"\apayload\"\x84\x02\n" +
	"\x12CreatedTransaction\x125\n" +
	"\vtransaction\x18\x01 \x01(\v2\x13.common.TransactionR\vtransaction\x12Z\n" +
	"\x10account_metadata\x18\x02 \x03(\v2/.ledger.CreatedTransaction.AccountMetadataEntryR\x0faccountMetadata\x1a[\n" +
	"\x14AccountMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value:\x028\x01\"\xa1\x01\n" +
	"\x13RevertedTransaction\x12F\n" +
	"\x14reverted_transaction\x18\x01 \x01(\v2\x13.common.TransactionR\x13revertedTransaction\x12B\n" +
	"\x12revert_transaction\x18\x02 \x01(\v2\x13.common.TransactionR\x11revertTransaction\"\xbc\x01\n" +
	"\rSavedMetadata\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x12\x1f\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tH\x00R\taccountId\x12'\n" +
	"\x0etransaction_id\x18\x03 \x01(\x04H\x00R\rtransactionId\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadataB\v\n" +
	"\ttarget_id\"\x9b\x01\n" +
	"\x0fDeletedMetadata\x12\x1f\n" +
	"\vtarget_type\x18\x01 \x01(\tR\n" +
	"targetType\x12\x1f\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tH\x00R\taccountId\x12'\n" +
	"\x0etransaction_id\x18\x03 \x01(\x04H\x00R\rtransactionId\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03keyB\v\n" +
	"\ttarget_id2\xdb\x02\n" +
	"\rLedgerService\x12I\n" +
	"\bSnapshot\x12\x1d.ledger.LedgerSnapshotRequest\x1a\x1e.ledger.LedgerSnapshotResponse\x12X\n" +
	"\x11CreateTransaction\x12 .ledger.CreateTransactionRequest\x1a!.ledger.CreateTransactionResponse\x12^\n" +
	"\x13SaveAccountMetadata\x12\".ledger.SaveAccountMetadataRequest\x1a#.ledger.SaveAccountMetadataResponse\x12E\n" +
	"\n" +
	"StreamLogs\x12\x19.ledger.StreamLogsRequest\x1a\x1a.ledger.StreamLogsResponse0\x01B6Z4github.com/formancehq/ledger-v3-poc/internal/serviceb\x06proto3"

var (
	file_proto_ledger_proto_rawDescOnce sync.Once
	file_proto_ledger_proto_rawDescData []byte
)

func file_proto_ledger_proto_rawDescGZIP() []byte {
	file_proto_ledger_proto_rawDescOnce.Do(func() {
		file_proto_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ledger_proto_rawDesc), len(file_proto_ledger_proto_rawDesc)))
	})
	return file_proto_ledger_proto_rawDescData
}

var file_proto_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_ledger_proto_goTypes = []any{
	(*LedgerSnapshotRequest)(nil),       // 0: ledger.LedgerSnapshotRequest
	(*LedgerSnapshotResponse)(nil),      // 1: ledger.LedgerSnapshotResponse
	(*Script)(nil),                      // 2: ledger.Script
	(*CreateTransactionRequest)(nil),    // 3: ledger.CreateTransactionRequest
	(*CreateTransactionResponse)(nil),   // 4: ledger.CreateTransactionResponse
	(*SaveAccountMetadataRequest)(nil),  // 5: ledger.SaveAccountMetadataRequest
	(*SaveAccountMetadataResponse)(nil), // 6: ledger.SaveAccountMetadataResponse
	(*StreamLogsRequest)(nil),           // 7: ledger.StreamLogsRequest
	(*StreamLogsResponse)(nil),          // 8: ledger.StreamLogsResponse
	(*Log)(nil),                         // 9: ledger.Log
	(*LogPayload)(nil),                  // 10: ledger.LogPayload
	(*CreatedTransaction)(nil),          // 11: ledger.CreatedTransaction
	(*RevertedTransaction)(nil),         // 12: ledger.RevertedTransaction
	(*SavedMetadata)(nil),               // 13: ledger.SavedMetadata
	(*DeletedMetadata)(nil),             // 14: ledger.DeletedMetadata
	nil,                                 // 15: ledger.Script.VarsEntry
	nil,                                 // 16: ledger.CreateTransactionRequest.AccountMetadataEntry
	nil,                                 // 17: ledger.CreateTransactionResponse.AccountMetadataEntry
	nil,                                 // 18: ledger.CreatedTransaction.AccountMetadataEntry
	(*timestamppb.Timestamp)(nil),       // 19: google.protobuf.Timestamp
	(*structpb.Struct)(nil),             // 20: google.protobuf.Struct
	(*Posting)(nil),                     // 21: common.Posting
	(*Transaction)(nil),                 // 22: common.Transaction
}
var file_proto_ledger_proto_depIdxs = []int32{
	15, // 0: ledger.Script.vars:type_name -> ledger.Script.VarsEntry
	16, // 1: ledger.CreateTransactionRequest.account_metadata:type_name -> ledger.CreateTransactionRequest.AccountMetadataEntry
	19, // 2: ledger.CreateTransactionRequest.timestamp:type_name -> google.protobuf.Timestamp
	20, // 3: ledger.CreateTransactionRequest.metadata:type_name -> google.protobuf.Struct
	21, // 4: ledger.CreateTransactionRequest.postings:type_name -> common.Posting
	2,  // 5: ledger.CreateTransactionRequest.script:type_name -> ledger.Script
	22, // 6: ledger.CreateTransactionResponse.transaction:type_name -> common.Transaction
	17, // 7: ledger.CreateTransactionResponse.account_metadata:type_name -> ledger.CreateTransactionResponse.AccountMetadataEntry
	20, // 8: ledger.SaveAccountMetadataRequest.metadata:type_name -> google.protobuf.Struct
	9,  // 9: ledger.SaveAccountMetadataResponse.log:type_name -> ledger.Log
	9,  // 10: ledger.StreamLogsResponse.log:type_name -> ledger.Log
	10, // 11: ledger.Log.data:type_name -> ledger.LogPayload
	19, // 12: ledger.Log.date:type_name -> google.protobuf.Timestamp
	11, // 13: ledger.LogPayload.created_transaction:type_name -> ledger.CreatedTransaction
	12, // 14: ledger.LogPayload.reverted_transaction:type_name -> ledger.RevertedTransaction
	13, // 15: ledger.LogPayload.saved_metadata:type_name -> ledger.SavedMetadata
	14, // 16: ledger.LogPayload.deleted_metadata:type_name -> ledger.DeletedMetadata
	22, // 17: ledger.CreatedTransaction.transaction:type_name -> common.Transaction
	18, // 18: ledger.CreatedTransaction.account_metadata:type_name -> ledger.CreatedTransaction.AccountMetadataEntry
	22, // 19: ledger.RevertedTransaction.reverted_transaction:type_name -> common.Transaction
	22, // 20: ledger.RevertedTransaction.revert_transaction:type_name -> common.Transaction
	20, // 21: ledger.SavedMetadata.metadata:type_name -> google.protobuf.Struct
	20, // 22: ledger.CreateTransactionRequest.AccountMetadataEntry.value:type_name -> google.protobuf.Struct
	20, // 23: ledger.CreateTransactionResponse.AccountMetadataEntry.value:type_name -> google.protobuf.Struct
	20, // 24: ledger.CreatedTransaction.AccountMetadataEntry.value:type_name -> google.protobuf.Struct
	0,  // 25: ledger.LedgerService.Snapshot:input_type -> ledger.LedgerSnapshotRequest
	3,  // 26: ledger.LedgerService.CreateTransaction:input_type -> ledger.CreateTransactionRequest
	5,  // 27: ledger.LedgerService.SaveAccountMetadata:input_type -> ledger.SaveAccountMetadataRequest
	7,  // 28: ledger.LedgerService.StreamLogs:input_type -> ledger.StreamLogsRequest
	1,  // 29: ledger.LedgerService.Snapshot:output_type -> ledger.LedgerSnapshotResponse
	4,  // 30: ledger.LedgerService.CreateTransaction:output_type -> ledger.CreateTransactionResponse
	6,  // 31: ledger.LedgerService.SaveAccountMetadata:output_type -> ledger.SaveAccountMetadataResponse
	8,  // 32: ledger.LedgerService.StreamLogs:output_type -> ledger.StreamLogsResponse
	29, // [29:33] is the sub-list for method output_type
	25, // [25:29] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_proto_ledger_proto_init() }
func file_proto_ledger_proto_init() {
	if File_proto_ledger_proto != nil {
		return
	}
	file_proto_common_proto_init()
	file_proto_ledger_proto_msgTypes[10].OneofWrappers = []any{
		(*LogPayload_CreatedTransaction)(nil),
		(*LogPayload_RevertedTransaction)(nil),
		(*LogPayload_SavedMetadata)(nil),
		(*LogPayload_DeletedMetadata)(nil),
	}
	file_proto_ledger_proto_msgTypes[13].OneofWrappers = []any{
		(*SavedMetadata_AccountId)(nil),
		(*SavedMetadata_TransactionId)(nil),
	}
	file_proto_ledger_proto_msgTypes[14].OneofWrappers = []any{
		(*DeletedMetadata_AccountId)(nil),
		(*DeletedMetadata_TransactionId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ledger_proto_rawDesc), len(file_proto_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ledger_proto_goTypes,
		DependencyIndexes: file_proto_ledger_proto_depIdxs,
		MessageInfos:      file_proto_ledger_proto_msgTypes,
	}.Build()
	File_proto_ledger_proto = out.File
	file_proto_ledger_proto_goTypes = nil
	file_proto_ledger_proto_depIdxs = nil
}
