# https://taskfile.dev

version: '3'

vars:
  PKG: "./..."
  FAILFAST: "-failfast"
  TIMEOUT: "10m"
  RUN: ".*"
  VERBOSE: "false"

tasks:
  default:
    cmds:
      - task: lint
      - task: tests:local

  tests:
    cmds:
      - go test {{if eq .VERBOSE "true"}}-v{{end}} -coverpkg {{.PKG}} -coverprofile coverage.out -covermode atomic {{.PKG}}

  lint:
    cmds:
      - golangci-lint -v run --fix

  tests:local:
    cmds:
      - >
        go test {{if eq .VERBOSE "true"}}-v{{end}} {{.FAILFAST}} -coverpkg {{.PKG}}
        -coverprofile coverage.out -covermode atomic
        -run={{.RUN}} -timeout {{.TIMEOUT}} {{.PKG}} |
        sed ''/PASS/s//$(printf "\033[32mPASS\033[0m")/'' |
        sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/'' |
        sed ''/RUN/s//$(printf "\033[34mRUN\033[0m")/''
      - task: print:coverage

  print:coverage:
    cmds:
      - go tool cover -html=coverage.out -o coverage.html
      - cov-report ./coverage.out
      - echo "To open the html coverage file, use one of the following commands:"
      - echo "open coverage.html on mac"
      - echo "xdg-open coverage.html on linux"
    silent: true
