// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: audit.proto

package auditpb

import (
	commonpb "github.com/formancehq/ledger/v3/internal/proto/commonpb"
	signaturepb "github.com/formancehq/ledger/v3/internal/proto/signaturepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuditEntry represents a single audit trail entry for a proposal.
// Each proposal (success or failure) generates exactly one audit entry.
// Per-order details are stored as separate AuditItem entries in Pebble
// (zone 0x04, sub 0x03) and populated on GetAuditEntry responses.
type AuditEntry struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Sequence   uint64                 `protobuf:"fixed64,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Timestamp  *commonpb.Timestamp    `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ProposalId uint64                 `protobuf:"fixed64,3,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*AuditEntry_Success
	//	*AuditEntry_Failure
	Outcome isAuditEntry_Outcome `protobuf_oneof:"outcome"`
	// Number of orders in the proposal (allows compact display without loading items).
	OrderCount uint32 `protobuf:"varint,6,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	// Per-order detail lines. Populated by GetAuditEntry, empty on ListAuditEntries.
	Items []*AuditItem `protobuf:"bytes,7,rep,name=items,proto3" json:"items,omitempty"`
	// Distinct ledger names targeted by orders in this proposal.
	// Used for efficient filtering without loading items.
	Ledgers []string `protobuf:"bytes,8,rep,name=ledgers,proto3" json:"ledgers,omitempty"`
	// Batch-level integrity hash chaining audit entries.
	// Formula: H(key, header_payload || concat(per_item_payload) ||
	//
	//	previous_audit_hash)
	//
	// where:
	//   - `key` is derived from the immutable ClusterID via domain-separated BLAKE3
	//   - `header_payload` is the canonical binary encoding of EVERY other field
	//     of this AuditEntry (sequence, timestamp, proposal_id, outcome,
	//     order_count, ledgers, hash_version, caller_snapshot), rebuilt by the
	//     verifier at check time from the stored fields via
	//     state.BuildHashedHeaderPayload — never persisted separately, so the
	//     typed fields ARE the source of truth
	//   - `per_item_payload` is the canonical binary encoding of each AuditItem
	//     (order_index, log_sequence, serialized_order), rebuilt the same way
	//     via state.BuildPerItemPayload
	//   - `previous_audit_hash` is `hash` of the predecessor entry, or empty for
	//     the first entry
	//
	// Same formula for success and failure entries. The hash binds every field
	// of AuditEntry and AuditItem except `hash` itself. Tampering with any
	// other field is detected by checker.verifyAuditHashChain.
	Hash []byte `protobuf:"bytes,9,opt,name=hash,proto3" json:"hash,omitempty"`
	// Hash algorithm version (matches common.HashAlgorithm enum).
	HashVersion uint32 `protobuf:"varint,10,opt,name=hash_version,json=hashVersion,proto3" json:"hash_version,omitempty"`
	// Admission-time auth snapshot: caller identification + the
	// authorization granted at admission. Nil when auth is disabled or
	// for system-initiated proposals.
	CallerSnapshot *commonpb.CallerSnapshot `protobuf:"bytes,12,opt,name=caller_snapshot,json=callerSnapshot,proto3" json:"caller_snapshot,omitempty"`
	// Batch identity, bound into the hash chain (header_payload) so it is
	// tamper-evident. idempotency is the batch dedup key; signature is the
	// client's proof over the whole ApplyBatch (nil for unsigned batches).
	// This is the authoritative, chain-verified home for batch non-repudiation;
	// the AppliedProposal projection carries a copy of the idempotency key for
	// event consumers, which the checker verifies against this entry.
	Idempotency   *commonpb.Idempotency         `protobuf:"bytes,13,opt,name=idempotency,proto3" json:"idempotency,omitempty"`
	Signature     *signaturepb.SignedApplyBatch `protobuf:"bytes,14,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEntry) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *AuditEntry) GetTimestamp() *commonpb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AuditEntry) GetProposalId() uint64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *AuditEntry) GetOutcome() isAuditEntry_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *AuditEntry) GetSuccess() *AuditSuccess {
	if x != nil {
		if x, ok := x.Outcome.(*AuditEntry_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *AuditEntry) GetFailure() *AuditFailure {
	if x != nil {
		if x, ok := x.Outcome.(*AuditEntry_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

func (x *AuditEntry) GetOrderCount() uint32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *AuditEntry) GetItems() []*AuditItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *AuditEntry) GetLedgers() []string {
	if x != nil {
		return x.Ledgers
	}
	return nil
}

func (x *AuditEntry) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *AuditEntry) GetHashVersion() uint32 {
	if x != nil {
		return x.HashVersion
	}
	return 0
}

func (x *AuditEntry) GetCallerSnapshot() *commonpb.CallerSnapshot {
	if x != nil {
		return x.CallerSnapshot
	}
	return nil
}

func (x *AuditEntry) GetIdempotency() *commonpb.Idempotency {
	if x != nil {
		return x.Idempotency
	}
	return nil
}

func (x *AuditEntry) GetSignature() *signaturepb.SignedApplyBatch {
	if x != nil {
		return x.Signature
	}
	return nil
}

type isAuditEntry_Outcome interface {
	isAuditEntry_Outcome()
}

type AuditEntry_Success struct {
	Success *AuditSuccess `protobuf:"bytes,4,opt,name=success,proto3,oneof"`
}

type AuditEntry_Failure struct {
	Failure *AuditFailure `protobuf:"bytes,5,opt,name=failure,proto3,oneof"`
}

func (*AuditEntry_Success) isAuditEntry_Outcome() {}

func (*AuditEntry_Failure) isAuditEntry_Outcome() {}

// AuditItem represents one order within a proposal, stored separately from the
// AuditEntry header. Pebble key: [ZoneCold][SubColdAuditItem][audit_seq BE 8][order_idx BE 4].
type AuditItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Zero-based position of this order within the proposal.
	OrderIndex uint32 `protobuf:"varint,1,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	// Deterministic serialized bytes of the order at apply time. The audit
	// hash chain on AuditEntry.hash is computed over the concatenation of
	// these bytes (in order_index order) so verification never re-marshals
	// an Order proto. This decouples the hash chain from the Order schema
	// and the vtprotobuf marshaller version. Field 2 previously held
	// `raft.Order order`; the wire format is identical (length-delimited,
	// bytes-equal) so the swap is on-wire compatible with entries persisted
	// before the change.
	SerializedOrder []byte `protobuf:"bytes,2,opt,name=serialized_order,json=serializedOrder,proto3" json:"serialized_order,omitempty"`
	// Sequence of the log produced by this order. Zero if the order was
	// an idempotent replay or if the proposal failed.
	LogSequence   uint64 `protobuf:"fixed64,3,opt,name=log_sequence,json=logSequence,proto3" json:"log_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditItem) Reset() {
	*x = AuditItem{}
	mi := &file_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditItem) ProtoMessage() {}

func (x *AuditItem) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditItem.ProtoReflect.Descriptor instead.
func (*AuditItem) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{1}
}

func (x *AuditItem) GetOrderIndex() uint32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *AuditItem) GetSerializedOrder() []byte {
	if x != nil {
		return x.SerializedOrder
	}
	return nil
}

func (x *AuditItem) GetLogSequence() uint64 {
	if x != nil {
		return x.LogSequence
	}
	return 0
}

// AuditSuccess records the log sequence range created by a successful proposal.
// Batch-level side effects (transient accounts, purged ephemeral accounts) live
// in proposalpb.AppliedProposal and on each Log directly — the audit log keeps
// only the integrity-relevant outcome data.
type AuditSuccess struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contiguous log sequence range [min_log_sequence, max_log_sequence] produced
	// by this proposal. Both are inclusive. When a proposal produces a single log,
	// min == max. When it produces no logs (all idempotent), both are 0.
	MinLogSequence uint64 `protobuf:"fixed64,1,opt,name=min_log_sequence,json=minLogSequence,proto3" json:"min_log_sequence,omitempty"`
	MaxLogSequence uint64 `protobuf:"fixed64,2,opt,name=max_log_sequence,json=maxLogSequence,proto3" json:"max_log_sequence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuditSuccess) Reset() {
	*x = AuditSuccess{}
	mi := &file_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditSuccess) ProtoMessage() {}

func (x *AuditSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditSuccess.ProtoReflect.Descriptor instead.
func (*AuditSuccess) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{2}
}

func (x *AuditSuccess) GetMinLogSequence() uint64 {
	if x != nil {
		return x.MinLogSequence
	}
	return 0
}

func (x *AuditSuccess) GetMaxLogSequence() uint64 {
	if x != nil {
		return x.MaxLogSequence
	}
	return 0
}

// AuditFailure records the reason and context for a failed proposal. reason is
// the typed, hash-chain-bound identifier; the numeric error kind is re-derived
// from it (domain.KindForReason) rather than stored, so it cannot drift from
// the reason and the idempotency failure projection is verifiable against it.
type AuditFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        commonpb.ErrorReason   `protobuf:"varint,1,opt,name=reason,proto3,enum=common.ErrorReason" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Context       map[string]string      `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditFailure) Reset() {
	*x = AuditFailure{}
	mi := &file_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditFailure) ProtoMessage() {}

func (x *AuditFailure) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditFailure.ProtoReflect.Descriptor instead.
func (*AuditFailure) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{3}
}

func (x *AuditFailure) GetReason() commonpb.ErrorReason {
	if x != nil {
		return x.Reason
	}
	return commonpb.ErrorReason(0)
}

func (x *AuditFailure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuditFailure) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

var File_audit_proto protoreflect.FileDescriptor

const file_audit_proto_rawDesc = "" +
	"\n" +
	"\vaudit.proto\x12\x05audit\x1a\fcommon.proto\x1a\x0fsignature.proto\"\xc2\x04\n" +
	"\n" +
	"AuditEntry\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x06R\bsequence\x12/\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x11.common.TimestampR\ttimestamp\x12\x1f\n" +
	"\vproposal_id\x18\x03 \x01(\x06R\n" +
	"proposalId\x12/\n" +
	"\asuccess\x18\x04 \x01(\v2\x13.audit.AuditSuccessH\x00R\asuccess\x12/\n" +
	"\afailure\x18\x05 \x01(\v2\x13.audit.AuditFailureH\x00R\afailure\x12\x1f\n" +
	"\vorder_count\x18\x06 \x01(\rR\n" +
	"orderCount\x12&\n" +
	"\x05items\x18\a \x03(\v2\x10.audit.AuditItemR\x05items\x12\x18\n" +
	"\aledgers\x18\b \x03(\tR\aledgers\x12\x12\n" +
	"\x04hash\x18\t \x01(\fR\x04hash\x12!\n" +
	"\fhash_version\x18\n" +
	" \x01(\rR\vhashVersion\x12?\n" +
	"\x0fcaller_snapshot\x18\f \x01(\v2\x16.common.CallerSnapshotR\x0ecallerSnapshot\x125\n" +
	"\vidempotency\x18\r \x01(\v2\x13.common.IdempotencyR\vidempotency\x129\n" +
	"\tsignature\x18\x0e \x01(\v2\x1b.signature.SignedApplyBatchR\tsignatureB\t\n" +
	"\aoutcomeJ\x04\b\v\x10\fR\x06caller\"\x81\x01\n" +
	"\tAuditItem\x12\x1f\n" +
	"\vorder_index\x18\x01 \x01(\rR\n" +
	"orderIndex\x12)\n" +
	"\x10serialized_order\x18\x02 \x01(\fR\x0fserializedOrder\x12!\n" +
	"\flog_sequence\x18\x03 \x01(\x06R\vlogSequenceR\x05order\"b\n" +
	"\fAuditSuccess\x12(\n" +
	"\x10min_log_sequence\x18\x01 \x01(\x06R\x0eminLogSequence\x12(\n" +
	"\x10max_log_sequence\x18\x02 \x01(\x06R\x0emaxLogSequence\"\xcd\x01\n" +
	"\fAuditFailure\x12+\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x13.common.ErrorReasonR\x06reason\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\acontext\x18\x03 \x03(\v2 .audit.AuditFailure.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B8Z6github.com/formancehq/ledger/v3/internal/proto/auditpbb\x06proto3"

var (
	file_audit_proto_rawDescOnce sync.Once
	file_audit_proto_rawDescData []byte
)

func file_audit_proto_rawDescGZIP() []byte {
	file_audit_proto_rawDescOnce.Do(func() {
		file_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_proto_rawDesc), len(file_audit_proto_rawDesc)))
	})
	return file_audit_proto_rawDescData
}

var file_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_audit_proto_goTypes = []any{
	(*AuditEntry)(nil),                   // 0: audit.AuditEntry
	(*AuditItem)(nil),                    // 1: audit.AuditItem
	(*AuditSuccess)(nil),                 // 2: audit.AuditSuccess
	(*AuditFailure)(nil),                 // 3: audit.AuditFailure
	nil,                                  // 4: audit.AuditFailure.ContextEntry
	(*commonpb.Timestamp)(nil),           // 5: common.Timestamp
	(*commonpb.CallerSnapshot)(nil),      // 6: common.CallerSnapshot
	(*commonpb.Idempotency)(nil),         // 7: common.Idempotency
	(*signaturepb.SignedApplyBatch)(nil), // 8: signature.SignedApplyBatch
	(commonpb.ErrorReason)(0),            // 9: common.ErrorReason
}
var file_audit_proto_depIdxs = []int32{
	5, // 0: audit.AuditEntry.timestamp:type_name -> common.Timestamp
	2, // 1: audit.AuditEntry.success:type_name -> audit.AuditSuccess
	3, // 2: audit.AuditEntry.failure:type_name -> audit.AuditFailure
	1, // 3: audit.AuditEntry.items:type_name -> audit.AuditItem
	6, // 4: audit.AuditEntry.caller_snapshot:type_name -> common.CallerSnapshot
	7, // 5: audit.AuditEntry.idempotency:type_name -> common.Idempotency
	8, // 6: audit.AuditEntry.signature:type_name -> signature.SignedApplyBatch
	9, // 7: audit.AuditFailure.reason:type_name -> common.ErrorReason
	4, // 8: audit.AuditFailure.context:type_name -> audit.AuditFailure.ContextEntry
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_audit_proto_init() }
func file_audit_proto_init() {
	if File_audit_proto != nil {
		return
	}
	file_audit_proto_msgTypes[0].OneofWrappers = []any{
		(*AuditEntry_Success)(nil),
		(*AuditEntry_Failure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_proto_rawDesc), len(file_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_audit_proto_goTypes,
		DependencyIndexes: file_audit_proto_depIdxs,
		MessageInfos:      file_audit_proto_msgTypes,
	}.Build()
	File_audit_proto = out.File
	file_audit_proto_goTypes = nil
	file_audit_proto_depIdxs = nil
}
