apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ledger.fullname" . }}
  labels:
    {{- include "ledger.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "ledger.fullname" . }}
  selector:
    matchLabels:
      {{- include "ledger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ledger.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
