VERSION 0.8
PROJECT FormanceHQ/ledger

IMPORT github.com/formancehq/earthly:tags/v0.19.0 AS core

FROM core+base-image

CACHE --sharing=shared --id go-mod-cache /go/pkg/mod
CACHE --sharing=shared --id go-cache /root/.cache/go-build

sources:
    FROM core+builder-image

    COPY ../../pkg /src/pkg
    COPY ../../internal /src/internal
    COPY ../../cmd /src/cmd
    COPY ../../*.go /src/
    COPY ../../go.mod /src/
    COPY ../../go.sum /src/

    WORKDIR /src/tools/generator
    COPY --dir cmd examples .
    COPY go.* *.go .

    SAVE ARTIFACT /src

compile:
    FROM +tidy
    CACHE --id go-mod-cache /go/pkg/mod
    CACHE --id go-cache /root/.cache/go-build
    RUN go build -o main
    SAVE ARTIFACT main

build-image:
    FROM core+final-image
    ENTRYPOINT ["/bin/ledger-generator"]
    COPY --pass-args (+compile/main) /bin/ledger-generator
    COPY examples /examples
    ARG REPOSITORY=ghcr.io
    ARG tag=latest
    DO --pass-args core+SAVE_IMAGE --COMPONENT=ledger-generator --REPOSITORY=${REPOSITORY} --TAG=$tag