#!/usr/bin/env just --justfile

set positional-arguments

push-image version='latest':
    docker buildx build . \
        --build-context root=../.. \
        -t ghcr.io/formancehq/ledger-generator:{{ version }} \
        --push \
        --platform linux/amd64,linux/arm64
