/*
Formance Stack API

Open, modular foundation for unique payments flows  # Introduction This API is documented in **OpenAPI format**.  # Authentication Formance Stack offers one forms of authentication:   - OAuth2 OAuth2 - an open protocol to allow secure authorization in a simple and standard method from web, mobile and desktop applications. <SecurityDefinitions /> 

API version: develop
Contact: support@formance.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package formance

import (
	"encoding/json"
)

// TaskWiseDescriptor struct for TaskWiseDescriptor
type TaskWiseDescriptor struct {
	Name *string `json:"name,omitempty"`
	Key *string `json:"key,omitempty"`
	ProfileID *int64 `json:"profileID,omitempty"`
}

// NewTaskWiseDescriptor instantiates a new TaskWiseDescriptor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaskWiseDescriptor() *TaskWiseDescriptor {
	this := TaskWiseDescriptor{}
	return &this
}

// NewTaskWiseDescriptorWithDefaults instantiates a new TaskWiseDescriptor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaskWiseDescriptorWithDefaults() *TaskWiseDescriptor {
	this := TaskWiseDescriptor{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TaskWiseDescriptor) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskWiseDescriptor) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TaskWiseDescriptor) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TaskWiseDescriptor) SetName(v string) {
	o.Name = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *TaskWiseDescriptor) GetKey() string {
	if o == nil || isNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskWiseDescriptor) GetKeyOk() (*string, bool) {
	if o == nil || isNil(o.Key) {
    return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *TaskWiseDescriptor) HasKey() bool {
	if o != nil && !isNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *TaskWiseDescriptor) SetKey(v string) {
	o.Key = &v
}

// GetProfileID returns the ProfileID field value if set, zero value otherwise.
func (o *TaskWiseDescriptor) GetProfileID() int64 {
	if o == nil || isNil(o.ProfileID) {
		var ret int64
		return ret
	}
	return *o.ProfileID
}

// GetProfileIDOk returns a tuple with the ProfileID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaskWiseDescriptor) GetProfileIDOk() (*int64, bool) {
	if o == nil || isNil(o.ProfileID) {
    return nil, false
	}
	return o.ProfileID, true
}

// HasProfileID returns a boolean if a field has been set.
func (o *TaskWiseDescriptor) HasProfileID() bool {
	if o != nil && !isNil(o.ProfileID) {
		return true
	}

	return false
}

// SetProfileID gets a reference to the given int64 and assigns it to the ProfileID field.
func (o *TaskWiseDescriptor) SetProfileID(v int64) {
	o.ProfileID = &v
}

func (o TaskWiseDescriptor) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !isNil(o.ProfileID) {
		toSerialize["profileID"] = o.ProfileID
	}
	return json.Marshal(toSerialize)
}

type NullableTaskWiseDescriptor struct {
	value *TaskWiseDescriptor
	isSet bool
}

func (v NullableTaskWiseDescriptor) Get() *TaskWiseDescriptor {
	return v.value
}

func (v *NullableTaskWiseDescriptor) Set(val *TaskWiseDescriptor) {
	v.value = val
	v.isSet = true
}

func (v NullableTaskWiseDescriptor) IsSet() bool {
	return v.isSet
}

func (v *NullableTaskWiseDescriptor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaskWiseDescriptor(val *TaskWiseDescriptor) *NullableTaskWiseDescriptor {
	return &NullableTaskWiseDescriptor{value: val, isSet: true}
}

func (v NullableTaskWiseDescriptor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaskWiseDescriptor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


