adminPassword: "admin"   # dev only 🙂

service:
  type: ClusterIP

grafana.ini:
  snapshots:
    external_enabled: false
  server:
    root_url: https://grafana.ledger-exp.v2.formance.dev
    serve_from_sub_path: false

deploymentStrategy:
  type: Recreate

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        type: prometheus
        access: proxy
        url: http://vm-victoria-metrics-single-server.monitoring.svc.cluster.local:8428
        isDefault: true
        editable: true
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.monitoring.svc.cluster.local:3200
        editable: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.monitoring.svc.cluster.local:3100
        editable: true

# Optionnel: un minimum de ressources
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

ingress:
  enabled: true
  #ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: zerossl
    nginx.ingress.kubernetes.io/proxy-buffer-size: "4m"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "4m"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"


  hosts:
    - grafana.ledger-exp.v2.formance.dev
  path: /
  pathType: Prefix

  tls:
  - secretName: grafana-tls
    hosts:
      - grafana.ledger-exp.v2.formance.dev

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    # optionnel: si tu veux les ranger par dossier
    # folderAnnotation: grafana_folder
    searchNamespace: monitoring

  datasources:
    enabled: true

persistence:
  enabled: true
  type: pvc
  size: 5Gi
  accessModes:
    - ReadWriteOnce
  finalizers:
    - kubernetes.io/pvc-protection
