/*
 * Formance Stack API
 * Open, modular foundation for unique payments flows  # Introduction This API is documented in **OpenAPI format**.  # Authentication Formance Stack offers one forms of authentication:   - OAuth2 OAuth2 - an open protocol to allow secure authorization in a simple and standard method from web, mobile and desktop applications. <SecurityDefinitions /> 
 *
 * The version of the OpenAPI document: develop
 * Contact: support@formance.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.formance.formance.model;

import com.formance.formance.model.PaymentStatus;
import com.formance.formance.model.TaskBankingCircle;
import com.formance.formance.model.TaskBankingCircleAllOfDescriptor;
import com.formance.formance.model.TaskCurrencyCloud;
import com.formance.formance.model.TaskDummyPay;
import com.formance.formance.model.TaskModulr;
import com.formance.formance.model.TaskStripe;
import com.formance.formance.model.TaskWise;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TasksCursorCursorAllOfDataInner
 */
public class TasksCursorCursorAllOfDataInnerTest {
    private final TasksCursorCursorAllOfDataInner model = new TasksCursorCursorAllOfDataInner();

    /**
     * Model tests for TasksCursorCursorAllOfDataInner
     */
    @Test
    public void testTasksCursorCursorAllOfDataInner() {
        // TODO: test TasksCursorCursorAllOfDataInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'connectorId'
     */
    @Test
    public void connectorIdTest() {
        // TODO: test connectorId
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'descriptor'
     */
    @Test
    public void descriptorTest() {
        // TODO: test descriptor
    }

}
