{
 "title": "Ledger Metrics Dashboard",
 "tags": [
  "ledger",
  "metrics"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values({\"raft.transport.recv.inflight\"},service.node_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Transactions per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(raft.apply_entries.batch_size{service.node_id=\"$node\", scope.name!=\"raft.system\"}[$__rate_interval]))",
     "legendFormat": "Transactions/sec"
    }
   ]
  },
  {
   "title": "Raft Apply Entries Duration - Percentiles (P50/P75/P95/P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(raft.apply_entries.duration_bucket{service.node_id=\"$node\", scope.name=\"raft.node.system\"}[30s])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(raft.apply_entries.duration_bucket{service.node_id=\"$node\", scope.name=\"raft.system\"}[30s])) by (le))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(raft.apply_entries.duration_bucket{service.node_id=\"$node\", scope.name=\"raft.system\"}[30s])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(raft.apply_entries.duration_bucket{service.node_id=\"$node\", scope.name=\"raft.system\"}[30s])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Ping latency",
   "type": "timeseries",
   "description": "RTT latency ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate({\"raft.transport.ping.latency_sum\", \"service.node_id\"=\"$node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate({\"system.memory.utilization\", \"system.memory.state\"=\"used\", \"service.node_id\"=\"$node\"}[$__rate_interval])",
     "legendFormat": "Used"
    },
    {
     "expr": "rate({\"system.memory.utilization\", \"system.memory.state\"=\"free\", \"service.node_id\"=\"$node\"}[$__rate_interval])",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "System memory usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{\"system.memory.usage\", \"service.node_id\"=\"$node\"}",
     "legendFormat": "{{system.memory.state}}"
    }
   ]
  },
  {
   "title": "Go memory allocated",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate({\"go.memory.allocated\", \"service.node_id\"=\"$node\"}[$__rate_interval])",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Go memory allocations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate({\"go.memory.allocations\", \"service.node_id\"=\"$node\"}[$__rate_interval])",
     "legendFormat": "Allocations"
    }
   ]
  },
  {
   "title": "System network traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate({\"system.network.io\", \"network.io.direction\"=\"receive\", \"service.node_id\"=\"$node\"})",
     "legendFormat": "Reception"
    },
    {
     "expr": "rate({\"system.network.io\", \"network.io.direction\"=\"transmit\", \"service.node_id\"=\"$node\"})",
     "legendFormat": "Transmission"
    }
   ]
  },
  {
   "title": "Go memory used",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{\"go.memory.used\", \"service.node_id\"=\"$node\"}",
     "legendFormat": "{{go.memory.type}}"
    }
   ]
  },
  {
   "title": "Go GC goal",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{\"go.memory.gc.goal\", \"service.node_id\"=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host CPU time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate({\"cpu.time\", \"service.node_id\"=\"$node\"})",
     "legendFormat": "{{cpu.mode}}"
    },
    {
     "expr": "{\"go.processor.limit\", \"service.node_id\"=\"$node\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Process CPU time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "targets": [
    {
     "expr": "rate({\"process.cpu.time\", \"service.node_id\"=\"$node\"})",
     "legendFormat": "{{cpu.mode}}"
    }
   ]
  },
  {
   "title": "Goroutine count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "{\"go.goroutine.count\", \"service.node_id\"=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Raft Root", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Transport queue incoming messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(raft.transport.recv.incoming{service.node_id=\"$node\", scope.name=\"raft.transport\"}[30s])",
     "legendFormat": "Incoming {{type}}"
    },
    {
     "expr": "rate(raft.transport.recv.outgoing{service.node_id=\"$node\", scope.name=\"raft.transport\"}[30s])",
     "legendFormat": "Outgoing {{type}}"
    }
   ]
  },
  {
   "title": "Transport queue inflight messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(raft.transport.recv.incoming{service.node_id=\"$node\", scope.name=\"raft.transport\"}[$__rate_interval] - raft.transport.recv.outgoing{service.node_id=\"$node\", scope.name=\"raft.transport\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Transport queue full count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raft.transport.recv.full{service.node_id=\"$node\", scope.name=\"raft.transport\"}",
     "legendFormat": "{{scope.name}}"
    }
   ]
  },
  {
   "title": "Transport Unreachable Channel - Inflight Messages (by Scope)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(raft.transport.unreachable.incoming{service.node_id=\"$node\", scope.name=\"raft.transport\"})",
     "legendFormat": "Incoming"
    },
    {
     "expr": "rate(raft.transport.unreachable.outgoing{service.node_id=\"$node\", scope.name=\"raft.transport\"})",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "Transport Unreachable Channel - Inflight Messages (by Scope)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(raft.transport.unreachable.incoming{service.node_id=\"$node\", scope.name=\"raft.transport\"} - raft.transport.unreachable.outgoing{service.node_id=\"$node\", scope.name=\"raft.transport\"})",
     "legendFormat": "Incoming"
    }
   ]
  },
  {
   "title": "Transport Unreachable Channel - Full Messages (by Scope)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raft.transport.unreachable.full{service.node_id=\"$node\", scope.name=\"raft.transport\"}",
     "legendFormat": "{{scope.name}}"
    }
   ]
  },
  { "title": "Ledger", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Raft Apply Entries Duration - Percentiles (P50/P75/P95/P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(raft.apply_entries.duration_bucket{service.node_id=\"$node\", scope.name!=\"raft.node.system\"}[$__rate_interval])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(raft.apply_entries.duration_bucket{service.node_id=\"$node\", scope.name!=\"raft.system\"}[$__rate_interval])) by (le))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(raft.apply_entries.duration_bucket{service.node_id=\"$node\", scope.name!=\"raft.system\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(raft.apply_entries.duration_bucket{service.node_id=\"$node\", scope.name!=\"raft.system\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Batch size distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "rate({\"raft.apply_entries.batch_size_distribution_count\", \"service.node_id\"=\"$node\", \"scope.name\"!=\"raft.node.system\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot creation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate({\"raft.syncer.create_snapshot.duration_sum\", \"service.node_id\"=\"$node\", \"scope.name\"=\"raft.node.ledger\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SQL latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate({\"db.sql.latency_sum\", method=\"sql.conn.begin_tx\", \"service.node_id\"=\"$node\"}[$__rate_interval]))",
     "legendFormat": "BeginTX"
    },
    {
     "expr": "sum(rate({\"db.sql.latency_sum\", method=\"sql.conn.exec\", \"service.node_id\"=\"$node\"}[$__rate_interval]))",
     "legendFormat": "Conn Exec"
    },
    {
     "expr": "sum(rate({\"db.sql.latency_sum\", method=\"sql.conn.prepare\", \"service.node_id\"=\"$node\"}[$__rate_interval]))",
     "legendFormat": "Prepare"
    },
    {
     "expr": "sum(rate({\"db.sql.latency_sum\", method=\"sql.conn.query\", \"service.node_id\"=\"$node\"}[$__rate_interval]))",
     "legendFormat": "Query"
    },
    {
     "expr": "sum(rate({\"db.sql.latency_sum\", method=\"sql.rows\", \"service.node_id\"=\"$node\"}[$__rate_interval]))",
     "legendFormat": "Rows"
    },
    {
     "expr": "sum(rate({\"db.sql.latency_sum\", method=\"sql.stmt.exec\", \"service.node_id\"=\"$node\"}[$__rate_interval]))",
     "legendFormat": "Statement Exec"
    },
    {
     "expr": "sum(rate({\"db.sql.latency_sum\", method=\"sql.tx.commit\", \"service.node_id\"=\"$node\"}[$__rate_interval]))",
     "legendFormat": "CommitTX"
    }
   ]
  },
  {
   "title": "Pending responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "{\"raft.transport.sending.pending_response\", \"service.node_id\"=\"$node\"}",
     "legendFormat": "Peer : {{scope.attributes.peer}}"
    }
   ]
  },
  {
   "title": "Propose queue incoming messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(raft.node.propose.incoming{service.node_id=\"$node\", scope.name!=\"raft.node.system\"}[$__rate_interval])",
     "legendFormat": "Incoming"
    },
    {
     "expr": "rate(raft.node.propose.outgoing{service.node_id=\"$node\", scope.name!=\"raft.node.system\"}[$__rate_interval])",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "Propose queue inflight messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(raft.node.propose.incoming{service.node_id=\"$node\", scope.name!=\"raft.node.system\"}[$__rate_interval] - raft.node.propose.outgoing{service.node_id=\"$node\", scope.name!=\"raft.node.system\"}[$__rate_interval])",
     "legendFormat": "Incoming"
    },
    { "legendFormat": "Outgoing" }
   ]
  },
  {
   "title": "Propose queue full count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "raft.node.propose.full{service.node_id=\"$node\", scope.name!=\"raft.node.system\"}",
     "legendFormat": "{{scope.name}}"
    }
   ]
  },
  {
   "title": "Transport Peer Sending Channel - Inflight Messages (by Peer)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(raft.transport.peer.sending.incoming{service.node_id=\"$node\"}[$__rate_interval])) by (scope.attributes.peer, type)",
     "legendFormat": "Peer {{scope.attributes.peer}} : {{type}}"
    }
   ]
  },
  {
   "title": "Transport Peer Sending Channel - Full errors",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({\"raft.transport.peer.sending.full\", \"service.node_id\"=\"$node\"}[$__rate_interval]) by (peer, type)",
     "legendFormat": "Peer {{peer}}: {{type}}"
    }
   ]
  },
  {
   "title": "Transport Peer Sending Channel - Inflight Messages (by Peer)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{\"raft.transport.peer.sending.inflight\", \"service.node_id\"=\"$node\"}",
     "legendFormat": "Peer {{scope.attributes.peer}} : {{type}}"
    }
   ]
  },
  {
   "title": "Reception channel (inflights)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "rate({\"raft.multiplexed_transport.ledger.recv.incoming\", \"service.node_id\"=\"$node\"}[$__rate_interval])",
     "legendFormat": "Peer {{peer}} : {{type}}"
    }
   ]
  },
  {
   "title": "Reception channel (full)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{\"raft.multiplexed_transport.ledger.recv.full\", \"service.node_id\"=\"$node\"}[$__rate_interval]",
     "legendFormat": "Peer {{peer}} : {{type}}"
    }
   ]
  },
  {
   "title": "Unreachable channel (inflights)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "rate({\"raft.multiplexed_transport.ledger.unreachable.incoming\", \"service.node_id\"=\"$node\"}[$__rate_interval])",
     "legendFormat": "Peer {{peer}}"
    }
   ]
  },
  {
   "title": "Unreachable channel (full)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "expr": "rate({\"raft.multiplexed_transport.ledger.unreachable.full\", \"service.node_id\"=\"$node\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}