// Code generated by protoc-gen-reader. DO NOT EDIT.
// source: events.proto

package eventspb

import (
	commonpb "github.com/formancehq/ledger/v3/internal/proto/commonpb"
)

// EventReader provides read-only access to Event.
// Call Mutate() to obtain a mutable clone.
type EventReader interface {
	GetType() commonpb.EventType
	GetLedger() string
	GetDate() commonpb.TimestampReader
	GetLogSequence() uint64
	GetLog() commonpb.LogReader
	Mutate() *Event
}

type eventReadonly struct{ v *Event }

func (r *eventReadonly) GetType() commonpb.EventType {
	return r.v.GetType()
}

func (r *eventReadonly) GetLedger() string {
	return r.v.GetLedger()
}

func (r *eventReadonly) GetDate() commonpb.TimestampReader {
	v := r.v.GetDate()
	if v == nil {
		return nil
	}
	return v.AsReader()
}

func (r *eventReadonly) GetLogSequence() uint64 {
	return r.v.GetLogSequence()
}

func (r *eventReadonly) GetLog() commonpb.LogReader {
	v := r.v.GetLog()
	if v == nil {
		return nil
	}
	return v.AsReader()
}

func (r *eventReadonly) Mutate() *Event {
	return r.v.CloneVT()
}

// AsReader returns a read-only view of this Event.
func (m *Event) AsReader() EventReader {
	if m == nil {
		return nil
	}
	return &eventReadonly{v: m}
}

// Mutate returns a mutable deep clone of this Event.
func (m *Event) Mutate() *Event {
	return m.CloneVT()
}
