// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"openapi/pkg/utils"
	"time"
)

type TransactionResponse struct {
	// Transaction ID (assigned by the system)
	ID        *int64            `json:"id,omitempty"`
	Metadata  map[string]any    `json:"metadata,omitempty"`
	Postings  []PostingResponse `json:"postings,omitempty"`
	Reference *string           `json:"reference,omitempty"`
	// Transaction timestamp (ISO 8601 format)
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

func (t TransactionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TransactionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TransactionResponse) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TransactionResponse) GetMetadata() map[string]any {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *TransactionResponse) GetPostings() []PostingResponse {
	if o == nil {
		return nil
	}
	return o.Postings
}

func (o *TransactionResponse) GetReference() *string {
	if o == nil {
		return nil
	}
	return o.Reference
}

func (o *TransactionResponse) GetTimestamp() *time.Time {
	if o == nil {
		return nil
	}
	return o.Timestamp
}
