version: '3'

vars:
  COMPONENT:
    sh: cat go.mod |head -1|cut -d \  -f2|cut -d / -f 3

tasks:
  tests:
    cmds:
      - go test -p 1 -coverpkg ./... -coverprofile coverage.out -covermode atomic ./...
  lint:
    cmds:
    - golangci-lint run -v --fix
  build:
    cmds:
    - go build
  build-image:
    cmds:
    - docker build -t github.com/formancehq/{{.COMPONENT}} .
  run-image:
    deps:
    - build-image
    cmds:
    - docker run --rm github.com/formancehq/{{.COMPONENT}}
