version: '3'

vars:
  VERSION: v1.4.1

tasks:

  template:
    desc: Extract templates
    preconditions:
      - sh: "[ \"{{.CLI_ARGS}}\" != \"\" ]"
        msg: Please specify generator as first cli arg (ie "task template -- go")
    cmds:
      - >
        docker run --rm -w /local -v ${PWD}:/local openapitools/openapi-generator-cli:latest author 
        template -g {{.CLI_ARGS}} -o templates/{{.CLI_ARGS}}

  generate:
    desc: Generate client code
    preconditions:
      - sh: "[ \"{{.CLI_ARGS}}\" != \"\" ]"
        msg: Please specify generator as first cli arg (ie "task generate -- go")
    cmds:
      - cp -R ./../pkg/api/controllers/swagger.yaml swagger.yaml
      - sed -i -e "s/LEDGER_VERSION/{{.VERSION}}/g" swagger.yaml
      - >
        docker run --rm -w /local -v ${PWD}:/local openapitools/openapi-generator-cli:latest generate
        -i ./swagger.yaml
        -g {{ (split "-" .CLI_ARGS)._0 }}
        -c ./configs/{{.CLI_ARGS}}.yaml
        -o ./sdks/{{.CLI_ARGS}}
        --git-user-id=numary
        --git-repo-id=numary-sdk-{{.CLI_ARGS}}
        -p packageVersion={{.VERSION}}

  test:
    desc: Test client code
    preconditions:
      - sh: "[ \"{{.CLI_ARGS}}\" != \"\" ]"
        msg: Please specify generator as first cli arg (ie "task test -- go")
      - sh: "[[ -e sdks/{{.CLI_ARGS}}/Taskfile.yml ]]"
        msg: "Not Taskfile found. You have to create a taskfile in ./sdks/{{.CLI_ARGS}}/ with a 'test' task"
    vars:
      RANDOM:
        sh: "echo $$"
    cmds:
      - task: generate
      - |
        cd ./sdks/{{.CLI_ARGS}}
        task test
