image:
  repository: ghcr.io/formancehq/benchmark-operator
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

serviceAccount:
  create: true
  name: ""

rbac:
  create: true
  # Additional RBAC rules for managing custom resources created by benchmarks.
  # Example for ledger resources:
  #   additionalRules:
  #     - apiGroups: ["ledger.formance.com"]
  #       resources: ["ledgerservices", "ledgers"]
  #       verbs: ["get", "list", "watch", "create", "delete"]
  additionalRules: []

watchNamespace: ""

env:
  GRAFANA_URL: ""
  GRAFANA_USER: ""
  GRAFANA_PASSWORD: ""
  SNAPSHOT_PER_NODE: "true"
  NODE_METRIC: ""
  NODE_LABEL: ""
  DATASOURCE_NAME: "VictoriaMetrics"
  SNAPSHOT_NAME_PREFIX: "k6-benchmark"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
