# Default values for k6-run chart
script: ""
spec:
  parallelism: 1
metadata:
  namespace: ""
runner:
  env:
    ledgerUrl: "http://ledger-exp.ledger.svc.cluster.local:9000"
    stages: ""
  otlp:
    endpoint: "otel-opentelemetry-collector.monitoring.svc.cluster.local:4317"
archiveData: ""
