# Default values for k6-run chart
script: ""
spec:
  parallelism: 1
metadata:
  namespace: ""

# Name of the ledger to create/delete via gRPC (optional).
ledgerName: ""

# LedgerService spec (passthrough to LedgerService CR).
ledgerService: {}

runner:
  env: {}
  # nodeSelector applied to k6 runner pods
  nodeSelector: {}
  # tolerations applied to k6 runner pods
  tolerations: []

archiveData: ""
