workflowVersion: 1.0.0
speakeasyVersion: v1.517.3
sources:
    Formance-OAS:
        inputs:
            - location: ../../openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/formance/formance/formance-oas
targets:
    formance:
        target: go
        source: Formance-OAS
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/formance/gfyrag/formance-oas-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
