---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors-all
spec:
  headers:
    accessControlAllowOriginList:
    - "*"
    accessControlAllowHeaders:
    - "Authorization"
    - "content-type"
    accessControlAllowMethods:
    - "*"
    accessControlAllowCredentials: true
    accessControlMaxAge: 100
    addVaryHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
spec:
  stripPrefix:
    prefixes:
    - /api/auth
    - /api/dex
    - /api/jaeger
    - /api/ledger
    - /api/webhooks
---
apiVersion: stack.formance.com/v1beta2
kind: Configuration
metadata:
  name: stacks
spec:
  # Define global ingress configuration
  ingress:
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: default-stripprefix@kubernetescrd, default-cors-all@kubernetescrd
  monitoring:
    traces:
      otlp:
        endpoint: otel-collector-opentelemetry-collector.default.svc.cluster.local
        insecure: true
        mode: grpc
        port: 4317
        resourceAttributes: "foo=bar"
  temporal:
    address: "local-operator.sihc8.tmprl.cloud:7233"
    namespace: "local-operator.sihc8"
    tls:
      crt: |
        -----BEGIN CERTIFICATE-----
        MIIDvDCCAqSgAwIBAgIUTQMMmzxFv5yUcH6H3l3AI+o01CswDQYJKoZIhvcNAQEL
        BQAwFzEVMBMGA1UEAxMMZm9ybWFuY2UuY29tMB4XDTIzMDEyMDEwMTExNVoXDTMz
        MDExNzA5MTE0NVowGTEXMBUGA1UEAwwOKi5mb3JtYW5jZS5jb20wggEiMA0GCSqG
        SIb3DQEBAQUAA4IBDwAwggEKAoIBAQC7NlrS6MuTXIEdUIs4FKaQY3krG4w7KKpr
        /ztQXYJ/4kyit+xnP6uuIiEs5qwfWJnS3V5a5ZGHF6x2GdZAKRMlHt3xxL7K39xu
        sY06kwCcNP7eNDKdz4fbaRQ109vM6ANY6h1VgZ7A/e49swV5gpJ+YfPqRykood6H
        afGSL0jLzFqTujjbNV6ZwIRD7ZMIa/NOYlb6oxlfZZXtMKwPY7An5fpDyEVJCRrP
        G2dShu0WHZlctzCjR3WFNfNPIN44yaPdF9q/WweWwcei8pcoz+d5m9sjUeviIhfb
        dXODDWbwJu1i1COOGz0suWchPQJCYGc9xOigCDWrH5A2BSu3C2gzAgMBAAGjgf0w
        gfowDgYDVR0PAQH/BAQDAgOoMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
        AjAdBgNVHQ4EFgQU564vj1K2ZEtgkcLtl5JurExg6AcwHwYDVR0jBBgwFoAU9JfZ
        psQJOHGZ+vYuZzZLPQRLYmwwOwYIKwYBBQUHAQEELzAtMCsGCCsGAQUFBzAChh9o
        dHRwOi8vMTI3LjAuMC4xOjgyMDAvdjEvcGtpL2NhMBkGA1UdEQQSMBCCDiouZm9y
        bWFuY2UuY29tMDEGA1UdHwQqMCgwJqAkoCKGIGh0dHA6Ly8xMjcuMC4wLjE6ODIw
        MC92MS9wa2kvY3JsMA0GCSqGSIb3DQEBCwUAA4IBAQAW9ispaeU9UnoTUihFf+cx
        RzNQ+JbxGoAihvri25YbxnXifjd/v9D9GnP50dkhfPcBQZnFtspsg9gAMla/Hhl8
        3g4liINIIMYy1wHak9K22a3+k5yKspbFovtvsOoac5jt0fIl+2MiBY3G1V7lKiZL
        LQiOlDdmBlzkldGD3ubunuh1NTMUbnBF8JTKquSqZv1i7Js6UbelJg89g9gh4N+R
        gK3El3m5jc2sLFQbuWiDx8gZtNWAd5wihs9ban87Dc9YOZ6695Dd/woifhMRuIWG
        YIezLQgPPPiyvTcTARipcA68eVu5GpFG8L3BKR9Mz5TThasRnsFwfa/ylbZkSWun
        -----END CERTIFICATE-----
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEowIBAAKCAQEAuzZa0ujLk1yBHVCLOBSmkGN5KxuMOyiqa/87UF2Cf+JMorfs
        Zz+rriIhLOasH1iZ0t1eWuWRhxesdhnWQCkTJR7d8cS+yt/cbrGNOpMAnDT+3jQy
        nc+H22kUNdPbzOgDWOodVYGewP3uPbMFeYKSfmHz6kcpKKHeh2nxki9Iy8xak7o4
        2zVemcCEQ+2TCGvzTmJW+qMZX2WV7TCsD2OwJ+X6Q8hFSQkazxtnUobtFh2ZXLcw
        o0d1hTXzTyDeOMmj3Rfav1sHlsHHovKXKM/neZvbI1Hr4iIX23Vzgw1m8CbtYtQj
        jhs9LLlnIT0CQmBnPcTooAg1qx+QNgUrtwtoMwIDAQABAoIBADEmhhXVVI0tviAq
        I0Ln+Qrzcr5kjx6BAK015yakRjy49xHJY+F/j905zKfzL8FTC5+WyszmdJyZFIg1
        JFDX99TJE9ADrWup9j+BkeiM654XM8q2vYs9DxgFsG6pXo2fZDGV1Xm7fCiDAmdk
        ds1+AGP554XchOvMA5ZdtDSDAYOvgiTnhR+ic881U+L4DkHt+HRHv8ZFcuuUa5z/
        IVSoAR/yIUcQZeimp2l/SZoYk50pfzFNksAfnye6OS0PFhwNT/MX1+3u3ytm34Yj
        fcXG/c1uKwfIR9GA/VseRDah0k+8fhsgECGeqtEJwUOqAzAmVWfyaCy6Ud/whAQP
        qtl9aTECgYEA3/QJQO9MhlKCpxyOuTm/vAb/Tx0hO6Erd+jWwv8P2GMpM1n4kZd8
        O5/PPzPQKDlHu2gqNqwfqL77+RWw8xHQ25mUtfLVCiIPF4SVsNLD66E9KzU4yYpS
        p40QckRHdaOO5gJmubkWV3UQczq2rPZyPs/Msy0r/8ilq4smMIjYpW8CgYEA1gBo
        H2v14v7x4LhgpdJrMOg4gc80qJyFpxYxw2T/CdmyjVhsVCDGF/0d3j4Lo/SJB2y6
        YolJb6T3orCUnxOE8CHUktgHB7Auheh1Ls4xyA/HKExRvO8kh/YkBn+z3bIki0QB
        w29yRx3d8hBu9hJT52f9veXN6wqzrp68H0Iw730CgYEA3nB/eHW25nuxtdZRlHxd
        ip7Qm33tclLE4BbuqUO6M01asNyeXc2+4WH78WS/ThSGwQfXVfJkh7EaiO8YkHWT
        o2rKIGaPX78wikVwgO73FmVSYkY8n0G6kx0zxqs25wuLdb3Q1ouWO0vVCP66TtWB
        6A1x3k3xs99RXi+ZwP9LYBUCgYAej3pPGmzH2N6T1+C9bXovRspjB0Me3RNdFBdR
        LwgY0QTlmH4H2ZJQdK4iQbwJ0u8Kp2VKkw5wqh9PFWZz/Sab4EjqG32NhIRwTQ0G
        /R0w08f+Ij/9+iy+WdE1OGFoRHthg/m4fh7Utxgt7FjcPSvMPRaIWtv4N9QHGNYG
        pL42RQKBgCRDE6abLoeUN38GIfQ09YeWoaRgQ0WYzeNwzu1Yl2VwLifWjrbukKZX
        p+3B/M7FaeXhjJ3qSVDXBXqI94B7NLjH32CxKsuil2ry7p+lLzdBDquUtMoL17lg
        xpAA8tqK3W+E8gj01vKhbcGP28373jREU016/HCbEHRsNxW/BGDj
        -----END RSA PRIVATE KEY-----
  kafka:
    brokers:
      - redpanda.default.svc.cluster.local:9092
  services:
    auth:
      postgres:
        host: postgres-postgresql.default.svc.cluster.local
        port: 5432
        username: formance
        password: formance
      staticClients:
      - id: foo
        public: true
        secrets:
        - bar
    ledger:
      postgres:
        host: postgres-postgresql.default.svc.cluster.local
        port: 5432
        username: formance
        password: formance
        disableSSLMode: true
      locking:
        strategy: redis
        redis:
          uri: redis://redis-headless.default.svc.cluster.local:6379
    payments:
      postgres:
        host: postgres-postgresql.default.svc.cluster.local
        port: 5432
        username: formance
        password: formance
        disableSSLMode: true
    orchestration:
      postgres:
        host: postgres-postgresql.default.svc.cluster.local
        port: 5432
        username: formance
        password: formance
        disableSSLMode: true
    search:
      elasticSearch:
        host: zinc.default.svc.cluster.local
        port: 4080
        scheme: http
        pathPrefix: /api
        useZinc: true
        basicAuth:
          username: admin
          password: "Complexpass#123"
    webhooks:
      postgres:
        host: postgres-postgresql.default.svc.cluster.local
        port: 5432
        username: formance
        password: formance
        disableSSLMode: true
    counterparties:
      postgres:
        host: postgres-postgresql.default.svc.cluster.local
        port: 5432
        username: formance
        password: formance
        disableSSLMode: true
---
apiVersion: stack.formance.com/v1beta2
kind: Versions
metadata:
  name: default
spec:
  control: 59e871d64514ec01c84ea18b34cf0788d17d7f63
  search: fa29fbcfa983990ef1042274e3d928713865b6a7
  orchestration: 6d3e981b6d05224caca139f3920373a8cee0ba3c
---
apiVersion: stack.formance.com/v1beta2
kind: Stack
metadata:
  name: stack1
spec:
  debug: true
  dev: true
  scheme: http
  host: host.k3d.internal
  seed: stacks
  auth:
    delegatedOIDCServer:
      issuer: http://host.k3d.internal/api/dex
      clientID: dexclient
      clientSecret: dexclient
    staticClients:
    - id: foo2
      secrets:
      - bar2
