name: Antithesis Integration
on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Run Antithesis tests after pushing images"
        type: boolean
        default: true
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "test/antithesis/**"
  schedule:
    - cron: "0 10 * * *"

jobs:
  push-antithesis-images:
    name: Push Images to Antithesis
    runs-on: shipfox-4vcpu-ubuntu-2404
    env:
      ANTITHESIS_PASSWORD: ${{ secrets.ANTITHESIS_PASSWORD }}
      ANTITHESIS_SLACK_REPORT_RECIPIENT: ${{ secrets.ANTITHESIS_SLACK_REPORT_RECIPIENT }}
      ANTITHESIS_REPOSITORY: ${{ secrets.ANTITHESIS_REPOSITORY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"

      - name: Setup Just
        uses: extractions/setup-just@v3
        with:
          just-version: "1.40.0"

      - name: Setup Environment
        uses: ./.github/actions/default
        with:
          token: ${{ secrets.NUMARY_GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "NumaryBot"
          password: ${{ secrets.NUMARY_GITHUB_TOKEN }}

      - name: Login to Antithesis Docker Registry
        run: |
          echo '${{ secrets.ANTITHESIS_JSON_KEY }}' | docker login -u _json_key https://us-central1-docker.pkg.dev --password-stdin

      - name: Build and Push Config Image
        run: |
          cd test/antithesis
          just requirements-build

      - name: Run Antithesis Tests
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.run_tests == true }}
        run: |
          cd test/antithesis
          just run-6min
