name: "Pull Request Labeler"
on:
  - pull_request_target
#  - pull_request

jobs:
  Triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
