name: Release
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  GoReleaser:
    runs-on: namespace-profile-linux-amd64-4vcpu
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          dissociate: true
      - name: Setup Env
        uses: ./.github/actions/default
      - name: Set up Docker Buildx
        uses: namespacelabs/nscloud-setup-buildx-action@d059ed7184f0bc7c8b27e8810cea153d02bcc6dd # v0.0.23
      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: NumaryBot
          password: ${{ secrets.NUMARY_GITHUB_TOKEN }}
      - run: >
          nix develop --command just release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
      - name: Build and push operator image
        run: >
          nix develop --command just operator-docker-build ${{ github.ref_name }}
      - name: Publish operator Helm charts
        env:
          GITHUB_TOKEN: ${{ secrets.NUMARY_GITHUB_TOKEN }}
        run: |
          version="${GITHUB_REF_NAME#v}"
          nix develop --command just operator-helm-publish "$version"
