name: Release
on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  GoReleaser:
    uses: formancehq/ci/.github/workflows/go-release.yml@main
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    secrets:
      NUMARY_GITHUB_TOKEN: ${{ secrets.NUMARY_GITHUB_TOKEN }}
      SPEAKEASY_API_KEY: ${{ secrets.SPEAKEASY_API_KEY }}
      FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
      GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
