name: Build for Control
on:
  workflow_call:
    secrets:
      NUMARY_GITHUB_TOKEN:
        required: true
        description: GitHub token with access to the repo

jobs:
  build:
    name: 'Build Control'
    runs-on: ubuntu-latest
    steps:
      - run: curl -OL https://github.com/numary/control/releases/download/1.2.0/numary-control-1.2.0.tar.gz
      - run: tar -zxvf numary-control-1.2.0.tar.gz
      - run: rm -rf numary-control-1.2.0.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          name: control-dist
          path: ./**
