name: Test Generate V2.1
on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened, labeled ]

jobs:
  Run:
    uses: ./.github/workflows/dataset.yml
    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      KUBE_APISERVER: ${{ secrets.FORMANCE_DEV_KUBE_API_SERVER_ADDRESS }}
      KUBE_TOKEN: ${{ secrets.FORMANCE_DEV_KUBE_TOKEN }}
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
    with:
      ledger-version: 'v2.1'
      organization: 'formance'
      rds-db-subnet-group-name: 'staging-eu-west-1-hosting'
      until-log-id: 100000
      generator-version: 'latest'
      namespace: ledger-dataset-v2-1
      create-snapshot: false
      preview: false
      refresh: true
      destroy: false
      script: |
        const plain = `vars {
          account $order
          account $seller
        }
        send [USD/2 100] (
          source = @world
          destination = $order
        )
        send [USD/2 1] (
          source = $order
          destination = @fees
        )
        send [USD/2 99] (
          source = $order
          destination = $seller
        )`

        function next(iteration) {
          return [{
            action: 'CREATE_TRANSACTION',
            data: {
              script: {
                plain,
                vars: {
                  order: `orders:${uuid()}`,
                  seller: `sellers:${iteration % 5}`
                }
              }
            }
          }]
        }
